### PR TITLE
tell people to speak up about snapshot blockers

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
Suggested by @stefanobaghino-da; thanks!

CHANGELOG_BEGIN
CHANGELOG_END

### CODE REVIEW

**Comment by garyverhaegen-da** [comment]
Is the `@here` overkill here? We've just spent some effort reducing noise on the team-daml channel, so this is going backwards a bit, but it's a once-a-week thing.

**Comment by cocreature** [comment]
> Is the `@here` overkill here? We've just spent some effort reducing noise on the team-daml channel, so this is going backwards a bit, but it's a once-a-week thing.

I’d remove it.

**Comment by stefanobaghino-da** [comment]
I guess we can see if this level is adequate and turn it up a bit if we see a reason for it. 🙂

**Review by stefanobaghino-da — APPROVED** [review]

**Review by cocreature — APPROVED** [review]
Thanks!

**Pull request merged**
