### PR TITLE
Prepare release note for next release

### PR DESCRIPTION
**Pull request by garyverhaegen-da**

### CODE REVIEW

**Comment by martin-drhu-da** [comment]
The PR title/description could be better. ;)

**Comment by garyverhaegen-da** [comment]
> The PR title/description could be better. ;)

I've tried my best. _Constructive_ criticism welcome!

**Comment by neil-da** [comment]
> I've tried my best. _Constructive_ criticism welcome!

"Update changelog in advance of release" is a bit clearer.

**Comment by martin-drhu-da** [comment]
@garyverhaegen-da "Prepare release note for next release" for instance.

**Comment by garyverhaegen-da** [comment]
> @garyverhaegen-da "Prepare release note for next release" for instance.

Updated PR and commit titles.

**Pull request merged**
