### PR TITLE
Fix name clashes with choices

### LINKED ISSUE #16853: Choice desugar collisions
We desugar choices to `_choice$_[templatename][choicename]` without anything inbetween the template and choice
Meaning the following 2 templates in a file will cause an error, saying multiple definitions of the same name

```hs
module Main where

template Account with
    p : Party
  where
  signatory p
  choice SafeCall : ()
    controller p
    do pure ()

template AccountSafe with
    pp : Party
  where
    signatory pp
    choice Call : ()
      controller p
      do pure ()
```

Ideally we should put a `$` between the template and choice name, so a collision isn't possible.

### PR DESCRIPTION
**Pull request by samuel-williams-da**
Resolves #16853 
Relevant ghc changes: https://github.com/digital-asset/ghc/pull/166

This PR just updates GHC and updates the desugar golden files

### CODE REVIEW

**Review by nickchapman-da — APPROVED** [review]
Nice!
Thanks

**Review by akrmn — APPROVED** [review]
nice, thank you @samuel-williams-da!

**Comment by basvangijzel-DA** [comment]
Are there any backwards compatibility concerns for this? E.g. should this go into the changelog?

**Comment by samuel-williams-da** [comment]
I don't _think_ so, but I need to look further into how these definitions are found by the engine - I'll do that today

**Comment by samuel-williams-da** [comment]
Confirmed, it won't affect anything, the name is only used for the typechecker, and is thrown away in LFConversion

**Review by basvangijzel-DA — APPROVED** [review]

**Comment by samuel-williams-da** [comment]
Platform independence test failed? Quite odd given the only changes have been to a file that runs as is on all platforms

**Pull request merged**
