### PR TITLE
Ensure `NodeInfo` derived properties `informeesOfNode` and `requireAuthorizers` always return

### PR DESCRIPTION
**Pull request by fabiotudone-da**
### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by fabiotudone-da** [comment]
@dajmaki Am I missing something or is it actually a meaningful change?

**Comment by dajmaki** [comment]
I would rather have it throw if this happens as it’s a serious bug if they’re missing. Returning Set.empty might mask real problems. Perhaps throw a more meaningful error?

**Comment by fabiotudone-da** [comment]
Yeah that's a possibility, I wonder why are they optional in the first place though

**Comment by dajmaki** [comment]
Backwards compatibility of course :)

**Pull request merged**
