### PR TITLE
participant-integration-api: Make the initial ledger config optional. [KVL-1046]

### PR DESCRIPTION
**Pull request by SamirTalwar-DA**
### Changelog

- **[Integration Kit]** The initial ledger configuration is now optional; if it is not specified, the participant will not attempt to submit a configuration, but instead wait for something else to provision the ledger with a configuration.

  This behavior is intended to be used by ledger drivers that have alternative means of setting up the initial ledger configuration. If no configuration is provisioned, the participant server will not be able to submit commands to the ledger.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by nicu-da — APPROVED** [review]

**Review by fabiotudone-da — COMMENTED** [review]
Does it makes sense to add a test for the new "don't inizialize a configuration if not asked to" behavior?

**Comment by SamirTalwar-DA** [comment]
@fabiotudone-da: Yeah, you're right. I think `LedgerConfigInitializer` needs some tests, which is a shame because it's kind of heavyweight. I'll add some as part of this PR.

**Comment by SamirTalwar-DA** [comment]
OK, looked into this and I think while it's possible to write tests for this, they'll have to be integrated tests and quite unpleasant. Perhaps some further refactoring could make it more testable but honestly, I'm not sure it's worth it.

**Review by fabiotudone-da — APPROVED** [review]

**Comment by fabiotudone-da** [comment]
> OK, looked into this and I think while it's possible to write tests for this, they'll have to be integrated tests and quite unpleasant. Perhaps some further refactoring could make it more testable but honestly, I'm not sure it's worth it.

Then it's fine IMO, perhaps let's take a note for the future to refactor it further so that it's more testable.

**Pull request merged**
