### PR TITLE
Remove ExcludeFromDamlParsing notes, because they no longer do anything

### PR DESCRIPTION
**Pull request by bethaitman-da**

### CODE REVIEW

**Comment by bethaitman-da** [comment]
Previously we tested DAML code inside snippets, and this annotation let you skip that testing. Now, we don't, so the annotation is pointless.

The follow-up to this (which I'm also doing) is moving as many of these snippets as I can to real daml files, so then they will be under test. Some of them are pseudocode but it should be possible for most of them.

**Comment by bethaitman-da** [comment]
(the fact that CI is passing on this demonstrates that the annotation changes nothing)

**Comment by moritzkiefer-da** [comment]
We could probably also reinstantiate testing code inside snippets if that makes your life significantly easier than moving the snippets to DAML files.

**Comment by bethaitman-da** [comment]
I think it's actually _easier_ to create a correct code snippet inside its own file, so the only thing that's annoying is the one-time switchover. But thanks anyway!

**Pull request merged**
