### PR TITLE
shut down ElasticSearch

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
The cluster shuts down about once every two weeks and takes a couple
hous to get back up. It's been off for a few days right now and as far
as I'm aware nobody noticed.

My personal assessment is that this is costing us more in maintenance
(not to mention running) costs than what we're getting out of it.

CHANGELOG_BEGIN
CHANGELOG_END

### CODE REVIEW

**Comment by garyverhaegen-da** [comment]
I'm open to the possibility that other people are actually getting value from this; if so, please speak up here so we can figure out how to move forward.

cc @cocreature @aherrmann-da

**Review by cocreature — APPROVED** [review]
I’m fine with shutting this down if others agree.

Let me try to provide some historic context of how we got there, what it achieved and where it failed:

I pushed for creating this at a time when our builds were much flakier than they are now and even slower. Things just seemed to have gotten worse over time with no clear indication on what caused it. The Canton team had successfully started tracking their test flakes and invested in fixing them. I didn’t want to start fixing things without clear data on what is causing issues and I also wanted to make sure we don’t regress over time so collecting data and displaying them in an easy to consume fashion seemed like the most reasonable option.

I don’t recall why we went for elastic search instead of pushing to datadog, I think @garyverhaegen-da suggested that but could be misremembering. Dunno if a managed services would have been better (that’s what Canton uses) in retrospect. At least I underestimated how complex it was to setup ES and keep it running and maybe also how hard it was to work with it for custom queries (at least for me).

In the beginning I used it a lot and fixed a number of issues both around flakes (e.g., the flakes in the damlc integration tests, create-daml-app, typescript integration tests were all discovered and fixed that way) and a number of slow tests (sped up stable package tests, integration tests, create-daml-app tests, …).

So why did I/we stop using it? I can only really speak to my own reasons:

1. First, it seemed like the buy in across teams wasn’t sufficient. Reporting flakes isn’t useful if people don’t prioritize them. And if someone looked at it at all, the solution was often to mark things flaky which just turns it into a slow build instead of a flaky one.
2. Next one, was slow builds: What killed my interest in trying to improve that was discovering that >1h of our test time went to ledger API conformance tests. It just didn’t seem sensible to start speeding anything else up significantly with that being by far the largest factor in our slow builds and I failed to get buy in to fix those (and couldn’t fix them myself). Some of them have now finally been cleaned up two weeks ago with things like sandboxes being deleted so maybe worth revisiting.
3. The last one for me was unclarity around the future of our current build & CI setup. There seemed to be an increasing (justified) dissatisfaction in the last few months with our current setup with pushes for splitting things across repositories, switching CI providers, ….. I couldn’t justify making potentially significant improvements into something that might get replaced soon and was hoping to get clarity on that first (sharding tests across machines which @aherrmann-da and I had plans for 4 months ago which we expected to speed up our CI times by at least 2x if not more died a similar death). Now the unfortunate part is that 4 months later after I first got unsure about the future, things seem just as open. Meanwhile we continue to deinvest in our current setup with Andreas working 20% and me stopping work on this without investing in an alternative which I find extremely worrying (but that’s also not my issue to solve at thi spoint).

So was it useful? In the beginning definitely but not sure it fully justified the investment. We probably should have gained larger cross-team agreement on wanting to improve things with our current setup to both justify investments into it and to make sure that things like flakes & slow builds get prioritized across teams.

**Comment by garyverhaegen-da** [comment]
I do want to clarify that my assessment that it should be shut down _now_ does not in any way invalidate the fact that setting it up _back then_ was a good choice.

I agree with all of your explanations. As to the stability of the cluster, I'm not sure what's going on. I have managed a larger ES cluster in the past and it was a lot easier to setup and a lot more stable overall. I've never seen machines just stop the way these do. It was a different version of ES running on AWS rather than GCP, and I have no idea what's the determining factor here.

But at this point in time it doesn't look like the cluster gets used enough to justify digging into the issue.

**Comment by cocreature** [comment]
> I do want to clarify that my assessment that it should be shut down _now_ does not in any way invalidate the fact that setting it up _back then_ was a good choice.

didn’t interpret it that way, just wanted to provide some context for others which may be useful for future investments around this area.

**Review by stefanobaghino-da — APPROVED** [review]
@cocreature Thanks for providing the historical context. The good thing about software is that sometimes it can just exist while it adds value and go away when it doesn't anymore. I agree this had value when it first started. It doesn't right now, so I think it's a good thing to shut this down. If we happen to need it again in the future, we can benefit from the lessons learned in doing this once (e.g. what you said about leaning on a managed service rather then rolling our own cluster).

**Review by ray-roestenburg-da — APPROVED** [review]

**Review by aherrmann-da — APPROVED** [review]
I agree with the description above. It was useful at the time, if no one is using it anymore, then it makes sense to shut it down.

One question this raises: Do we want to maintain the store of build event logs (https://github.com/digital-asset/daml/blob/main/ci/upload-bazel-metrics.yml) and related infrastructure (e.g. https://github.com/digital-asset/daml/pull/10628)?

**Comment by garyverhaegen-da** [comment]
@aherrmann-da Thanks for the pointers! I was fully aware of upload-bazel-metrics but had forgotten about the name shortening.

As far as I'm aware these pieces do not require any maintenance and do not incur much added cost (about ~20s per job IIUC). They also allow us to revert the decision here with no loss of data should we want to.

So my position would be to keep those around at least for a while.

**Comment by garyverhaegen-da** [comment]
Applied.

**Comment by garyverhaegen-da** [comment]
Scary:

```
Apply complete! Resources: 0 added, 0 changed, 39 destroyed.
```

**Pull request merged**
