### PR TITLE
Update scalafmt to 3.0.6

### PR DESCRIPTION
**Pull request by nicu-da**
This will allow us to introduce https://scalameta.org/scalafmt/docs/configuration.html#newlinestoplevelstatementblanklines

CHANGELOG_BEGIN

CHANGELOG_END

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by stefanobaghino-da** [comment]
> > This will allow us to introduce https://scalameta.org/scalafmt/docs/configuration.html#newlinestoplevelstatementblanklines
> 
> Please keep in mind that introducing a new formatting change has the potential to introduce conflicts on _all_ open PRs, potentially causing puzzling moments for the people working on the codebase.
> 
> My advice is to _not_ do this, unless there is a _very_ good reason why we need to adopt this.

If you decide to go for it anyway, please let other contributors know about this and collect their feedback.

**Comment by stefanobaghino-da** [comment]
> The value would be in not wasting time fixing minor code formatting styles through manual review/changes. I would expect that our code style is consistently enforced and does not depend on "magic" settings. Eg: this PR [#11174 (comment)](https://github.com/digital-asset/daml/pull/11174#discussion_r724876488), where there are multiple occurrences where IJ decided to drop the newlines when reformating imports, but scalafmt does not enforce that.

It's a lot of noise, I agree. Is there some way in which we can somehow disable IJ's import rearrangement with a committed config file? This way this would stop automatically for all IJ users on the codebase without any interruption.

**Comment by garyverhaegen-da** [comment]
> Ah ok, was not aware of that. From the wording, it leads me to think that it represents just a normal code change and not some "special" change.

The naming is a bit weird here, but code changes are considered "Routine Changes" whereas changes to production systems (in the case of this repo, mostly making releases and changing the CI infrastructure) are considered "Standard" or "Normal" changes. "Standard" changes are the ones that require following the change management process, including tracking and monthly review; "Routine" changes are the ones for which we can have a more informal process where it's enough for two people to agree (in general, PR opener + 1 reviewer).

Search for "Change Management" on Confluence for details.

**Comment by garyverhaegen-da** [comment]
(They're "Normal" changes to production system as opposed to the third type of change, "Emergency Change", usually done in response to an incident and possibly bypassing the normal review process — but nevertheless tracked for after-the-fact review.)

**Pull request merged**
