### PR TITLE
Switch to correct protobuf repo

### PR DESCRIPTION
**Pull request by cocreature**
changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by SamirTalwar-DA — APPROVED** [review]
Gonna file this one in the "how did this ever work?" bucket.

**Comment by cocreature** [comment]
> Gonna file this one in the "how did this ever work?" bucket.

yeah I’m very confused. Maybe they renamed the repo or something. Having `google/protobuf` be the dart specific stuff also seems very questionable.

**Comment by SamirTalwar-DA** [comment]
GitHub maintains redirections for renamed/moved repositories until the name is re-claimed by something else. So if _google/protobuf_ was moved to _protocolbuffers/protobuf_, and then _recently_ _google/protobuf-dart_ (or whatever) was renamed to _google/protobuf_, it would explain how this worked beforehand.

**Comment by cocreature** [comment]
I’ll just get mad at google, that seems sensible either way.

**Pull request merged**
