### PR TITLE
Removed logging JDBC url to prevent leaking passwords to log files. [DPP-140]

### PR DESCRIPTION
**Pull request by kamil-da**
Removed logging JDBC url to prevent leaking passwords to log files.

CHANGELOG_BEGIN
- not logging JDBC url
CHANGELOG_END

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [x] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by SamirTalwar-DA — APPROVED** [review]
Good call. Makes it a little harder to diagnose some problems but you're right that these could get persisted.

**Review by mziolekda — APPROVED** [review]
LGTM

**Review by fabiotudone-da — APPROVED** [review]

**Pull request merged**
