### PR TITLE
Call ghc `./boot` with `--hadrian`

### PR DESCRIPTION
**Pull request by akrmn**

### CODE REVIEW

**Comment by samuel-williams-da** [comment]
Is there context to this? What does it fix?

**Comment by garyverhaegen-da** [comment]
> Is there context to this? What does it fix?

At some point in our (very long) build logs we get this warning:

```
WARNING: You don't have a mk/build.mk file.

By default a standard GHC build will be done, which uses optimisation
and builds the profiling libraries. This will take a long time, so may
not be what you want if you are developing GHC or the libraries, rather
than simply building it to use it.

For information on creating a mk/build.mk file, please see:
    http://ghc.haskell.org/trac/ghc/wiki/Building/Using#Buildconfiguration
```

This is an attempt to fix that.

**Review by samuel-williams-da — APPROVED** [review]

**Comment by akrmn** [comment]
@garyverhaegen-da thanks for providing the context

@samuel-williams-da, to be clear, I don't think the warning message is right, regardless of the flag we don't do a "standard GHC build". The clue is that `./boot` is called from the (patched) `ghc-lib-gen`, which is used to `gen` `ghc-lib` and `ghc-lib-parser` from the ghc source files,

> Looking at `boot`, theres a validate flag you can use to disable just this warning. The hadrian flag also stops the generation of `ghc.mk` and `GHUmakefile` for each library. I'll approve assuming we're okay with this.

since the next steps use `hadrian` i thought this would be consistent, and indeed CI seems happy about it

**Comment by garyverhaegen-da** [comment]
Also to clarify my position, I'm not saying "please suppress the warning" (though I'm all for removing irrelevant logs); I flagged this warning because it says building GHC with the provided options may be slow and I do indeed get the anecdotal impression from all of the build-watching I tend to do that we spend a lot of time compiling GHC.

I was hoping we may be able to tweak something somewhere to make this faster, especially on Windows. But if we just get a bit less noise in the build process I'll take that too.

**Pull request merged**
