### PR TITLE
Add other node_modules to bazelignore

### PR DESCRIPTION
**Pull request by aherrmann-da**
### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by aherrmann-da** [comment]
> Would that change in light of #4147?

Yes, in that case it's `language-support/ts/packages/node_modules`

**Comment by hurryabit** [comment]
> Yes, in that case it's `language-support/ts/packages/node_modules`

Let's merge this PR after https://github.com/digital-asset/daml/pull/4147 then.

**Comment by hurryabit** [comment]
@aherrmann Local dev workflows might still create `/language-support/ts/node_modules`. Should we hence add this one as well as `/language-support/ts/packages/node_modules`?

**Comment by aherrmann-da** [comment]
> @aherrmann Local dev workflows might still create `/language-support/ts/node_modules`. Should we hence add this one as well as `/language-support/ts/packages/node_modules`?

Yes, that's a good idea.

**Pull request merged**
