### PR TITLE
[BACKPORT] Use bazel-provided gRPC on Unix-like OSs (#12273) (#12194)

### PR DESCRIPTION
**Pull request by akrmn**
We switch back to bazel-provided gRPC as a temporary fix for #12194

This partially reverts commit 0de7b2eae5667d652635628177b1b06edeb61faf (#11031)

changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by cocreature** [comment]
Just to be extra safe, can you check if the repl command works with this for you?

**Review by cocreature — APPROVED** [review]
Thank you!

**Comment by akrmn** [comment]
> check if the repl command works with this for you?

on it

**Comment by akrmn** [comment]
there's no timeout on the repl command!
However, I noticed that `daml-sdk-head` fails on this branch. I'm also not sure why Windows CI failed 🤔

**Comment by cocreature** [comment]
Windows CI looks like it might be an issue with an older gRPC version than we have on `main`? How does `daml-sdk-head` fail?

**Comment by cocreature** [comment]
> Windows CI looks like it might be an issue with an older gRPC version than we have on `main`

hm but I don’t understand why it would have worked before then. We didn’t change the grpc version in this PR :confused:

**Comment by cocreature** [comment]
So apparently the answer is it didn’t work before, https://github.com/digital-asset/daml/pull/12282 fails too. Looking into it.

**Pull request merged**
