### PR TITLE
Batched usage with IGNORE_ROW_ON_DUPKEY_INDEX throws

### PR DESCRIPTION
**Pull request by nmarton-da**
java.lang.ArrayIndexOutOfBoundsException

changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by matthiasS-da** [comment]
Thanks for finding this! Please keep open until we may have received a patch from Oracle.

**Comment by nmarton-da** [comment]
@matthiasS-da do you think we need this still?

**Comment by matthiasS-da** [comment]
We don't need a demo of the problem. We need to make sure we don't have batched usages of IGNORE_ROW_ON_DUPKEY_INDEX.

**Comment by nmarton-da** [comment]
> We don't need a demo of the problem. We need to make sure we don't have batched usages of IGNORE_ROW_ON_DUPKEY_INDEX.

The usage in participant-integration-api is designed so (no batching).
I found 2 more usages:
* Triggers: https://github.com/digital-asset/daml/blob/main/triggers/service/src/main/scala/com/digitalasset/daml/lf/engine/trigger/dao/DbTriggerDao.scala#L331 this seems to me non-batched usage, can you confirm @remyhaemmerle-da ?
* ledger-service: https://github.com/digital-asset/daml/blob/main/ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala#L925 here I am not sure, but the updateMany seems a bit suspicious this regard. @ray-roestenburg-da @S11001001 can you maybe have a look?

**Comment by S11001001** [comment]
Every Oracle insert into the contracts table by JSON API ever has done this; this is not a corner-case code path. If you expect it to throw every time, then there is no problem here. (It's possible that DB library doobie already accounts for the above.)

If it only occurs one-in-a-million times or in weird configurations, some further research may be called for.

**Comment by nmarton-da** [comment]
> Every Oracle insert into the contracts table by JSON API ever has done this; this is not a corner-case code path. If you expect it to throw every time, then there is no problem here. (It's possible that DB library doobie already accounts for the above.)
> 
> If it only occurs one-in-a-million times or in weird configurations, some further research may be called for.

AFAIR the problem got bigger when the transport of the data of the batch grows, also concurrent usage is needed this to be triggered. It might be that you are not encountering it because either the payload is small, and or the batch size is small, or usage is sequential.

**Comment by remyhaemmerle-da** [comment]
> > We don't need a demo of the problem. We need to make sure we don't have batched usages of IGNORE_ROW_ON_DUPKEY_INDEX.
> 
> The usage in participant-integration-api is designed so (no batching). I found 2 more usages:
> 
>     * Triggers: https://github.com/digital-asset/daml/blob/main/triggers/service/src/main/scala/com/digitalasset/daml/lf/engine/trigger/dao/DbTriggerDao.scala#L331 this seems to me non-batched usage, can you confirm @remyhaemmerle-da ?

It does not seems to me neither. @cocreature can you confirm ?

**Comment by matthiasS-da** [comment]
This is my brief summary from back then:
https://github.com/DACH-NY/canton/blob/09ad796730fd239aaaedf5681c24924bd6be3c83/community/common/src/main/scala/com/digitalasset/canton/resource/Storage.scala#L727

```
// Bail out if the statement contains IGNORE_ROW_ON_DUPKEY_INDEX, because update counts are known to be broken.
    // Use MERGE instead.
    // Ignoring update counts is not an option, because the JDBC driver reads them internally and may fail with
    // low-level exceptions.
    // See UpsertTestOracle for details.
```

Even if it currently works within your tests, it may throw if you change the payload size and / or batch size. Therefore my recommendation is to not use `IGNORE_ROW_ON_DUPKEY_INDEX` within batched db commands.

@stephencompall-DA

**Comment by cocreature** [comment]
There shouldn't be any batching here in the trigger service.

**Pull request closed without merging**
