### PR TITLE
Correct number of steps for creating new feature

### PR DESCRIPTION
**Pull request by wallacekelly-da**
I don't know if there are three steps or four steps involved in implementing the feature. However, there are only three *listed*.

CHANGELOG_BEGIN
CHANGELOG_END

### CODE REVIEW

**Review by carrielaben-da — APPROVED** [review]
LGTM

**Review by stefanobaghino-da — APPROVED** [review]

**Comment by stefanobaghino-da** [comment]
@wallacekelly-da https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md#pull-request-checklist I'll do the changelog entry step for you this time.

**Comment by stefanobaghino-da** [comment]
> @wallacekelly-da https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md#pull-request-checklist I'll do the changelog entry step for you this time.

Unfortunately I cannot actually do this since this is coming from your own fork. Please add the changelog entry commit as required. After that, all checks will pass.

**Comment by carrielaben-da** [comment]
> @stefanobaghino-da Thank you for pointing me to the PR checklist and specifically the change log requirement. I added an empty change log section. I would be happy to add a change log message, if you think it would be helpful. However...
> 
> * One of the requirements for the change log is, "the first term to appear should be the affected component" The [list of components](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md#list-of-components-for-changelog-entries) does not include "Daml Docs" or something like that. Any recommendations?

We generally use empty change log entries for all documentation issues; keeps it simple.

**Pull request merged**
