### PR TITLE
Expunge Ledger API NPM package

### PR DESCRIPTION
**Pull request by stefanobaghino-da**
These files were used to publish the `.proto` files on NPM so that the
dependency could be defined in the Node.js bindings package manifest.
These files are not longer used and can be safely removed from this
repository.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/docs/source/support/release-notes.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by stefanobaghino-da** [comment]
_EXPUNGE!_

**Comment by gerolf-da** [comment]
image

**Comment by stefanobaghino-da** [comment]
Paging in @moritzkiefer-da for this [very important message.](https://github.com/digital-asset/daml/pull/1394#issuecomment-496136639)

**Comment by cocreature** [comment]
:+1:

**Pull request merged**
