### PR TITLE
[release] 2.8.5

### PR DESCRIPTION
**Pull request by yves-da**

### CODE REVIEW

**Review by remyhaemmerle-da — APPROVED** [review]

**Comment by yves-da** [comment]
Forced a restart of the build:
* macos ran for more than 1 hour while a normal build should take around 24 minutes
* windows also should take like 24 minutes but ran for at least 40 minutes

**Comment by yves-da** [comment]
Forced another restart because windows ran for 30 minutes +

This is just the PR to trigger the release build from `main` once it is merged. Afterwards the another release build will be kicked off.

Don't see any reason to wait for this PR any longer than needed.

**Pull request merged**
