### PR TITLE
Adding Daml Script to the "create-daml-app" template

### PR DESCRIPTION
**Pull request by nemanja-da**
CHANGELOG_BEGIN
Added Daml Script to the "create-daml-app" template. This template is used a lot at daml.com/learn and we're switching to using Daml Script over scenarios in general
CHANGELOG_END

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by cocreature — CHANGES_REQUESTED** [review]
This is just an unused import and an unused dependency. If you want to add the import and the dependency, we should have a script in the file.

**Comment by garyverhaegen-da** [comment]
Do we still want this? There is no scenario currently in create-daml-app, so nothing to port, but  could see an argument for providing an example Script in this template.

Adding the script itself would be easy enough, but I'm not sure that'd be enough. We may want to update the documentation to mention it, and update the build to actually run those scripts. It's not a huge amount of work but it's not entirely trivial either.

**Comment by cocreature** [comment]
[#12089](https://github.com/digital-asset/daml/pull/12089) will add it anyway so I’ll close this.

**Pull request closed without merging**
