### PR TITLE
Sequential log entry ID for InMemoryLedgerReaderWriter

### PR DESCRIPTION
**Pull request by miklos-da**
Summary of changes:
* Switched to using a sequential ID to generate the next log entry ID instead of using a random set of bytes.
* Code tidying:
  * Moved LedgerRecord into its own file.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by SamirTalwar** [comment]
I'd love it if we could move this behavior into a class (`SequentialEntryId`?) that other implementations can use.

**Comment by miklos-da** [comment]
> I'd love it if we could move this behavior into a class (`SequentialEntryId`?) that other implementations can use.

Moved logic into a separate class to allow reuse.

**Comment by stefanobaghino-da** [comment]
I'm not sure of what's going on here but it looks like even fixing what I suggested seems to result in a broken change log... :thinking: 

Was the reported change log actually wanted?

Due to a merge a commit from `master` is part of the timeline and someone else seems to have put `CHANGELOG_BEGIN` in the commit message title, resulting in a squashed `* CHANGELOG_BEGIN`. Could this affect the outcome? /cc @garyverhaegen-da

**Comment by stefanobaghino-da** [comment]
Probably I'm just getting confused because of the merges.

I'll remove the blocker for now but I would suggest you favor rebasing over merging to make sure your PRs have a clear and understandable set of change log entries.

**Comment by miklos-da** [comment]
> Probably I'm just getting confused because of the merges.
> 
> I'll remove the blocker for now but I would suggest you favor rebasing over merging to make sure your PRs have a clear and understandable set of change log entries.

Committed a changelog message that properly opens & closes.

**Pull request merged**
