### PR TITLE
Docs style alignment

### PR DESCRIPTION
**Pull request by bame-da**
This PR moves the docs styling closer to the colors and fonts of digitalasset.com and generally makes the theme much lighter.
Outside of the docs theme, there are only minor changes:

1. I removed all redundant local contents on docs pages as these don't render well and induce non-working backlinks from titles
2. I aligned the Sphinx versions in dev-env and Bazel so I could include the `copy_button` extension in the preview
3. I removed one or two indentations in the docs which caused code to be rendered oddly

The changes in this PR are deployed at http://docs-daml-com-staging.s3-website-us-east-1.amazonaws.com/ so the rendered result can be viewed and tested there.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by garyverhaegen-da — APPROVED** [review]
I'm not a big fan of the color chosen for buttons & inline code snippets, or the background color on active links (while being clicked). But overall I don't think my opinion should hold much weight when it comes to graphics so 🤷 .

**Comment by bame-da** [comment]
> the background color on active links (while being clicked)

Do you mean that the background goes blue in the menu? That's actually not very nice, I'll just remove that effect.

**Review by stefanobaghino-da — APPROVED** [review]
> Do you mean that the background goes blue in the menu? That's actually not very nice, I'll just remove that effect.

Seconded. 🙇🏻 

---

Looks good thanks!

**Comment by bame-da** [comment]
thanks both, the effect is now gone on staging. The turquoise button and code colour is part of the DA palette. I think it looks pretty decent as well, but it is quite bright so I can understand why it's not to everyone's liking. I'll leave it like that for now, though.

**Pull request merged**
