### PR TITLE
eliminating some mutable state

### PR DESCRIPTION
**Pull request by gaboraranyossy-da**
- eliminates a lot of confusing mutable state in the top level of the Sandbox.  There is still plenty of potential for improvement, but I believe this PR is a considerable improvement.
- addresses some ownership related life-cycle management concerns.
- various cleanups

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/docs/source/support/release-notes.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by gleber-da** [comment]
This PR dropped `ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/SandboxApplication.scala`, but this file is still referred by 
```
$ ag SandboxApplication

language-support/scala/examples/codegen-sbt-example/sandbox-example/src/main/scala/com/digitalasset/example/ExampleMain.scala
34:import com.digitalasset.platform.sandbox.SandboxApplication
35:import com.digitalasset.platform.sandbox.SandboxApplication.SandboxServer
58:  private val server: SandboxServer = SandboxApplication(serverConfig)
```

**Comment by gaboraranyossy-da** [comment]
Thanks @gleber-da  I have two questions related to this:

**Comment by gaboraranyossy-da** [comment]
tagging @leo-da as the assumed owner of that file

**Comment by leo-da** [comment]
> Thanks @gleber-da I have two questions related to this:
> 
> * why is this code not compiled?
> * why are we using internals of the Sandbox outside, especially in code examples?

it was compiled with SBT, it used to build against the released/published binaries... building it as part of bazel won't work... I mentioned multiple times instructions how to validate the release... but I guess they were ignored
Did not know that the example was using an internal class... if it is internal -- hide it, don't publish it, so I cannot access it from the published jars.

**Comment by gaboraranyossy-da** [comment]
@leo-da Ok, do we still need that example? I think it is ok to use the SandboxServer for internal testing, but we should not advertise it in examples as it is not meant to be public. If that is the intention, we should introduce a stable API for doing that.

**Comment by leo-da** [comment]
I need this example as a test that all released artifacts work with Scala codegen. Plus it demonstrates to the end user how to write self-contained tests, that bring up sandbox internally.

**Comment by leo-da** [comment]
BTW we removed sandbox-control... and the recommended way of testing against sandbox now is start sandbox directly from your integration test... If this is not true anymore, we need to revive sandbox control :)

**Comment by leo-da** [comment]
@gaboraranyossy-da I remove the usage of the `SandboxApplication`... see the above PR.

**Comment by gaboraranyossy-da** [comment]
thanks @leo-da

**Pull request merged**
