### PR TITLE
daml-react: allow for React 17

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
See #11358.

```
CHANGELOG_BEGIN

- [@daml/react] Our React bindings now request the `react` library as a
  peer dependency, and will accept React 17 in addition to the current
  React 16.

CHANGELOG_END
```

### CODE REVIEW

**Comment by garyverhaegen-da** [comment]
Changed to bump React in `create-daml-app`. Note that while I believe this all _should_ work, I don't know how to actually test this without pushing to npm.

**Comment by garyverhaegen-da** [comment]
(Beyond the CI tests, which we might decide are good enough.)

**Comment by cocreature** [comment]
> (Beyond the CI tests, which we might decide are good enough.)

they’re fairly thorough so I have _some_ trust in them here.

**Comment by stefanobaghino-da** [comment]
Does this fix #11358?

**Comment by cocreature** [comment]
We have a new snapshot and testing passed so https://github.com/digital-asset/daml/issues/11358#issuecomment-956354428 should be addressed now.

**Comment by stefanobaghino-da** [comment]
> We have a new snapshot and testing passed so [#11358 (comment)](https://github.com/digital-asset/daml/issues/11358#issuecomment-956354428) should be addressed now.

Cool, thanks!

**Pull request merged**
