### PR TITLE
Document ResultNeedUpgradeVerification use cases

### PR DESCRIPTION
**Pull request by simonmaxen-da**

### CODE REVIEW

**Review by andreaslochbihler-da — APPROVED** [review]
Works for me for now. Just a side question: On the submission path, we will still validate that the declared stakeholders / signatories / ... of explicitly disclosed contracts are correct by doing the contract id authentication check after interpretation, don't we?

**Comment by simonmaxen-da** [comment]
> On the submission path, we will still validate that the declared stakeholders / signatories 
Yes: 
CantonSyncService.submitTransaction 
-> DomainRouter.submitTransaction 
-> SerializableContractAuthenticator.authenticate

**Comment by simonmaxen-da** [comment]
And all (`UsedAndCreatedContracts.used`) input contracts are checked during request processing.

**Review by nickchapman-da — APPROVED** [review]
This is fine.
Being modal is a bit hacky, but at least we avoid changing the interface.
:+1:

**Pull request merged**
