### PR TITLE
kvutils: Buffer (im/ex)port streams, and simplify reading a fixed-length ByteString.

### PR DESCRIPTION
**Pull request by SamirTalwar-DA**
Little attempts to make export and import a little faster.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by stefanobaghino-da — APPROVED** [review]
LGTM.

Probably silly question though: why would the buffering make those operations faster?

**Comment by SamirTalwar-DA** [comment]
Buffered input and output streams make sure we read and write in large chunks by storing a queue of data in memory. This should mean fewer trips to the disk in the case of file access.

This isn't really the bottleneck when it comes to integrity checking, but I thought I'd take care of it on the way.

**Comment by leo-da** [comment]
@SamirTalwar-DA  did you capture any metrics before and after the change?

One more thing to keep in mind:
```
private static int DEFAULT_BUFFER_SIZE = 8192;
```
might be too big or too small depending on the file size. I would set it manually to: `Math.min(default, file.size)`. In any case, I don't know much about this logic. Feel free to disregard my comment.

**Comment by SamirTalwar-DA** [comment]
I ran the integrity checks with the ledger API test tool export before and after, and saw somewhere between an 0% and 10% improvement. So I'm not really sure if it's done anything, but it definitely didn't hurt.

The smallest file size we care about is around 5 MB, so the buffer is probably fine. 🙂

**Pull request merged**
