### PR TITLE
replace DAML Authors with DA in copyright headers

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
Change requested by Manoj.

### CODE REVIEW

**Comment by garyverhaegen-da** [comment]
Built on top of #5227; ideally should be merged afterwards.

**Comment by garyverhaegen-da** [comment]
> I thought we use DAML authors explicitly because our CLA does not give DA the copyright for external contributions? Am I missing something here?

Yes, that is the reasoning under which we changed it back in August last year (#2499). But now Manoj has asked me to change it back, so I comply. As I stated then, copyright law is way above my head so I do as I'm told. I guess I can extend the apology he gave me for the back-and-forth to the rest of the team. 🤷‍♂

**Comment by S11001001** [comment]
> I thought we use DAML authors explicitly because our CLA does not give DA the copyright for external contributions? Am I missing something here?

You aren't missing anything. The CLA does not assign copyright to DA.

**Comment by garyverhaegen-da** [comment]
@shaul-da any objection to this?

**Comment by garyverhaegen-da** [comment]
As this is a bit time-sensitive (not on the legal side, but this PR is very sensitive to race conditions) I'll go ahead and merge for now. I have raised the concern of external contributions with Manoj, and he's heard it, and he's confirmed that external contributors do not indeed assign copyright to us and retain ownership of their contributions, but despite that it is still his expert opinion that this is the appropriate header.

He tried to explain it to me. I think it is something about contributors owning their contribution, but not the whole piece of work that contains their contribution. For anyone interested in digging further, he shared [this link](https://google.github.io/opencasebook/authorship/). Me, I'm going to just trust him.

@shaul-da should you have any objection to this, I'm happy to reverse (or change to a third option) once you've worked it out with Manoj.

**Comment by garyverhaegen-da** [comment]
Successfully applied Terraform which, as expected, updated the Linux CI nodes. I did double-check that the only change was to the copyright header of the init script (infra/vsts_agent_linux_startup.sh).

**Pull request merged**
