### PR TITLE
Update rules_scala

### PR DESCRIPTION
**Pull request by aherrmann-da**
Two patches have since been upstreamed and can be removed.

changelog_begin
changelog_end

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by cocreature — APPROVED** [review]
Deleted code is the best code

**Comment by cocreature** [comment]
CI failures look legit. Something seems to have changed around jmh.

**Comment by SamirTalwar-DA** [comment]
Rather than fixing the JMH issues, you may just want to remove _sandbox-perf_; we'll probably delete it in a month or two anyway.

**Comment by cocreature** [comment]
> Rather than fixing the JMH issues, you may just want to remove _sandbox-perf_

it’s not the only jmh test and I really want to keep some of the other ones for speedy and also for the JSON API



> we'll probably delete it in a month or two anyway.

sandbox(classic) will never die

**Comment by SamirTalwar-DA** [comment]
Fair enough. I think that _sandbox-perf_ tests Sadbonx though.

**Pull request merged**
