### PR TITLE
ledger-api-test-tool: Port LotsOfPartiesIT.

### PR DESCRIPTION
**Pull request by SamirTalwar**
Port `LotsOfPartiesIT` to the Ledger API test tool.

Because this test is fairly intensive, running it in parallel with all other tests makes them time out. Until we have a smarter solution, I've changed it to run as separate Bazel tasks. On the sandbox, these are `//ledger/sandbox:conformance-test-lots-of-parties-*`, and there's a similar set for the DAML-on-X reference server.

In the interest of factoring out duplication, I've pulled out a Bazel function, `server_conformance_test`, which declares multiple conformance tests. In doing so, I changed some names:

- `//ledger/sandbox/conformance-test` →
  `//ledger/sandbox/conformance-test-memory`
- `//ledger/api-server-damlonx/reference-v2/conformance-test` →
  `//ledger/api-server-damlonx/reference-v2/conformance-test-postgres`

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/unreleased.rst), if appropriate
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by SamirTalwar** [comment]
/azp run

One more time!

**Comment by stefanobaghino-da** [comment]
/azp run
# source

**Pull request merged**
