### PR TITLE
Generate `Eq` instances for interfaces

### PR DESCRIPTION
**Pull request by akrmn**
DA-GHC PR: https://github.com/digital-asset/ghc/pull/102

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by cocreature — COMMENTED** [review]
I think I’m slightly confused here. I thought we agreed that we’ll solve https://github.com/digital-asset/daml/issues/12196 at an LF level rather than hacking around in user-land by comparing type reps. Am I misremembering? (I realize we should have written this out, sorry about that).

If I’m not misremembering, we can still solve it in 2 steps and first merge this for the GHC changes, add the LF primitive and then drop the typerep comparison.

**Comment by akrmn** [comment]
> I thought we agreed that we’ll solve https://github.com/digital-asset/daml/issues/12196 at an LF level

I'm sorry, I don't remember that discussion. I went with your comment on #12196,

> The other option is to ignore this and only have sensible equality in Daml:
>
> ```
> instance Eq I where
>  x == y = interfaceTypeRep x == interfaceTypeRep y && GHC.Types.primitive @"BEEqual" x y
> ```

which is pretty much what I generate here.

**Comment by akrmn** [comment]
yeah that sounds good, again sorry I forgot the discussion around `Any`

**Review by cocreature — APPROVED** [review]
Thanks!

**Pull request merged**
