### PR TITLE
Release SDK v2.0.0-snapshot.20220110.8812.0.3a08380b

### PR DESCRIPTION
**Pull request by kamil-da**
CHANGELOG_BEGIN
CHANGELOG_END

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by cocreature — APPROVED** [review]

**Comment by kamil-da** [comment]
Opening a release PR again due to technical problems - sorry for the noise!

**Comment by kamil-da** [comment]
Manual tests passed on macOS.

**Comment by mziolekda** [comment]
Manual tests passed on Windows.

**Comment by mziolekda** [comment]
Test procedures need updating. Following discrepancies observed:

- One needs to login as alice/bob instead of Alice/Bob
- One needs to follow palice/pbob intead of Alice/Bob
- The line to modify in quickstart project to verify that studio shows editor errors is 14 instead of 25

**Comment by cocreature** [comment]
> Test procedures need updating. Following discrepancies observed:

thanks we’re on it.

**Pull request merged**
