### PR TITLE
Install the Windows SDK on CI nodes

### PR DESCRIPTION
**Pull request by cocreature**
This provides signtool.exe which we need to sign our Windows installer.

I don’t have any permissions to test or apply the terraform changes but I tried this out on my local Windows machine and it seems to work. It is somewhat annoying that we have to get this via chocolatey instead of via scoop (and thereby via dev-env) but the Windows SDK is not available via scoop.

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/docs/source/support/release-notes.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by neil-da** [comment]
@majcherm-da any chance of making the Windows SDK available via chocolatey? Any idea where/how we can request that?

**Comment by cocreature** [comment]
@neil-da Did you mean Scoop? We already include scoop manifests in our repo so we could try to add a manifest for the Windows SDK but I have no clue what assumptions scoops makes about installers (afaik it tries to install in custom locations). Given that contrary to other tools in dev-env this is not something that we want developers to run themselves, I don’t think it makes sense to spend effort on using scoop instead of chocolatey for this.

**Comment by majcherm-da** [comment]
@cocreature We could get almost anything via dev-env (scoop) - it's just a matter of making binaries available somewhere and writting a manifest file for scoop with an install script

@neil-da I could take a look at `choco` - I guess it almost the same - it shouldn't be that hard.

Do we need it for CI / DAML team only or end users as well and make it available for people having just scoop/choco installed (without dev-env)?

**Comment by cocreature** [comment]
The Windows SDK is a pretty large download so even if we get it via scoop we probably don’t want to install it by default given  that developers don’t have the signing certificate so this isn’t very useful.

**Comment by majcherm-da** [comment]
@cocreature ah.. sorry I just read comments - it's Windows SDK, not DAML SDK for Windows ;) If it's available via `choco` it could be ported to `scoop` without major problems I guess. See `tools\chocolateyInstall.ps` under Files on: https://chocolatey.org/packages/windows-sdk-10.0

**Comment by neil-da** [comment]
I leave it to you two as to whether the effort is worth it. Given its not a general dev tool sounds like it probably isn't worth it?

**Comment by cocreature** [comment]
I’d say unless we want to get rid of Chocolatey completely (we already use it for installing git at the moment), there is little reason to switch this over to scoop (but if someone wants to do it, I’m also not opposed to it).

**Comment by majcherm-da** [comment]
The only benefit of having it in scoop (or rather dev-env) is the ability to put it into `.dadew`, which will ensure it's available on dev boxes / for bazel builds. If we would like to create the installer from bazel for example (or on dev machines / outside of CI in general, easily) it would make sense to put it there, but if you'd like to keep it on CI only it's ok to have it as is I'd say.

**Comment by cocreature** [comment]
Applied by @majcherm-da and I verified that signtool is now present.

**Pull request merged**
