### PR TITLE
Remove unnecessary comment from Helm Chart docs

### PR DESCRIPTION
**Pull request by stefanobaghino-da**
Apart from being unnecessary, it also got rendered on the docs.

changelog_begin
changelog_end

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by cocreature — APPROVED** [review]

**Review by ray-roestenburg-da — APPROVED** [review]

**Review by victormueller-da — APPROVED** [review]

**Comment by garyverhaegen-da** [comment]
> Apart from being unnecessary, it also got rendered on the docs.

I strongly disagree that it's unnecessary to point out when something needs to be kept in sync with another repo. I would have vastly preferred if you'd fixed the markup instead. 🤷‍♂️

**Comment by ray-roestenburg-da** [comment]
Does restructured text have author mode comments that don't get rendered? asciidocs has something like that.

**Comment by cocreature** [comment]
Yes
```
.. comment
```

**Comment by ray-roestenburg-da** [comment]
Ah lol so that was the intention here already, though looks like the formatting somehow was wrong, if it got rendered in the docs?

**Comment by garyverhaegen-da** [comment]
I think the comment should have been indented 3 spaces instead of 2, but I'm (clearly) no RST expert.

**Comment by stefanobaghino-da** [comment]
> I strongly disagree that it's unnecessary to point out when something needs to be kept in sync with another repo. I would have vastly preferred if you'd fixed the markup instead. man_shrugging

Thanks for bringing that up, I restore it [here](https://github.com/digital-asset/daml/pull/12862) changing the wording a bit.

**Pull request merged**
