### PR TITLE
WIP: Switch to GHC 8.10.2

### PR DESCRIPTION
**Pull request by cocreature**
changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by cocreature** [comment]
Guess what, the problem is Windows https://gitlab.haskell.org/ghc/ghc/issues/17575 I don’t really see an easy way around this. It looks like `runhaskell` is just completely broken and that’s what `rules_haskell` uses for cabal packages to run `Setup.hs`. So we’ll have to wait for `8.8.3`. cc @aherrmann-da

**Comment by aherrmann-da** [comment]
We've seen some issues with profiling and coverage with GHC 8.8 in rules_haskell, see https://github.com/tweag/rules_haskell/issues/1323 and https://github.com/tweag/rules_haskell/issues/1324. We're not using coverage here, but testing profiling might be a good idea.

**Comment by cocreature** [comment]
Last I checked profiling in the DAML repo was broken anyway probably due to the switch to `haskell_cabal_library`.

**Comment by cocreature** [comment]
Undrafting since Azure stopped running draft PRs and I’m tired of `/azp run`ning.

**Comment by cocreature** [comment]
Broken by https://gitlab.haskell.org/ghc/ghc/-/issues/18550 on Windows and it fails to even build GHC on other platforms

https://i.imgflip.com/4b3b25.jpg

**Comment by cocreature** [comment]
stop trying to make

**Pull request closed without merging**
