### PR TITLE
ledger-on-sql: Remove conformance tests for H2 and SQLite files.

### PR DESCRIPTION
**Pull request by SamirTalwar-DA**
We don't use these in any kind of production setting, and it reduces the CI overhead a lot.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by cocreature — APPROVED** [review]
looks sensible, can we just stop supporting them completely and error out?

**Comment by SamirTalwar-DA** [comment]
@cocreature: Not really, unless we want to parse JDBC URLs to a much greater degree.

**Review by fabiotudone-da — COMMENTED** [review]
I think that, if we support something, we should test it; thus, I agree with @moritzkiefer-da that we should remove H2 and SQLite support altogether, and actually I think doing so should really be inseparable from the removal of the tests (else everything should stay as it is).

**Comment by SamirTalwar-DA** [comment]
Well, we can't remove support altogether; we still need to support them for the in-memory version of Sandbox.

**Comment by fabiotudone-da** [comment]
> @cocreature: Not really, unless we want to parse JDBC URLs to a much greater degree.

Can't we e.g. whitelist on the connection class?

**Comment by fabiotudone-da** [comment]
> Well, we can't remove support altogether; we still need to support them for the in-memory version of Sandbox.

Both of them? Then I am actually not OK with removing the tests.

**Comment by cocreature** [comment]
I think we need to clarify this a bit:
We use h2 an sqlite in in-memory mode (not sure why we need both :shrug:). We don’t use the file mode anywhere.

**Comment by SamirTalwar-DA** [comment]
Yes, there are still tests for the in-memory modes.

I think we can probably drop support for H2 altogether, but I need to look into it more.

**Comment by cocreature** [comment]
> I think we can probably drop support for H2 altogether, but I need to look into it more.

No, Canton uses this in their tests atm.

**Comment by fabiotudone-da** [comment]
> (not sure why we need both)

> I think we can probably drop support for H2 altogether, but I need to look into it more.

Well that's perhaps another great PR.

> We don’t use the file mode anywhere

I see, thanks, then I am OK with this. I agree it would be better to error out on what we don't support.

**Review by fabiotudone-da — APPROVED** [review]

**Review by hubert-da — APPROVED** [review]

**Review by miklos-da — APPROVED** [review]

**Pull request merged**
