### PR TITLE
WIP: Bazel 0.25

### PR DESCRIPTION
**Pull request by aherrmann-da**
- Update to Bazel 0.25 RC2
- Enable minimal downloads from remote cache. I.e. don't download unnecessary intermediate build products.

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/docs/source/support/release-notes.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by moritzkiefer-da** [comment]
Nice! Let me know if you have any results for how much this helps. I think this also brings asynchronous fetching from the cache so even if we download the full artifacts it should probably help.

**Comment by aherrmann-da** [comment]
@cocreature I've gotten Bazel 0.25.2 working on Linux. Sadly the numbers are not looking good.
`time bazel build damlc` on empty disk-cache and populated remote cache yields
- 6m38.570s on Bazel 0.25.2
- 5m57.573s on Bazel 0.24.0

The disk cache was still enabled in these cases, but I don't think that should interfere with this test. In any case it matches our use-case.

**Comment by cocreature** [comment]
@aherrmann-da Those numbers are with the new experimental cache downloads or has Bazel just gotten slower overall?

**Comment by aherrmann-da** [comment]
@cocreature I made a mistake in `.bazelrc` so these numbers are just the regular downloads without the builds without bytes. So, there's indeed a regression for regular downloads.

However, with the builds without bytes flags the results are much better. Down to 2m18.042s on Bazel 0.25.2

**Comment by cocreature** [comment]
Nice!

**Comment by aherrmann-da** [comment]
Closing in favor of #1957

**Pull request closed without merging**
