### PR TITLE
move ledger-api-test-tool out of ledger

### PR DESCRIPTION
**Pull request by mziolekda**

### CODE REVIEW

**Comment by remyhaemmerle-da** [comment]
Cannot we let it (unmaintained) until we move the language part ? 
We just remove it from the release.

**Comment by mziolekda** [comment]
@remyhaemmerle-da We are moving the tool out, because it is not practical to make it build in canton without having the daml-lf stuff ported. Whether you want to let it unmaintained is orthogonal to this move. Whether we maintain it or not will be dictated solely on the fact whether a necessity arises or not.

**Comment by remyhaemmerle-da** [comment]
> We are moving the tool out, because it is not practical to make it build in canton without having the daml-lf stuff ported.
I understood that. I was in fact meaning can we fork it, and keep a unmaintained copy in the daml repo until we move the language part. I will make sure we do not release it anymore form the daml repo. 

> Whether you want to let it unmaintained is orthogonal to this move.
I would like to keep in the daml repo to have the conformance running in the CI

**Review by remyhaemmerle-da — APPROVED** [review]
LGTM.

**Comment by remyhaemmerle-da** [comment]
I though the test-tool was moving out of the repo.

**Pull request merged**
