### PR TITLE
Release 1.8.0-snapshot.20201214.5841.0.a8ae8e4a. [KVL-773]

### PR DESCRIPTION
**Pull request by SamirTalwar-DA**
This is not intended for general consumption.

See #8286 for details.

### Changelog

- **[Integration Kit]** Reverted a fix to the kvutils input state that caused performance degradation on some ledgers. This is a temporary measure that we do not expect to be used outside of very specific circumstances, as it can trade correctness for performance if the semantics are not completely understood.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [x] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by gerolf-da** [comment]
@moritzkiefer-da: should this be merged into the `release/1.8.x-experiment` branch?

**Comment by cocreature** [comment]
No, we only change `LATEST` on master. The commit you reference can then be from a different branch.

**Review by gerolf-da — APPROVED** [review]

**Comment by SamirTalwar-DA** [comment]
Manual tests passed on Linux.

**Comment by SamirTalwar-DA** [comment]
Manual tests passed on Windows.

**Pull request merged**
