### PR TITLE
Delete "testing with scenarios" section

### LINKED ISSUE #8839: "Testing Using Scenarios" should be updated to "Scripts"
Since scenarios are no longer recommended I think this section should be updated. Also for most new developers given the location of this section I imagine they'd be much more likely to come across this section than the "Daml Script" section further down and with a less descriptive name.

https://docs.daml.com/daml/testing-scenarios.html

### PR DESCRIPTION
**Pull request by cocreature**
This is superseded by
https://docs.daml.com/daml/intro/2_DamlScript.html which seems much
nicer and I don’t see what we gain by having both.

fixes #8839

changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by sofiafaro-da — APPROVED** [review]
Thank you!

**Review by bame-da — APPROVED** [review]
I'd suggest we expand this into a "deprecate Scenarios" PR, but if you want to do the two separately, you also have my blessing for that.

**Comment by bame-da** [comment]
Oh, my comment raced with your Squash & Merge. nvm.

**Comment by cocreature** [comment]
> I'd suggest we expand this into a "deprecate Scenarios" PR, but if you want to do the two separately, you also have my blessing for that.

Will take care of that.

**Pull request merged**
