### PR TITLE
Docs style alignment

### PR DESCRIPTION
**Pull request by bame-da**
What I hope to be the last PR in the series improving the docs styling.

- New icons and styling on the landing page
- Pixel alignment of the right arrow of the active menu item

Preview live on http://docs-daml-com-staging.s3-website-us-east-1.amazonaws.com/

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by nemanja-da** [comment]
Looks really big on MacBook Pro's 13'' screen

image

**Comment by gerolf-da** [comment]
the menu on the left is quite wide and uses lots of screen real estate. is that intentional? (MacBook 13", firefox)
image

**Comment by bame-da** [comment]
@nemanja-da Pushed version with better spacing to staging.

@gerolf-da Yes, because once you open them up, titles get much wider. I could go down to 400px, but the 20px make little difference.

**Review by nemanja-da — APPROVED** [review]
tyvm!

**Pull request merged**
