### PR TITLE
Fix Jackson transitive version clash

### PR DESCRIPTION
**Pull request by stefanobaghino-da**
We're currently depending on `com.auth0:java-jwt:3.8.1` and `com.auth0:jwks-rsa:0.9.0`, with the two clashing over the Jackson dependencies. This PR upgrades to `com.auth0:java-jwt:3.8.3`, which shares the same dependencies as `com.auth0:jwks-rsa:0.9.0`.

- [`com.auth0:java-jwt:3.8.1` on mvnrepository.com](https://mvnrepository.com/artifact/com.auth0/java-jwt/3.8.1)
- [`com.auth0:java-jwt:3.8.3` on mvnrepository.com](https://mvnrepository.com/artifact/com.auth0/java-jwt/3.8.3)
- [`com.auth0:jwks-rsa:0.9.0` on mvnrepository.com](https://mvnrepository.com/artifact/com.auth0/jwks-rsa/0.9.0)

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags, if appropriate
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by dasormeter** [comment]
hiya @stefanobaghino-da this actually doesn't fix the problem for external apps using SBT to consume SDK and its transitive dependencies, because we still go to maven central to get the transitives, and they still have the bad jackson transitive.  This PR will make sure that the SDK tarball has the expected jackson dependency, but the problem i believe is that the auth0 published artifact has a bad transitive

**Comment by stefanobaghino-da** [comment]
@dasormeter Not sure of what you mean, as stated in the description

> This PR upgrades to com.auth0:java-jwt:3.8.3, which shares the same dependencies as com.auth0:jwks-rsa:0.9.0.

That same dependency is `com.fasterxml.jackson.core/jackson-databind/2.10.0.pr3` as reported in the links I added to the description.

Am I missing something?

**Comment by stefanobaghino-da** [comment]
@miklos-da Your comment has been addressed by https://github.com/digital-asset/daml/pull/3769#pullrequestreview-328288276.

**Comment by dasormeter** [comment]
> @dasormeter Not sure of what you mean, as stated in the description
> 
> > This PR upgrades to com.auth0:java-jwt:3.8.3, which shares the same dependencies as com.auth0:jwks-rsa:0.9.0.
> 
> That same dependency is `com.fasterxml.jackson.core/jackson-databind/2.10.0.pr3` as reported in the links I added to the description.
> 
> Am I missing something?

Yeah this is a tricky one, but it basically is not a Bazel / DAML repo problem but rather a transitive problem with the artifact we are pulling from maven central and the transitive dependencies it has in its maven central published pom.   Us forcing a particular version in our DAML artifacts helps our packaging and makes the SDK tarball coherent, but it doesn't help an app consuming our artifacts and the things we depend on from maven central, which is what we do for SBT apps that are our ledger integrations.

We need to find a version of this external lib that has a transitive dependency on a fully fledged version of jackson rather than the pr3 pre-release,, i believe.

**Comment by dasormeter** [comment]
> @dasormeter Not sure of what you mean, as stated in the description
> 
> > This PR upgrades to com.auth0:java-jwt:3.8.3, which shares the same dependencies as com.auth0:jwks-rsa:0.9.0.
> 
> That same dependency is `com.fasterxml.jackson.core/jackson-databind/2.10.0.pr3` as reported in the links I added to the description.
> 
> Am I missing something?

Also I think .10.0.pr3.jar may be a poisoned version as published on maven central given the ivy invalid artifact warnings as well.  So I don't think that is a version we want to actually rely upon

**Comment by dasormeter** [comment]
@stefanobaghino-da i tested locally and by using version 3.8.2 of java-jwt and version 0.8.3 of jwks-rsa this does resolve this issue as they agree on a properly released version of jackson transitive

``ledger/ledger-api-auth_2.12/100.0.0/ledger-api-auth_2.12-100.0.0.pom
40:      <groupId>com.auth0</groupId>
41-      <artifactId>java-jwt</artifactId>
42-      <version>3.8.2</version>

ledger-service/jwt_2.12/100.0.0/jwt_2.12-100.0.0.pom
48:      <groupId>com.auth0</groupId>
49-      <artifactId>java-jwt</artifactId>
50-      <version>3.8.2</version>
--
56:      <groupId>com.auth0</groupId>
57-      <artifactId>jwks-rsa</artifactId>
58-      <version>0.8.3</version>```

**Comment by dasormeter** [comment]
however when i test with this PR (build a local full SDK build cherrypicking these commits) it still does not resolve the problem

so i think going back to java-jwt 3.8.2 and jwks-rsa 0.8.3 is preferable as that puts you with jackson 2.9.9.3, which seems to be a good one

**Comment by dasormeter** [comment]
alternate take PR -- https://github.com/digital-asset/daml/pull/3775

that one looks to work when i build a local version and consume it from an sbt project

**Comment by stefanobaghino-da** [comment]
Closing in favor of #3775

**Pull request closed without merging**
