### PR TITLE
Parallelize daml-assistant integration tests.

### PR DESCRIPTION
**Pull request by sofiafaro-da**
This mainly involves avoiding changing the working directory or the environment while inside tests.

AFAIK the daml start tests can't be parallelized without starting up a sandbox instance each time, which seems bad. These tests could be separated from the rest...

The magic number "2" was picked via experimentation:

```
1 threads -> 306 s
2 threads -> 199 s
3 threads -> 198 s
4 threads -> 195 s
```

changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by cocreature** [comment]
> AFAIK the daml start tests can't be parallelized without starting up a sandbox instance each time, which seems bad. These tests could be separated from the rest...

I think at least parts of it should be parallelizable by creating different parties per test. I think the one thing where this doesn’t apply is the reload test.

**Review by cocreature — APPROVED** [review]
Nice, thank you!

**Comment by sofiafaro-da** [comment]
> I think at least parts of it should be parallelizable by creating different parties per test. I think the one thing where this doesn’t apply is the reload test.

Good point. That sounds like it might be worth exploring in a future PR.

**Comment by cocreature** [comment]
> Good point. I think that might be worth exploring in a future PR.

Definitely something for a separate PR and probably not super urgent either, just wanted to mention the idea.

**Pull request merged**
