### PR TITLE
Enforce Java formatting style with google-java-format

### PR DESCRIPTION
**Pull request by stefanobaghino-da**
### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by stefanobaghino-da** [comment]
Note: this PR currently does not include the actual formatting to make reviewing easier (and test that formatting fails on CI as expected). Once we're clear that this is the kind of formatting we want to use, https://github.com/digital-asset/daml/pull/8685 can be merged here.

**Comment by stefanobaghino-da** [comment]
I just tested the IntelliJ IDEA plugin and (after enabling it explicitly and restarting the IDE) it worked as expected, taking over the IntelliJ default formatting.

**Comment by stefanobaghino-da** [comment]
Waiting for https://github.com/digital-asset/daml/pull/8673 to be merged before we merge this one.

**Comment by garyverhaegen-da** [comment]
> I just tested the IntelliJ IDEA plugin and (after enabling it explicitly and restarting the IDE) it worked as expected, taking over the IntelliJ default formatting.

Perhaps worth adding instructions to [our IntelliJ instructions](https://github.com/digital-asset/daml/blob/main/BAZEL.md#intellij-integration) as part of this PR?

**Comment by stefanobaghino-da** [comment]
> > I just tested the IntelliJ IDEA plugin and (after enabling it explicitly and restarting the IDE) it worked as expected, taking over the IntelliJ default formatting.
> 
> Perhaps worth adding instructions to [our IntelliJ instructions](https://github.com/digital-asset/daml/blob/main/BAZEL.md#intellij-integration) as part of this PR?

@garyverhaegen-da Makes a lot of sense, thanks for raising this. Does [this](https://github.com/digital-asset/daml/pull/8686/commits/0722c45edbd700b7e6e1333c0dd6ddb95bb45f92) working work?

**Comment by garyverhaegen-da** [comment]
> @garyverhaegen-da Makes a lot of sense, thanks for raising this. Does [this](https://github.com/digital-asset/daml/pull/8686/commits/0722c45edbd700b7e6e1333c0dd6ddb95bb45f92) wording work?

Yes, thanks!

**Review by cocreature — COMMENTED** [review]
I’m confused, why does this pass CI without actually reformatting everything?

**Comment by stefanobaghino-da** [comment]
> I’m confused, why does this pass CI without actually reformatting everything?

Because drafts don't go through all checks. 😉 

Now that https://github.com/digital-asset/daml/pull/8673 has been merged I'll merge https://github.com/digital-asset/daml/pull/8687 and promote this to a non draft for proper testing.

**Comment by cocreature** [comment]
huh drafts used to run CI

**Comment by stefanobaghino-da** [comment]
[CI check enforced successfully, merging the actual formatting.](https://dev.azure.com/digitalasset/daml/_build/results?buildId=68243&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=f58be928-45a1-58e7-c1ad-04869565b3f4)

**Comment by stefanobaghino-da** [comment]
@bame-da I isolated the application of the new code style in our docs to a single commit for your convenience ([here](https://github.com/digital-asset/daml/pull/8686/commits/05220130a42449f726cff8e494eecf158e75f07b)). The resulting code takes a bit more space but it's probably also more readable. Do you think that's ok?

### Before

before

### After

after

**Comment by bame-da** [comment]
Thanks @stefanobaghino-da. The docs part looks good to me - updated line numbers and everything 👏 . Lucky for you, I don't measure code quality in docs by how few lines they take, but only on how visually pleasing the layout looks when squinting.

**Comment by cocreature** [comment]
Verified that the changes are only formatting via
```
find . -name '*.java' -exec git restore -s 69b28d2ef2a851c3d8217ba075886366af6bf2e3 '{}' \;
./fmt.sh
````

**Review by cocreature — APPROVED** [review]
Thanks!

**Comment by garyverhaegen-da** [comment]
> I’m confused, why does this pass CI without actually reformatting everything?

```
Base automatically changed from ste/javafmt-dev-env  to main  3 hours ago
```
`PRs` only runs on branches targeting `main`.

**Pull request merged**
