### PR TITLE
[LF] add proper encoder tests for Builtins

### PR DESCRIPTION
**Pull request by remyhaemmerle-da**
We test encoder with exhaustive list of builtins for 1.11, 1.12, 1.13, 1.14, 1.15, 1.dev.

This test indirectly allso, LF parser, and LF type checking for builtins.

### CODE REVIEW

**Review by nickchapman-da — APPROVED** [review]
I like this systematic approach!

My only criticism is regarding the failure modes for this testing:

- If an `.lf` file fails to list an available builtin, we have to search through a wall of call stack to see which is missing, and in which version.

- If an `.lf` file tries to use a non-existing builtin, or specifies the wrong type for a builtin, or has any other syntax error... then the test fails with no indication at all about what went wrong. Which could made debugging very tricky!

**Comment by remyhaemmerle-da** [comment]
@nickchapman-da does cc43d032b72facdea911705f9b39e369ac83dfbe address your concern. 

Note that, because we are using `Table` (with a  `forEvery`) for the version, scalatest will output the problematic version

**Comment by nickchapman-da** [comment]
> Note also that the second cases cannot happend, because the LF-encoder only generates valid dar file.
Yes I noticed this too!

I wasn't precise enough...

When I said  "If an .lf file tries to use a non-existing builtin, or specifies the wrong type for a builtin, or has any other syntax error... then the test fails with no indication at all about what went wrong"

I meant the build of the test fails.. because the LF-encoder fails to generate a dar file.

My problem was I couldn't see the error report: for the unbound var, or type error or syntax error
But looking again, I see that it is there.
Sorry!

**Review by nickchapman-da — APPROVED** [review]
LGTM

**Pull request merged**
