### PR TITLE
fix Artifactory hashes

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
Apparently it's been silently broken since introduction all the way back
in #7196.

Huge thanks to @SamirTalwar-DA for reporting.

CHANGELOG_BEGIN
CHANGELOG_END

### CODE REVIEW

**Review by SamirTalwar-DA — COMMENTED** [review]
It worries me that this wasn't failing loudly. Do we need to add an extra `set -euo pipefail` at the top of the function?

**Review by cocreature — APPROVED** [review]
lgtm, if we can make it fail loudly we should definitely do so.

**Comment by garyverhaegen-da** [comment]
A bit of testing shows that a) I don't know enough Bash to be allowed to write any of it and b) it's not the function scope breaking the error reporting, it's the subshell evaluation within a string. In more concrete terms:

```bash
$ cat does_not_fail.sh               
#!/usr/bin/env bash

set -euo pipefail

f() {
    echo "hello $(echo ${there})"
}

f
$ bash does_not_fail.sh; echo $?      
does_not_fail.sh: line 6: there: unbound variable
hello 
0
$ cat fails_as_expected.sh            
#!/usr/bin/env bash

set -euo pipefail

f() {
    echo "hello ${there}"
}

f
$ bash fails_as_expected.sh; echo $?  
fails_as_expected.sh: line 6: there: unbound variable
1
$ cat fails_too.sh                
#!/usr/bin/env bash

set -euo pipefail

f() {
    local sub
    sub=$(echo ${there})
    echo "hello $sub"
}

f
$ bash fails_too.sh; echo $?       
fails_too.sh: line 7: there: unbound variable
1
$ 
```

Now I want a linter for bash that works on Bash-embedded-in-YAML that warns on subshells expanded within strings.

**Review by SamirTalwar-DA — APPROVED** [review]

**Comment by SamirTalwar-DA** [comment]
Looks to me that it's far too complicated to fail loudly. Let's just cross our fingers. :upside_down_face:

**Comment by garyverhaegen-da** [comment]
I've rewritten this bit to avoid expanding subshells inside of a string. I've made a note of reading all the rest of our Bash scripts for similar issues, but may not get to that today.

**Pull request merged**
