### PR TITLE
.rst target for the contract keys section

### PR DESCRIPTION
**Pull request by oggy-**
### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by oggy-** [comment]
Merci! I want to point to it from the Canton docs (eventually, once the new SDK version is out).

**Comment by cocreature** [comment]
Why don’t you just link to https://docs.daml.com/daml/reference/contract-keys.html? The ref is mainly useful for internal links since they are checked.

**Comment by oggy-** [comment]
Because we use `intersphinx` to link to the DAML repo Sphinx targets, so we know when our links to the DAML docs break. It's quite neat, you can observe it in its full glory here:
https://docs.daml.com/objects.inv

**Comment by cocreature** [comment]
Ah didn’t know that was a thing, thanks!

**Pull request merged**
