### PR TITLE
Engine: bug fix for transaction validation

### PR DESCRIPTION
**Pull request by remyhaemmerle-da**
This fix a severe bug in the transaction validation that was introduced in #5186.

Testing transaction validation should be done as part of  #6665.

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by remyhaemmerle-da** [comment]
> Assuming there are no tests for transaction validation at all so far, I’m fine with merging the fix first.

There is some basic cases in `EngineTest` that checks only for successful validation. 
There no test for failing validation.

**Comment by cocreature** [comment]
> There is some basic cases in `EngineTest` that checks only for successful validation.

Can we add a test that is successful now but would have failed before?

**Comment by remyhaemmerle-da** [comment]
> Can we add a test that is successful now but would have failed before?

No. The validation was too lenient, i.e. all test successful now was successful before.

**Comment by cocreature** [comment]
> No. The validation was too lenient, i.e. all test successful now was successful before.

Makes sense, thanks for the explanation!

**Comment by gerolf-da** [comment]
You could make a negative test, i.e. the test expects a failure, but previously wouldn't have failed.

**Comment by remyhaemmerle-da** [comment]
> You could make a negative test, i.e. the test expects a failure, but previously wouldn't have failed.

Yes I could. However #6665 is concerned about adding this kind of tests. Adding those tests is very tedious and I have no time to do it right now.

**Pull request merged**
