### PR TITLE
Add jq stream support to integration tests

### LINKED ISSUE #16447: Switch jq to use streaming mode in integration tests
Jq query current fails in trading test as the generated json is too large. jq's stream mode may fix this.
Once fixed, re-enable the QUERY-LF lines in bond-trading

### PR DESCRIPTION
**Pull request by samuel-williams-da**
Resolves #16447 

Added a new `-- @QUERY-LF-STREAM` pragma, that runs `jq` in stream mode.
Added a couple utils in jq library.
Converted and re-enabled the lf assertions in bond-trading.

### CODE REVIEW

**Review by dylant-da — APPROVED** [review]
Thanks for this, it should really help!

I'm a bit worried about the different semantics for jq when streaming (we use `-n` and read `inputs`), but a bit of experimenting with jq's stream/`inputs` behaviour makes me think there's nothing much better.

**Comment by samuel-williams-da** [comment]
Right right, I'm tempted to just always enable `-n`, and switch the general behaviour to always use inputs

**Comment by dylant-da** [comment]
> Right right, I'm tempted to just always enable `-n`, and switch the general behaviour to always use inputs

Yeah, I think moving forward that kind of change could be good

**Comment by samuel-williams-da** [comment]
Sure, I'll do that in this PR then :)

**Comment by samuel-williams-da** [comment]
Fair enough, will do!

**Pull request merged**
