### PR TITLE
Show function names in stack trace on failing scenario

### PR DESCRIPTION
**Pull request by hurryabit**
So far, we've only shown the location of the function but not its name.
Now, we add the name of the function as well.

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/unreleased.rst), if appropriate
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

---
This change is [Reviewable](https://reviewable.io/reviews/digital-asset/daml/2516)

### CODE REVIEW

**Comment by hurryabit** [comment]
Stack traces look like this now:
```
Stack trace:
- function fromSomeNote (DA.Optional:24:23)
- function fromSomeNote (DA.Optional:23:1)
- function $$dmfoldl1 (DA.Foldable:52:3)
- function maxOn (Utils:21:11)
- function maxOn (Utils:19:1)
- function winning (Round:179:29)
- function winning (Round:178:1)
- function signatories (Round:199:43)
- function signatories (Round:199:29)
- function signatories (Round:195:20)
- function signatories (Round:194:1)
- function $$dm_signatoryRound (Round:225:19)
- function $$dm_signatoryRound (Round:225:19)
- function $$dm_signatoryRound (Round:225:19)
- function $$dm_signatoryRound (Round:225:9)
```

**Comment by hurryabit** [comment]
Stack traces look like this now:
```
Stack trace:
- fromSomeNote (DA.Optional:24:23)
- fromSomeNote (DA.Optional:23:1)
- $$dmfoldl1 (DA.Foldable:52:3)
- maxOn (Utils:21:11)
- maxOn (Utils:19:1)
- winning (Round:179:29)
- winning (Round:178:1)
- signatories (Round:199:43)
- signatories (Round:199:29)
- signatories (Round:195:20)
- signatories (Round:194:1)
- $$dm_signatoryRound (Round:225:19)
- $$dm_signatoryRound (Round:225:19)
- $$dm_signatoryRound (Round:225:19)
- $$dm_signatoryRound (Round:225:9)
```

**Comment by hurryabit** [comment]
I'll add tests in a separate PR.

**Comment by stefanobaghino-da** [comment]
> I'll add tests in a separate PR.
Why?

**Comment by hurryabit** [comment]
@cocreature I've added a test. Can you please double check it makes sense:
https://github.com/digital-asset/daml/pull/2516/commits/7efabb2743498cf4e86b22347e49c4b4d8a43b87

**Comment by cocreature** [comment]
Test looks good to me, thanks a lot for adding it!

**Pull request merged**
