### PR TITLE
Use Postgres 10 for testing DAML-on-SQL.

### PR DESCRIPTION
**Pull request by gerolf-da**
This PR makes it so we use Postgres 10.x from nix for running the DAML-on-SQL tests.
### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/unreleased.rst), if appropriate
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by aherrmann-da** [comment]
@gerolf-da Looks like in `nix/bazel.nix` you also need to replace `postgresql` by `postgresql_10`.

**Comment by gerolf-da** [comment]
@aherrmann-da: Hm, I already had done that. What seems to be failing on CI doesn't fail for me locally :(

**Comment by gerolf-da** [comment]
The linux CI build fails with
```
ERROR: missing input file '@postgresql_dev_env//:bin/createlang'
...
ERROR: /home/vsts/agent/_work/1/s/ledger/sandbox/BUILD.bazel:155:1: //ledger/sandbox:sandbox-scala-tests_test_suite_src_test_suite_scala_com_digitalasset_platform_index_RecoveringIndexerSpec.scala: missing input file '@postgresql_dev_env//:bin/createlang'
...
ERROR: /home/vsts/agent/_work/1/s/ledger/sandbox/BUILD.bazel:155:1 19 input file(s) do not exist
```
But that build target works just fine on my local Mac. Any ideas?

**Comment by aherrmann-da** [comment]
`bin/createlang` exists in postgresql 9.6 and no longer exists in `10.8`. That test-case depends on `@postgresql_dev_env//:all`, which includes `bin/createlang` with postgresql 9.6. It seems that `dev_env_tool` does not properly explain all inputs to Bazel. I can reproduce the issue on linux by first executing
```
bazel test //ledger/sandbox:sandbox-scala-tests_test_suite_src_test_suite_scala_com_digitalasset_platform_index_RecoveringIndexerSpec.scala
```
then updating to `postgresql_10` in `nix/bazel.nix` and `WORKSPACE` and then rerunning the above `bazel test` command.

As a workaround you can remove the dependency on `@postgresql_dev_env//:all`. It doesn't seem to be required for this test-case
``` diff
diff --git a/ledger/sandbox/BUILD.bazel b/ledger/sandbox/BUILD.bazel
index bb6f21bbae..6977d94ce2 100644
--- a/ledger/sandbox/BUILD.bazel
+++ b/ledger/sandbox/BUILD.bazel
@@ -159,7 +159,6 @@ da_scala_test_suite(
     ),
     data = [
         "//ledger/test-common:Test-stable.dar",
-        "@postgresql_dev_env//:all",
         "@postgresql_dev_env//:createdb",
         "@postgresql_dev_env//:initdb",
         "@postgresql_dev_env//:pg_ctl",
```

**Comment by gerolf-da** [comment]
Thanks a lot, @aherrmann-da!

**Comment by garyverhaegen-da** [comment]
Does that mean we are dropping support for PostgreSQL 9.x and lower? Do we have any numbers on industry adoption and which version our users would prefer to use?

I know CI times are already problematic, but have we explored testing against more than one version?

**Comment by gerolf-da** [comment]
I haven't been able to find data about the adoption/deployment numbers for the various postgres versions (9.x, 10.x, 11.x). But, we did get requests from users asking whether DAML-on-SQL was being tested against 10.x specifically.

**Comment by stefanobaghino-da** [comment]
Should we close this? Looks stale.

**Pull request closed without merging**
