### PR TITLE
Remove daml3-script JSON client (2.x)

### PR DESCRIPTION
**Pull request by samuel-williams-da**
Remove the json ledger client from daml3-script.

### CODE REVIEW

**Comment by remyhaemmerle-da** [comment]
> Remove the json ledger client from daml3-script.

**Comment by samuel-williams-da** [comment]
For main, entirely, for main-2x, only removed from daml3-script.
Thus the flag still exists on this branch.
(Note that no-one external knows about daml3-script, and i don't believe anyone internal is using it via json)

**Review by remyhaemmerle-da — APPROVED** [review]

**Comment by remyhaemmerle-da** [comment]
fair enough

**Comment by samuel-williams-da** [comment]
The full daml3 removal is here #18503

**Pull request merged**
