### PR TITLE
rename master to main

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
As we strive for more inclusiveness, we are becoming less comfortable with historically-charged terms being used in our everyday work.

This is targeted for merge on Dec 26, _after_ the necessary corresponding changes at both the GitHub and Azure Pipelines levels.

```
CHANGELOG_BEGIN

- DAML Connect development is now conducted from the `main` branch,
  rather than the `master` one. If you had any dependency on the
  digital-asset/daml repository, you will need to update this parameter.

CHANGELOG_END
```

### CODE REVIEW

**Review by cocreature — APPROVED** [review]
Awesome! Thanks a lot for doing this. Changes all look good to me. Obviously hard to see what is missing during review but I’m sure you’ve grepped to find all occurences.

**Comment by garyverhaegen-da** [comment]
> Awesome! Thanks a lot for doing this. Changes all look good to me. Obviously hard to see what is missing during review but I’m sure you’ve grepped to find all occurences.

Missing things being the most obvious concern, I've actually done it the other way around: I've started with
```
find $(echo *) -type f -print0 | xargs -0 sed -i 's/master/main/g'
```
then manually reverted all the ones that did not seem relevant. So I'm fairly sure this should be complete. (Keyword being _manually_, so errors are definitely still possible.)

**Comment by bame-da** [comment]
How will open PRs be handled? Will someone go around on the 26th and Request Changes to all open PRs to master or does the rename automatically change PRs to point to main?

**Comment by cocreature** [comment]
> How will open PRs be handled? Will someone go around on the 26th and Request Changes to all open PRs to master or does the rename automatically change PRs to point to main?

We’ll send out an email with all the details including updating your old repo and updating PRs.

**Comment by garyverhaegen-da** [comment]
Adding standard change label because this changes comments and cos under `infra/`.

Note that this PR itself is arguably a standard change anyway for other reasons, and the change is tracked internally as CM-160.

**Pull request merged**
