### PR TITLE
Update 5_Restrictions.rst

### PR DESCRIPTION
**Pull request by jordan-mittleman**
### Pull Request Checklist

- [ ] Going more in depth regarding setting time in scenarios (what the parameters/format looks like, even though there are examples in daml-intro-5)

### CODE REVIEW

**Comment by bethaitman** [comment]
@jordan-mittleman - have you signed the contributor license agreement? Github seems to think you haven't.

Alternatively - @hurryabit , can we get Jordan added to our Github org?

**Comment by hurryabit** [comment]
If @jordan-mittleman doesn't mind signing the CLA, then going this route seems to be the easier way.

**Comment by cocreature** [comment]
Closing as obsolete.

**Pull request closed without merging**
