### PR TITLE
LF: Drop some tests for deprecated LF versions

### PR DESCRIPTION
**Pull request by remyhaemmerle-da**
Since #5321, LF versions < 1.6 are deprecated. This PR drops some tests
for those deprecated versions.

CHANGELOG_BEGIN
CHANGELOG_END

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by cocreature — COMMENTED** [review]
Do we still support those versions in Sandbox classic? What about DAML on SQL?

**Comment by remyhaemmerle-da** [comment]
> Do we still support those versions in Sandbox classic? What about DAML on SQL?

Since #7415, Sandbox classic does not supported then any more.

**Review by cocreature — APPROVED** [review]
Thanks!

**Review by hurryabit — APPROVED** [review]
Nice catch. Thanks.

**Pull request merged**
