### PR TITLE
Remove references to the legacy error codes from docs [DPP-773]

### PR DESCRIPTION
**Pull request by kamil-da**
### Changes
- remove the `Configuration` section describing how to switch to the legacy error codes
- remove the Error Code Migration Guide

CHANGELOG_BEGIN
CHANGELOG_END

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by pbatko-da — APPROVED** [review]

**Comment by pbatko-da** [comment]
Have checked how the docs render after those removals?
```
./docs/scripts/live-preview.sh --gen
```

**Review by mziolekda — APPROVED** [review]

**Review by tudor-da — APPROVED** [review]
LGTM! Are you planning to remove the [yml files](https://github.com/digital-asset/daml/tree/a727a9efc5a7620608e071653560612545b8c997/ledger/participant-integration-api/src/docs/resources/com/daml/platform/docs) based on which there were generated in a separate PR?

**Comment by kamil-da** [comment]
> Have checked how the docs render after those removals?
> 
> ```
> ./docs/scripts/live-preview.sh --gen
> ```

@pbatko-da  Yes, I did, but thank you for the heads up!

**Comment by kamil-da** [comment]
> LGTM! Are you planning to remove the [yml files](https://github.com/digital-asset/daml/tree/a727a9efc5a7620608e071653560612545b8c997/ledger/participant-integration-api/src/docs/resources/com/daml/platform/docs) based on which there were generated in a separate PR?

@tudor-da I haven't noticed these files, thanks! I'll open a follow-up 👍

**Pull request merged**
