### PR TITLE
Failing example

### PR DESCRIPTION
**Pull request by oggy-**
### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by SamirTalwar-DA** [comment]
For the record, this results in the following test failure:

```
CommandService
- A command resulting in no creates/archives works with flat transactions ... Unexpected failure (StatusRuntimeException)
  NOT_FOUND: Transaction not found, or not visible.
```

**Comment by SamirTalwar-DA** [comment]
@oggy-: This is only running on macOS right now because it fails linter checks (which only run on Linux), and Windows doesn't run the conformance tests.

You can run `./fmt.sh` to fix this.

**Comment by garyverhaegen-da** [comment]
No movement in almost 18 months; closing.

**Pull request closed without merging**
