### PR TITLE
Build & releases 1.13 Ledger API test tool

### PR DESCRIPTION
**Pull request by cocreature**
Temporary hack to unblock Canton until they finish their exception support.

changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by oliverse-da — APPROVED** [review]
Thank you!

**Review by remyhaemmerle-da — COMMENTED** [review]
We can also revert the change in the function `daml_lf_compatible` in `compatibility/bazel_tools/testing.bzl` 

See 213893fdf69c32757afd35d896a52916620eb264

**Comment by cocreature** [comment]
> We can also revert the change in the function `daml_lf_compatible` in `compatibility/bazel_tools/testing.bzl`
> 
> See [213893f](https://github.com/digital-asset/daml/commit/213893fdf69c32757afd35d896a52916620eb264)

That’s a bit of a larger change. The default ledger API test tool version is still 1.14 which is picked up by the compat tests. We need to download different versions and pick the right one depending on what we tes tagainst.

**Comment by remyhaemmerle-da** [comment]
> > We can also revert the change in the function `daml_lf_compatible` in `compatibility/bazel_tools/testing.bzl`
> > See [213893f](https://github.com/digital-asset/daml/commit/213893fdf69c32757afd35d896a52916620eb264)
> 
> That’s a bit of a larger change. The default ledger API test tool version is still 1.14 which is picked up by the compat tests. We need to download different versions and pick the right one depending on what we tes tagainst.

Indeed. Forget my comment.

**Review by remyhaemmerle-da — APPROVED** [review]
Thanks.

**Pull request merged**
