### PR TITLE
add puppeteer dependencies to Linux nodes

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
See #5540 for context.

CHANGELOG_BEGIN
CHANGELOG_END

### CODE REVIEW

**Comment by garyverhaegen-da** [comment]
Can't reproduce the problem locally (in a VM), so not sure this will fix anything.

As a test, I'll pick one of the CI machines and:
- Remove it from the Azure pool so it doesn't get new jobs assigned.
- Manually checkout the branch from #5540 and run the offending test (`//daml-assistant/integration-tests:create-daml-app-tests`), checking that I get the same error message.
- Manually run the `apt-get` command here to install the dependencies.
- Try running the test again.
- Delete the machine, so the group manager creates a fresh new one.

@cocreature @hurryabit Does this sound sensible as a testing strategy?

**Comment by garyverhaegen-da** [comment]
Picked `vsts-agent-linux-5t3z`, removed from Azure pool. Will connect and run manually now.

**Comment by garyverhaegen-da** [comment]
Can reproduce the CI error messages when logged into a CI node (which is reassuring), will try the `agt-get` command now.

**Comment by garyverhaegen-da** [comment]
I can confirm that installing those libraries does make the test go green. Will kill the machine now and deploy this later tonight.

**Comment by rohanjr** [comment]
Good news, thanks @garyverhaegen-da!

**Comment by garyverhaegen-da** [comment]
Successfully (as per Terraform's notion of success) applied 43def51fce338154bc2d95bd9e4397b6a20c2db6.

**Comment by garyverhaegen-da** [comment]
And now #5540 passes. :tada:

**Pull request merged**
