### PR TITLE
Introduce insertWith from Map to TextMap and refactor fromListWithL.

### PR DESCRIPTION
**Pull request by yangzai**
Follows #18753.

### CODE REVIEW

**Review by dylant-da — APPROVED** [review]
Looks good to me, have run //compiler/damlc/tests:stable-packages and //compiler/damlc/tests:platform-independence-dar-hash-file-matches locally to be sure of DAR hashes

**Comment by remyhaemmerle-da** [comment]
Be aware `TextMap` is deprecate in main, and very probably not survived in Daml 3.x.
If you want the change to be included in  the upcoming  2.10 release, one need to backport #18753 and this PR to the branch [main-2.x](https://github.com/digital-asset/daml/tree/main-2.x)

**Review by remyhaemmerle-da — APPROVED** [review]
Thanks for the contribution.

**Comment by dylant-da** [comment]
If you'd like any help with backporting, please feel free to reach out

**Comment by yangzai** [comment]
> Looks good to me, have run //compiler/damlc/tests:stable-packages and //compiler/damlc/tests:platform-independence-dar-hash-file-matches locally to be sure of DAR hashes

Feel free to make direct changes to the branch if the hashes have change.

**Pull request merged**
