### PR TITLE
rs-grpc-bridge-test-lib: remove unneeded deps

### PR DESCRIPTION
**Pull request by curiousleo-da**
### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

---

The entirety of this library is this one file:

```scala
package com.daml.grpc.adapter;

public class TestExecutionSequencerFactory {
    public static ExecutionSequencerFactory instance = new SingleThreadExecutionSequencerPool("rs-grpc-bridge-testing");
}
```

It doesn't need a lot of dependencies.

### CODE REVIEW

**Review by cocreature — COMMENTED** [review]
Why does the unused dependency checker not catch this?

**Review by SamirTalwar-DA — APPROVED** [review]
It looks fine, but I would also like to know why the unused dependency checker doesn't pick this up.

Regardless, feel free to merge when the build stops flaking.

**Comment by curiousleo-da** [comment]
> Why does the unused dependency checker not catch this?

I didn't know there was such a thing in the repo. Where does it live? I'm happy to report this as a bug, but I don't know where :)

**Comment by aherrmann-da** [comment]
> > Why does the unused dependency checker not catch this?
> 
> I didn't know there was such a thing in the repo. Where does it live? I'm happy to report this as a bug, but I don't know where :)

It's a [feature of rules_scala](https://github.com/bazelbuild/rules_scala/#experimental-unused-dependency-checking) and enabled [here](https://github.com/digital-asset/daml/blob/566d3a21d150dbff780968f8730be3f531991b14/bazel_tools/scala.bzl#L138-L140).

**Pull request merged**
