### PR TITLE
Reactivate windows tests disable in #16760

### PR DESCRIPTION
**Pull request by remyhaemmerle-da**
namely:
-  //daml-script/export/integration-tests/reproduces-transactions:test
-  //compiler/damlc:daml-stdlib-doctest

### CODE REVIEW

**Review by akrmn — APPROVED** [review]

**Comment by garyverhaegen-da** [comment]
I've shut down the `remy` machine as it didn't seem to help.

**Review by garyverhaegen-da — DISMISSED** [review]
Temporarily blocking merge as the current successes were on GCP.

**Comment by garyverhaegen-da** [comment]
Some progress: the doctest one at least is not an Azure v. GCP issue, but a Windows 2016 v. Windows 2022 issue (i.e. Azure is currently running Windows 2022, and if we run Windows 2022 on GCP that fails at the same point in the same way).

**Review by nickchapman-da — APPROVED** [review]
Love the improvements to the Haskell to make the imports explicit. So hard to work on Haskell code without this. :+1: 

LGTM

**Comment by remyhaemmerle-da** [comment]
:tada:

**Pull request merged**
