### PR TITLE
Update to ghc-lib-0.20190425.1

### PR DESCRIPTION
**Pull request by shayne-fletcher-da**
This PR updates daml to 0.20190425.1 incorporating the latest changes to the GHC parser on HEAD.

### CODE REVIEW

**Comment by cocreature** [comment]
CI failures look legitimate
```
da-hs-damlc-app: user error (DAML-1.2 to LF compilation failed
File:     language-support/scala/codegen-sample-app/src/main/daml/MyMain.daml
Range:    193:1-195:32
Source:   Compiler
Severity: Error
Message: 
  language-support/scala/codegen-sample-app/src/main/daml/MyMain.daml:193:1: error:
  Parse error in pattern: bitOptionUpdate
)
```

**Comment by shayne-fletcher-da** [comment]
@moritzkiefer-da  @neil-da  I'm afraid it is. It relates to code like this:
```
  f (x : Int) : Int = ...
```
and changed/added "parser validator" code in `RdrHsSyn.hs`. Seeing what can be done.

**Comment by neil-da** [comment]
The only reason we supported that syntax was due to a patch by Tim Williams. Any chance his patch got lost/corrupted in the change?

**Comment by shayne-fletcher-da** [comment]
No, it's not that Tim's code has got lost. There is revised/new logic for checking patterns ("parser validation") in `RdrHsSyn.hs`.

**Comment by shayne-fletcher-da** [comment]
Have cracked it. 
> Any chance his patch got lost/corrupted in the change?
Right as always @neil-da  :) New ghc-lib on the way.

**Pull request merged**
