### PR TITLE
integration-kit: remove all its docs

### PR DESCRIPTION
**Pull request by meiersi-da**
Product decisions to be made, paging @davidrichards-da and @resmela-da and @bame-da :
- [x] should the [component status docs for the integration kit](https://docs.daml.com/support/component-statuses.html#integration-components) be completely removed or updated with the change in status? Answer from @bame-da : yes
- [x] how to update the section on Daml Networks and Drivers, https://docs.daml.com/support/overview.html#daml-networks, given that the "Integration Components" section has been removed

Engineering decisions to be made, paging @gerolf-da and @miklos-da and @mziolekda : 
- [x] should we completely remove the docs for the `ledger-api-test-tool`, https://docs.daml.com/tools/ledger-api-test-tool/index.html, or keep them somewhere? My vote is to remove them, as the CLI help text is sufficient and easier to keep up to date

```
CHANGELOG_BEGIN
- [Daml Integration Kit]: removed from Daml 2.0
CHANGELOG_END
```

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [x] Normal production system change, include purpose of change in description
- [x] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by gerolf-da — APPROVED** [review]
Thanks, @meiersi-da!

**Comment by gerolf-da** [comment]
I agree with removing the ledger-api-test-tool entirely from the docs.

**Comment by stefanobaghino-da** [comment]
> I agree with removing the ledger-api-test-tool entirely from the docs.

Is it still meant as a way to test generic ledger implementations outside of our repo? Otherwise the tests can possibly be transitioned back to normal integration tests and the test framework around it can be dropped.

**Comment by meiersi-da** [comment]
> > I agree with removing the ledger-api-test-tool entirely from the docs.
> 
> Is it still meant as a way to test generic ledger implementations outside of our repo? Otherwise the tests can possibly be transitioned back to normal integration tests and the test framework around it can be dropped.

We still need to be able to use the `ledger-api-test-tool` to test whether VMBC is a proper daml ledger; i.e., our testing approach needs to work with a fixed out-of-process ledger. However, we might still want to transition back to a Scalatest based runner, as that could also use a fixture that talks to a remote ledger, couldn't that @stefanobaghino-da ?

**Comment by bame-da** [comment]
You did exactly what I was going to recommend anyway: remove the section on integration components 👍

**Pull request merged**
