### PR TITLE
upgrade h2 to latest version without sec vulns

### PR DESCRIPTION
**Pull request by dasormeter**
### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by cocreature — APPROVED** [review]
lgtm,
if I understand this correctly we’re not affected by this since we don’t do any xml magic wtr to h2?

**Comment by cocreature** [comment]
looks like some sql statements need changing

**Comment by dasormeter** [comment]
there are some breaking schema changes that need to be dealt with trivial upgrade not possible

closing for now

```
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "SELECT VALUE[*] FROM INFORMATION_SCHEMA.SETTINGS WHERE NAME = 'MODE'"; expected "TOP, DISTINCT, ALL, ,, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
SELECT VALUE FROM INFORMATION_SCHEMA.SETTINGS WHERE NAME = 'MODE' [42001-202]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.getSyntaxError(DbException.java:261)
	at org.h2.command.Parser.getSyntaxError(Parser.java:1286)
	at org.h2.command.Parser.readTerm(Parser.java:5513)
	at org.h2.command.Parser.readFactor(Parser.java:3726)
	at org.h2.command.Parser.readSum(Parser.java:3713)
	at org.h2.command.Parser.readConcat(Parser.java:3678)
	at org.h2.command.Parser.readCondition(Parser.java:3461)
	at org.h2.command.Parser.readExpression(Parser.java:3381)
	at org.h2.command.Parser.parseSelectExpressions(Parser.java:3196)
	at org.h2.command.Parser.parseSelect(Parser.java:3213)
	at org.h2.command.Parser.parseQuerySub(Parser.java:3092)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:2930)
	at org.h2.command.Parser.parseQuery(Parser.java:2900)
	at org.h2.command.Parser.parsePrepared(Parser.java:1101)
	at org.h2.command.Parser.parse(Parser.java:1068)
	at org.h2.command.Parser.parse(Parser.java:1041)
	at org.h2.command.Parser.prepareCommand(Parser.java:965)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:614)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:552)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1111)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:283)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.prepareStatement(JdbcTemplate.java:344)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.queryForString(JdbcTemplate.java:196)
	at org.flywaydb.core.internal.database.h2.H2Database.determineCompatibilityMode(H2Database.java:87)
	... 13 common frames omitted


```

**Comment by dasormeter** [comment]
rework of information_schema is the culprit, likely

```
Some new features:

Complete re-work of INFORMATION_SCHEMA to be more in-line with the standard
Support for new types: ARRAY, ROW, JAVA_OBJECT
Numerous bit, string, array and system functions implemented
Standard-based access to generated keys
JDBC 4.2 compliance
Support for JDK 7 is dropped
PageStore is discontinued
```

from https://github.com/h2database/h2database/releases/tag/version-2.0.202

**Pull request closed without merging**
