### PR TITLE
reference-v2, sandbox: Add the dependency on PostgreSQL where required.

### PR DESCRIPTION
**Pull request by SamirTalwar**
And remove it from the tests, as they now pick it up from the binary.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/unreleased.rst), if appropriate
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by SamirTalwar** [comment]
I think we can trim down the list of PostgreSQL dependencies in general. If we're depending on `@postgresql_dev_env//:all`, we don't also need to include the individual binaries. Let's see if it works on CI though.

**Comment by dasormeter** [comment]
`bazel run //ledger/api-server-damlonx/reference-v2:ephemeral-postgres-reference-server` works for me on this branch :)

**Comment by dasormeter** [comment]
`bazel test //ledger/api-server-damlonx/reference-v2/...` also good locally                                                                                           
INFO: Writing tracer profile to '/private/var/tmp/_bazel_brianhealey/191c77e1bcea6e1b949558cf8ebb3be9/command.profile.gz'
INFO: Invocation ID: e671529d-979f-4a50-8d68-d55522ad6aa2
DEBUG: /private/var/tmp/_bazel_brianhealey/191c77e1bcea6e1b949558cf8ebb3be9/external/bazel_skylib/lib.bzl:30:1: WARNING: lib.bzl is deprecated and will go away in the future, please directly load the bzl file(s) of the module(s) needed as it is more efficient.
INFO: Analyzed 7 targets (0 packages loaded, 0 targets configured).
INFO: Found 3 targets and 4 test targets...
INFO: Elapsed time: 100.701s, Critical Path: 40.50s
INFO: 8 processes: 1 remote cache hit, 6 local, 1 processwrapper-sandbox.
INFO: Build completed successfully, 5 total actions
//ledger/api-server-damlonx/reference-v2:reference-ledger-dump-integrity-test (cached) PASSED in 0.3s
//ledger/api-server-damlonx/reference-v2:conformance-test-h2database     PASSED in 30.4s
//ledger/api-server-damlonx/reference-v2:conformance-test-h2database-multi-node PASSED in 28.1s
//ledger/api-server-damlonx/reference-v2:conformance-test-postgres       PASSED in 40.4s

**Comment by stefanobaghino-da** [comment]
Smart.

**Pull request merged**
