### PR TITLE
Compile time errors for unsupported primitives

### PR DESCRIPTION
**Pull request by dylant-da**

### CODE REVIEW

**Comment by basvangijzel-DA** [comment]
Looks fine, but we should really have a unit test covering this new behaviour. From following the code it seems that we're missing test coverage for templates containing these types?

**Comment by dylant-da** [comment]
> Looks fine, but we should really have a unit test covering this new behaviour. From following the code it seems that we're missing test coverage for templates containing these types?

To actually exercise this requires that we output an unsupported version of LF, so such an error actually can't actually be triggered as far as I can tell, since we only support outputting 1.14-1.dev and these primitives were introduced in 1.13

@moisesackerman-da Is there a way to output older LF versions in tests, possibly 1.8?

**Comment by dylant-da** [comment]
nvm - I'm going to use the compile-time `whenSupports` helper for `UExerciseInterfaceGuarded` too, so I can test that

**Comment by dylant-da** [comment]
The code that removes interface instances does too good a job, so the guard in UExerciseInterfaceGuarded is never triggered in versions that are too old. I tried making it emit an error for simple interfaces as well in 1.14, but that didn't work either because we already have checks for that, and because searching for primitives isn't actually a great way of tracking version mismatches.

**Comment by akrmn** [comment]
> Is there a way to output older LF versions in tests, possibly 1.8?

not as far as I know. The `--target` option is filtered according to [`supportedOutputVersions`](https://github.com/digital-asset/daml/blob/main/compiler/daml-lf-ast/src/DA/Daml/LF/Ast/Version.hs#L63-L64), so it only accepts `1.14`, `1.15` and `1.dev`.

**Comment by akrmn** [comment]
honestly, I have the hunch that we can just remove all guards for lf-version < 1.14, since we can't possibly output that anyway, but I'd like to ensure this at the type level.

**Pull request closed without merging**
