### PR TITLE
Replace FilePath with FilePath.Posix

### PR DESCRIPTION
**Pull request by shayne-fletcher**

### CODE REVIEW

**Comment by robin-da** [comment]
I thought FilePath is usually the better import than FilePath.Posix, won't this be used under windows?

**Comment by shayne-fletcher** [comment]
@robin-da you are right and that was the motivation for not replacing filepath with the posix version wholesale before now. please see the discussion here https://github.com/digital-asset/daml/pull/4951 and let me know what you think!

**Comment by cocreature** [comment]
There are two cases two consider:
1. File paths that end up in the generated typescript sources: For those we want to use `/` consistently.
2. Actual file path operations  performed in the codegen. In general, we need to use `System.FilePath` here but for the subset used by the tests we can probably get away with using `System.FilePath.Posix` which avoids accidentally using `System.FilePath` for 1.

**Comment by shayne-fletcher** [comment]
So @cocreature , @robin-da , perhaps the safer path is to not land this? That is, stick with,
```
import System.FilePath hiding ((<.>), (</>)) 
import System.FilePath.Posix((</>)) -- Make sure we generate / on all platforms.
import qualified System.FilePath as FP
```
That is, be sure to use '/' when we write `</>` but got to `FilePath` for any "real" file path operations?

**Comment by cocreature** [comment]
Yeah, I think the current state is probably safer.

**Comment by shayne-fletcher** [comment]
> Yeah, I think the current state is probably safer.

I agree. Withdrawing this PR.

**Pull request closed without merging**
