### PR TITLE
HOTFIX add Blackduck CoPilot to azure pipeline

### PR DESCRIPTION
**Pull request by dasormeter**

### CODE REVIEW

**Comment by moritzkiefer-da** [comment]
Should we close this in favor of #370?

**Comment by cocreature** [comment]
@sormeter What are your plans here? It looks like we have #271 and #461, neither of which have been touched in quite some time.

**Comment by dasormeter** [comment]
@cocreature i think we want #461 first as this does a full scan for true PR contribution.

Blackduck CoPilot is a true open source thing that can be run by external contributors without sending anything back to our licensed blackduck instance so this was an exploratory thing to see if this is viable for our repo.  At the moment CoPilot lags behind our Blackduck instance although blackduck claim it should be brought up to speed in May -- i'll move this to a draft PR

**Comment by garyverhaegen-da** [comment]
@dasormeter Why do we want this? What happened to "should be done in May"? We're now in June.

**Pull request closed without merging**
