### PR TITLE
Disable scaladoc on the MacOS CI

### LINKED ISSUE #4441: Only build Scaladoc in CI on Linux, and make it optional for local development
We currently spend a lot of time and processing power building Scaladoc for all our artifacts. I believe this is because we need to publish Scaladoc to Maven Central, which is admirable, but we probably don't need to do this multiple times.

Looks like we only release to Maven Central from Linux. If this is actually the case (I could be wrong), then let's only build the Scaladoc on Linux and save ourselves some time in the other CI builds.

I propose doing this with a Bazel tag, which will also allow us to selectively disable Scaladoc builds locally to speed up development.

### PR DESCRIPTION
**Pull request by cocreature**
It is still built by default locally.

fixes #4441

changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by SamirTalwar-DA** [comment]
Can we use a specific tag rather than "dont-run-on-darwin" (e.g. "no-scaladoc" or something)? I will probably want to turn this on sometimes when running locally, and I'd quite like it if I could read my _.bazelrc_ file in a month and understand why I would set that tag.

**Comment by SamirTalwar-DA** [comment]
Also, can we disable these on Windows too? 🙃

**Comment by cocreature** [comment]
They are already disabled on Windows (completely not via a tag).

**Comment by cocreature** [comment]
Changed the tag to `scaladoc` so to exclude it pass `-scaladoc`.

**Comment by SamirTalwar-DA** [comment]
Ironic that this PR is being held up by the macOS build. 🍎

**Pull request merged**
