### PR TITLE
DEL-8657 update version info for Haskell LF libraries

### PR DESCRIPTION
**Pull request by jberthold-da**
We are past the 1.14 feature set so it is 1.15, even though more changes may come in before 1.15.0 is released.

### CODE REVIEW

**Review by garyverhaegen-da — APPROVED** [review]
Not very familiar with this setup, but bumping seems sensible enough. Is there any reason why this should not be unified with, say, the max version from LATEST?

**Comment by jberthold-da** [comment]
Thanks Gary! 
Using `LATEST` is definitely an option (I was unaware that this version file exists and is maintained). The only caveat would be that  modules might get added or removed every now and then, which could render the build invalid unless the `*.cabal` file reflects the change. In the past there was no desire from the language team to maintain these cabal files so I took it upon myself, and I can continue to do it manually.
### Options
1) keep the status-quo of manual version bumps and maintenance
2) use `LATEST` to determine the version number; accept temporary breakage and leave maintenance of `cabal` files with me
3) use `LATEST` to determine the version number; add a test for the artefact so that everybody working on these packages needs to adapt the `cabal` files when their cabal/stack build fails

Note that 3) still misses out on added modules if they are unused (but that is perfectly acceptable for my purpose). 3) also means to figure out how to reliably build the packages with stack plus a given stackage resolver, but that should not be hard.

**Comment by garyverhaegen-da** [comment]
For context, the `LATEST` file is not just "maintained", it _is_ the trigger for releasing new versions. So you really can rely on it being up-to-date.

I don't know enough about the Haskell world to understand how much effort is involved in maintaining cabal files, and I don't know enough about these particular packages to have any idea how often they change and thus might break, so I'm afraid I won't be much help in making a decision here.

**Comment by cocreature** [comment]
I’ll happily accept PRs that switch to `LATEST` (although it’s not entirely clear to me that this is correct, there is a reason why nothing else reads that file and we instead get the version from an env var) but given that these bindings are explicitly not supported externally, I’m not going to spend effort from my teams on those cabal files.

**Comment by garyverhaegen-da** [comment]
Looks like option 1, then. Sorry for the noise.

**Pull request merged**
