### PR TITLE
ledger-on-posix-filesystem: Burn it to the ground.

### PR DESCRIPTION
**Pull request by SamirTalwar-DA**
This has outlived its usefulness as an experiment in how to implement a
kvutils-based leger, and is now just a source of flaky test runs.

🔥

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by SamirTalwar-DA** [comment]
@miklos-da, if you'd like to preserve this in another repository, now's your chance.

**Comment by cocreature** [comment]
Let’s replace it by `ledger-on-windows-filesystem`.

**Comment by SamirTalwar-DA** [comment]
@cocreature: Pretty sure this would work on Windows now; doesn't rely on atomic moves any more.

**Comment by cocreature** [comment]
@SamirTalwar-DA famous last words

**Pull request merged**
