### PR TITLE
ADD: User guides for deploying on opensource sawtooth and fabric

### PR DESCRIPTION
**Pull request by anthonylusardi-da**
User guides for Sawtooth and Fabric. 

Original blockers:
- [x] create-daml-app adding support for custom ledgerids
- [ ] daml-on-sawtooth addressing the caveats mentioned in the document to the best of their ability (ideally removing all caveats)
- [ ] daml-on-fabric addressing the caveats mentioned in the document to the best of their ability (ideally removing all caveats)

Additional blockers:
- [ ] daml-on-sawtooth pending upgrade to 1.0
- [ ] daml-on-fabric pending new release supporting 1.0

These changes are beyond the scope of this PR so will be addressing separately with their maintainers.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by cocreature** [comment]
What needs to be done here before we can merge this? We already have external users that follow https://festive-jackson-9a7320.netlify.app/deploying-daml/fabric-deployment.html which we presumably linked somewhere. I’d much rather have this in our official docs and updated to the latest SDK.

One obvious thing is missing is that the GSG has changed in a few ways so this needs some minor adjustments but you marked this as a draft before that was the case so presumably you have something else in mind.

**Comment by anthonylusardi-da** [comment]
Updated the list of blockers. The `create-daml-app` one is resolved but we need the caveats removed and the ledgers supporting daml 1.0.

**Comment by cocreature** [comment]
I don’t see why we need those caveats removed before merging this (apart from the 1.0 upgrade). Users are already following these instructions. I’d rather have them follow those instructions on `docs.daml.com` than some random netlify instance.

**Comment by anthonylusardi-da** [comment]
Simply because it's not a great experience. But happy to merge once 1.0 is supported, and can split the docs into separate PRs if one is ready before the other.

**Comment by cocreature** [comment]
I do agree that the experience is not great but I think it’s even worse if you follow it on a separate website that is not kept up2date at all.

**Comment by anthonylusardi-da** [comment]
This PR will be replaced by 2 individual PRs when their respective daml-on-x projects are ready.

**Pull request closed without merging**
