### PR TITLE
fix Exception intro template

### PR DESCRIPTION
**Pull request by garyverhaegen-da**

### CODE REVIEW

**Review by samuel-williams-da — APPROVED** [review]

**Comment by samuel-williams-da** [comment]
Maybe check the Ious are created? up to you

**Comment by garyverhaegen-da** [comment]
> Maybe check the Ious are created? (instead of simply failing and having no affect on the ledger) Up to you

I'm not familiar enough with this code or how it's used by the docs to have much of an opinion here. I think what's important in this PR is that we are now exercising the code that actually throws an exception, and checking that we are. Beyond that, I don't really know what the behaviour is intended to be. For example, it seems really weird to me that `OrderItemTrustedLimited` returns a `ContractId Order` rather than an `Optional`. Current behaviour seems to be that the order is created regardless, but that makes little sense to me if you can't pay for it.

**Comment by samuel-williams-da** [comment]
I'm not too familiar either, I moreso wanted to check the `catch` behaviour was working, though I guess if the submit fails without following that path, it'd fail out the entire Script anyway

**Comment by garyverhaegen-da** [comment]
> I'm not too familiar either, I moreso wanted to check the `catch` behaviour was working, though I guess if the submit fails without following that path, it'd fail out the entire Script anyway

I'm hoping `catch` is tested in the compiler/language tests already. This is just the introductory documentation.

**Review by akrmn — APPROVED** [review]
> I think what's important in this PR is that we are now exercising the code that actually throws an exception, and checking that we are. 

agreed!

> Beyond that, I don't really know what the behaviour is intended to be. For example, it seems really weird to me that `OrderItemTrustedLimited` returns a `ContractId Order` rather than an `Optional`. Current behaviour seems to be that the order is created regardless, but that makes little sense to me if you can't pay for it.

I think this does make sense because the customer still pays in the form of an `Iou` towards the shop owner. We can add a `query` to make sure that this `Iou` was created after exercising `OrderItemTrustedLimited`. 

> I'm not too familiar either, I moreso wanted to check the `catch` behaviour was working, though I guess if the submit fails without following that path, it'd fail out the entire Script anyway

checking the `Iou` was created should cover this. To check that `TransferLimited` indeed throws a `TransferLimitExceeded`, I'd add something like this at the end of `test`:

```haskell
  threwTransferLimitExceeded <- do
    try do
      exercise accountCid (TransferLimited shopOwner 100)
      pure False
    catch
      (e : TransferLimitExceeded) -> pure True
  unless threwTransferLimitExceeded $ 
    error "expected TransferLimitExceeded exception"
```

**Pull request merged**
