### PR TITLE
language: some small fixes to the daml source gen from dalfs.

### PR DESCRIPTION
**Pull request by robin-da**
Two changes: Make sure `DA.Internal.Template` is imported if necessary
and convert variants with unit argument correctly.

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/unreleased.rst), if appropriate
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by robin-da** [comment]
the only thing right now would be golden tests, where you check that the result of the compilation of the generated source matches your expectations. but that's just saying that you're not allowed to change the source generating code anymore. instead of golden tests, I'd prefer we have a little test framework that takes fixed dalfs, reads them, generates interface files from them and checks that another package can import the module and execute the template methods.

**Comment by cocreature** [comment]
I feel like I’m missing something. My understanding was that you’ve just ripped out parts of the upgrading code and we already have a test to build against those stubs so it doesn’t seem to be completely broken. Why can’t we add more similar tests with the only difference being that the input is a hand-crafted DAR instead of something built using `daml build`?

**Comment by robin-da** [comment]
we have an integration test in the daml-assistant tests. but this one only tests the same sdk. I need tests that can take arbitrary dalfs and not only test compilation but also that you can actually call the generated template methods. I'm testing manually right now, and that fails. What works is that you can generate source from dalfs and have a succesful compilation. but that only means that you're generating valid DAML source. the next thing I want to do is a) figure out what the issue is, b) automate the manual testing and make it part of the CI.

**Comment by cocreature** [comment]
Testing that it builds still seems better than not testing anything.

**Comment by robin-da** [comment]
It builds with or without this PR. I can also just wait with merging this PR, until I have figured the real issue out and wrote a decent test suite. Just means this PR will sit around for long.

**Comment by robin-da** [comment]
Thanks! I definitely agree on the testing. I'll add infrastructure for these tests as a next step.

**Pull request merged**
