### PR TITLE
Update hlint; enable bracket hints

### PR DESCRIPTION
**Pull request by shayne-fletcher-da**
Draft PR, not ready for review or landing

This PR updates hlint and thereby enables hints about redundant brackets. Before this lands, the template desugaring and record-dot-preprocessor code needs to be updated so these components don't issue such brackets.

The language tests pass because they have been massaged to accommodate the current state of the template desugared code. When  the template desugaring code changes, tests will start failing. The fix in that case is to remove `INFO` annotations from the failing tests.

The relevant tests are:
```
Cash.daml
ChoiceSyntaxes.daml
Choice_no_params_template.daml
Choice_superfluous_with.daml
CoerceContractId.daml
Conjunction.daml
ConsumingTests.daml
DisjunctionChoices.daml
Divulgence.daml
ExerciseWithoutActors.daml
ExportList.daml
Iou12.daml
Isomorphism.daml
LetKeys.daml
Newtype.daml
No_concat_clash.daml
Optional.daml
Precondition.daml
Proposal.daml
ProposalDesugared.daml
ProposalIou.daml
QualifiedPrelude.daml
RecordBig.daml
RecordUpdate.daml
Records.daml
RelTimeDetailsHidden1.daml
RightOfUse.daml
ScenearioReturningUpdate.daml
Self.daml
Self2.daml
SerializablePolymorphicContractId.daml
Show.daml
Simple.daml
SubmitterInMaintainers_after_1866.daml
SumProducts.daml
Swappable.daml
Symbol.daml
TemplateHeaders.daml
Transferrable.daml
Unserializable.daml
```

### CODE REVIEW

**Comment by shayne-fletcher-da** [comment]
Also commented out the "scenario error" test case in `daml.git/compiler/lsp-tests/src//Main.hs`.

**Comment by shayne-fletcher-da** [comment]
The problems with `IsomorphismFail.hs` appear to be with the record preprocessor. The difficulty with the test is with the testing framework (there doesn't seem to be a way to ignore the lints regarding parens from the typecheck error). Easiest thing to do is ignore until the record preprocessor is fixed.

**Comment by shayne-fletcher-da** [comment]
AFAICT, the macos failure is not real. I seem to be struggling with a lack of cache invalidation here.

**Comment by cocreature** [comment]
I would suggest to disable the test by default and get this merged and then work separately on fixing the preprocessor and whatever else needs fixing. The MacOS failure does not look like a caching issue to me but I’m not entirely sure what’s going on.

**Comment by shayne-fletcher-da** [comment]
> I would suggest to disable the test by default and get this merged and then work separately on fixing the preprocessor and whatever else needs fixing. The MacOS failure does not look like a caching issue to me but I’m not entirely sure what’s going on.

As always, a voice of reason when I need it most. Thank-you.

**Pull request closed without merging**
