### PR TITLE
Upgrades opentelemetry to 0.16.0

### PR DESCRIPTION
**Pull request by lucb-da**
opentelemetry `0.8.0` is [not compatible](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1839) with io.grpc >= `1.33.0` (upgraded in #8558).
Upgrading to opentelemetry `0.16.0`.

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by cocreature** [comment]
Can we test this? I’d like to avoid breaking it again on the next grpc upgrade.

**Comment by lucb-da** [comment]
It is not simple to test. Without the upgrade, it doesn't break. It just doesn't generate the expected data.
The gRPC support in OpenTelemetry relies on instrumentation. The instrumented code changed in such a way that the instrumentation was not active anymore.

It would be an integration test. Start one of the component with OpenTelemetry instrumentation enable, make a gRPC call, check that the traces looks right (the trace data can be sent to the log).

**Comment by cocreature** [comment]
Fair enough, I’ll leave it up to you whether that is worth the effort.

**Review by cocreature — APPROVED** [review]
lgtm, thanks! See discussion for whether we should test this.

Needs rebasing and you also need to repin the json file for Scala 2.13.

**Comment by lucb-da** [comment]
@fabiotudone-da Yes, I have run the changes multiple times in LR benchmarks.

The manually added spans are still there (they were not broken).
image

And the automatic gRPC spans are back.
image

**Comment by lucb-da** [comment]
Rebased on `main`, and updated the `maven_install*` files.

**Comment by fabiotudone-da** [comment]
@lucb-da I think the build wasn't run automatically because the PR is from a fork; it looks like you need some reformatting through `./fmt.sh`.

**Comment by lucb-da** [comment]
Added changelog section, and squashed the commits.

Need a new run to be triggered.

**Pull request merged**
