### PR TITLE
Release 1.18.2 RC

### PR DESCRIPTION
**Pull request by tudor-da**
changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by tudor-da** [comment]
@garyverhaegen-da The builds fail with ` ERROR  Invalid extension version '1.18.2-snapshot.20220324.8439.0.00297192'`
Do you know why this might be happening?

**Comment by garyverhaegen-da** [comment]
> 

No, that doesn't ring a bell. "Extension" would point to VSCode; it'd be really annoying if they'd changed their rules re: valid version numbers.

**Comment by garyverhaegen-da** [comment]
Ok I think I know what's going on, but it's going to be a bit annoying to fix.

The problem is that segments in semver can be either numeric or alphanumeric. In this case, the last segment of our version string is `00297192`; that's a commit hash so in principle it's alphanumeric, but it happens to be composed of only numbers, so it's parsed as numeric, and (apparently) numeric fields can't start with leading zeroes.

So... We need another commit. 😿

**Review by garyverhaegen-da — APPROVED** [review]
Thanks!

**Review by mziolekda — APPROVED** [review]

**Comment by tudor-da** [comment]
Manual tests passed on Windows.

**Comment by tudor-da** [comment]
Manual tests passed on macOS.

**Pull request merged**
