### PR TITLE
Backport of "Ensure lookupMaximumLedgerTime contention failures are propagated normally" to release/1.14.x

### PR DESCRIPTION
**Pull request by tudor-da**
This PR is a backport of https://github.com/digital-asset/daml/pull/10211 to release/1.14.x

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by cocreature** [comment]
why are we backporting this now? I wasn’t aware of plans for a 1.14.3?

**Comment by tudor-da** [comment]
> why are we backporting this now? I wasn’t aware of plans for a 1.14.3?

There are no plans for 1.14.3 afaik and this backport does not affect the current users of 1.14 so it doesn't warrant another release. Nevertheless, we've decided (with @mziolekda ) to add it here in case a new release is coming, since it affects a major feature introduced in this release (the mutable contract state cache).

**Comment by cocreature** [comment]
Makes sense

**Review by cocreature — APPROVED** [review]

**Review by mziolekda — APPROVED** [review]
Thanks for the propagation!

**Pull request merged**
