### PR TITLE
Release 1.3.0-snapshot.20200610.4412.0.0544323d

### PR DESCRIPTION
**Pull request by rohanjr**
changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by rohanjr** [comment]
Manual tests passed on macOS.

**Comment by rohanjr** [comment]
Found an issue with DAML Script initialization on Windows. This release is on hold while we investigate.

**Comment by rohanjr** [comment]
Issues above due to an incorrect java installation. Not reproducible with a correct setup.

**Comment by rohanjr** [comment]
Manual tests passed on Windows.

**Comment by hurryabit** [comment]
Thanks for cutting the release.

**Pull request merged**
