### PR TITLE
update all references of old repo to new repo

### PR DESCRIPTION
**Pull request by francesco-da**

### CODE REVIEW

**Comment by francesco-da** [comment]
@neil-da actually, many / most of the issues redirect just fine. in any case, i'll double check each link.

**Comment by francesco-da** [comment]
@neil-da i've updated all the issue links -- please review again.

**Comment by gerolf-da** [comment]
@francesco-da: was 42008a0d565f068f420259eb674e62800bda479b supposed to make it into this PR?

**Comment by francesco-da** [comment]
@gerolf-da no, thanks for catching this.

**Pull request merged**
