### PR TITLE
Speedy Profiler: add labels for new SDefinitionRef

### PR DESCRIPTION
**Pull request by remyhaemmerle-da**
With this PR, the profiler nicely handles the new `SDefinitionRef`'s added in #7472.

We add labels for:
* 'create'
* 'exerciseByKey' 
* 'fetch'
* 'fetchByKey'
* 'lookupByKey'

CHANGELOG_BEGIN
CHANGELOG_END

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by S11001001** [comment]
Are you adding any points of use to match, or are those meant to be separate?

**Comment by remyhaemmerle-da** [comment]
> Are you adding any points of use to match, or are those meant to be separate?

It is indeed missing. 
Is the the fxes for `topLevelFunction` method enought ?

**Review by S11001001 — APPROVED** [review]
> It is indeed missing.
> Is the the fexe for topLevelFunction method I just pushed enough ?

Looks good to me.

**Review by nickchapman-da — APPROVED** [review]
Nice. I can see all the labels are used now.
Thanks!

**Review by hurryabit — COMMENTED** [review]
Good catch. Thank you.

**Pull request merged**
