### PR TITLE
Fix: make use of unused my_text in docs example

### PR DESCRIPTION
**Pull request by richardkapolnai-da**
### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags, if appropriate
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by hurryabit** [comment]
@bame-da, you wrote this. Is this the right fix for the problem?

**Comment by bame-da** [comment]
No, the point here is to show literals for the different types. The better fix would be to write an assert about it further down.

**Comment by bame-da** [comment]
Why does this need fixing? Because it generates lint warnings?

**Comment by richardkapolnai-da** [comment]
> better fix would be to write an assert about it further down.
Thanks, I made a new attempt.

> Why does this need fixing? Because it generates lint warnings?
Yes.

**Pull request merged**
