### PR TITLE
Bump rules_haskell

### PR DESCRIPTION
**Pull request by cocreature**
The c2hs Windows patches and the include dir patches have been merged
upstream so we can remove them.

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/unreleased.rst), if appropriate
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by cocreature** [comment]
Not sure why this breaks `axe` on Windows. I’ll take a look.

**Comment by cocreature** [comment]
@aherrmann-da I’m a bit lost, I am unable to reproduce the failure even after a `bazel clean --expunge` on my local machine. Any ideas where I’ve screwed up?

**Comment by cocreature** [comment]
@aherrmann-da I am not sure what I actually changed (I first added expunge which didn’t help, then built alex alone which worked, then removed alex which still worked, then removed expunge and it still works :woman_shrugging:) but it seems to pass now. Would be great if you could take a look.

**Comment by aherrmann-da** [comment]
I've merged the Bazel update meanwhile, maybe that is related. Or, maybe this was due to invalid worker state. The changes all look good to me.

**Pull request merged**
