### PR TITLE
macos: move cache setup to step 2

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
The caches really need to be set up before we warm them up.

CHANGELOG_BEGIN
CHANGELOG_END

### CODE REVIEW

**Comment by garyverhaegen-da** [comment]
Tested, seems to work. I'll wait until it's approved to deploy.

**Review by cocreature — APPROVED** [review]
lgtm, thanks!

**Comment by garyverhaegen-da** [comment]
Alright, deploying now then.

**Comment by garyverhaegen-da** [comment]
Deployed.

**Pull request merged**
