### PR TITLE
language-support/scala: Remove unused docs.

### PR DESCRIPTION
**Pull request by SamirTalwar-DA**
We seem to have some old, out-of-date documentation lying around. Let's remove it.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by bame-da** [comment]
I'll defer to @leo-da and @S11001001 on this. Since these docs are (sadly) not part of our public docs, I don't mind removing them from the repo.

**Comment by SamirTalwar-DA** [comment]
If there's pertinent information we don't have elsewhere in the docs, I'm happy to move it, but I think pretty much all of it is outdated and covered elsewhere. Happy to be shown where I'm wrong.

**Comment by cocreature** [comment]
Not sure how outdated it is but afaik we don’t have a description of what the scala codegen generates anywhere else.

**Comment by leo-da** [comment]
> Not sure how outdated it is but afaik we don’t have a description of what the scala codegen generates anywhere else.

We might just move this section from this doc into the new up-to-date one:
```
What it generates
-----------------

It generates:

1. Objects for contract templates. Each object provides methods for producing
   Create, Exercise and Archive Commands that can be used with the
   Ledger Client API.

2. Objects for user defined type synonyms for records/variants. They allow one
   to construct instances of these DAML values in Scala. These values can be used
   with contract template classes that accept such values as template or choice
   parameters. The generated classes also take care of
   serialization/deserialization to/from the ``ArgumentValue`` type used by the
   Ledger Client API.

3. An object called the *event decoder*  which listens to Events returned by the
   Ledger Client API and produces a *contract data* value for the appropriate
   contract template. This value can be used to exercise choices and archive
   the created contract.
```

Everything else is obsolete in here, this doc is referring to `damli`:
```
$ damli export-core Main.daml.daml > Main.daml.sdaml
```
this predates the scala codegen that @S11001001  and I worked on.

**Comment by leo-da** [comment]
Please do not merge this PR yet, I will push the change to copy `What it generates` into the new doc.

**Comment by leo-da** [comment]
Actually looking at the current docs: https://docs.daml.com/app-dev/bindings-scala/index.html#introduction

I think the following explanation of what scala codegen generates is sufficient. There is no reason to go into details.
```
The generated Scala code provides a type safe way of creating contracts (:ref:`com.daml.ledger.api.v1.CreateCommand`) and exercising contract choices (:ref:`com.daml.ledger.api.v1.ExerciseCommand`).
```

@S11001001 what do you think?

**Comment by SamirTalwar-DA** [comment]
Merging it; the content is here in this PR if you need to move it somewhere.

**Pull request merged**
