### PR TITLE
Remove daml-ghcide submodule accidentally checked-in by #17299

### PR DESCRIPTION
**Pull request by akrmn**
This is causing CI failures for the canton team, https://daholdings.slack.com/archives/C044LUG7CKT/p1692798644565979

### CODE REVIEW

**Review by carlpulley-da — APPROVED** [review]

**Comment by samuel-williams-da** [comment]
Oh shoot! Sorry about this! I didn't even notice D:

**Comment by akrmn** [comment]
> Oh shoot! Sorry about this! I didn't even notice D:

no worries, it happens, and the tiny github diff didn't really help

**Comment by PHOL-DA** [comment]
hey @akrmn it seems this problem has been reintroduced here: https://github.com/digital-asset/daml/pull/17215

is this something that can be fixed permanently?

**Comment by samuel-williams-da** [comment]
Apologies - this is my fault, I had merged a couple PRs before realising this had happened.
It shouldn't happen again - i've checked over all my branches, but we're also looking at gitignoring these files

**Pull request merged**
