### PR TITLE
tweaks to help reproduce and explore https issue

### PR DESCRIPTION
**Pull request by raphael-speyer-da**
Currently the target `//ledger-service/http-json:integration-tests-ce_test_suite_src_it_scala_http_HttpServiceIntegrationTest.scala` fails in the test `"should serve HTTPS requests"`

To run just this one test, avoiding the flake retries, you can
```
bazel run //ledger-service/http-json:integration-tests-ce_test_suite_src_it_scala_http_HttpServiceIntegrationTest.scala -- -z HTTPS
```
We see that it produces and writes the ClientHello 6 times, each 1 minute apart, and there’s never a ServerHello sent back. After 6 attempts it gives up and dies with
```
  akka.stream.scaladsl.TcpIdleTimeoutException: TCP idle-timeout encountered on connection to [localhost:36993], no bytes passed in the last 60 seconds
```
I imagine this is the exception getting thrown every time, and when establishing the connection the client just catches and retries 5 times before rethrowing.

Now to test it manually, we can also start canton locally with
```
bazel run canton:community_app -- -c $(pwd)/canton.conf
```
and then update the paths in `jsonapi.conf` and in another terminal
```
bazel run ledger-service/http-json:http-json-binary -- -c $(pwd)/jsonapi.conf 
```

Then you can try connecting using other tools, such as curl
```
curl -vikI https://127.0.0.1:1235/livez
```
or openssl
```
openssl s_client -connect localhost:1235 -prexit -showcerts -debug -tlsextdebug -state -msg -tls1_2 </dev/null
```
and you get the same behaviour, it just hangs after sending the clienthello.

We do see that the server sees the request and logs 
```
javax.net.ssl|DEBUG|1A|http-json-ledger-api-akka.actor.default-dispatcher-6|2023-11-13 15:46:20.493 AEDT|SunX509KeyManagerImpl.java:392|matching alias: key
```
but gets no further than that.

### CODE REVIEW

**Comment by mziolekda** [comment]
`testssl` doesn't recognize the JSON endpoint as an SSL server:

```
docker run --network host --rm -ti drwetter/testssl.sh localhost:1235

###########################################################
    testssl.sh       3.2rc1 from https://testssl.sh/dev/

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.0.2-bad (1.0.2k-dev)" [~183 ciphers]
 on mziolek-Precision-5540:/home/testssl/bin/openssl.Linux.x86_64
 (built: "Sep  1 14:03:44 2022", platform: "linux-x86_64")


 Start 2023-11-13 17:52:14        -->> 127.0.0.1:1235 (localhost) <<--

 A record via:           /etc/hosts 
 rDNS (127.0.0.1):       --

 127.0.0.1:1235 doesn't seem to be a TLS/SSL enabled server
 The results might look ok but they could be nonsense. Really proceed ? ("yes" to continue) --> y
```

**Comment by mziolekda** [comment]
`OPENSSL` seems to work fine though and the right classes are being loaded, see the commit e7881f23bf8b4e37e1a729e91354f6bf6e12ed12

**Comment by mziolekda** [comment]
testssl works ok on json-api from Oct 26 when started with exactly the same configuration

**Comment by raphael-speyer-da** [comment]
Created a minimal binary to assist reproduction, run

```
bazel run //simple-https:simple
```
and once it's finished starting up, run
```
openssl s_client -connect localhost:1235 -prexit -showcerts -debug -tlsextdebug -state -msg -tls1_2 </dev/null
```
in another terminal and you should see it hanging after sending the client hello.

The only logic copied across was the part that sets up the `HttpsConnectionContext`

**Pull request closed without merging**
