### PR TITLE
Cut a snapshot release for the 1.8.0 special patch

### PR DESCRIPTION
**Pull request by mziolekda**
CHANGELOG_BEGIN
CHANGELOG_END

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by garyverhaegen-da — CHANGES_REQUESTED** [review]
Blocking until #9000 is merged and `release/1.8.x-special-patch` becomes a legitimate target branch to make releases from.

**Review by garyverhaegen-da — COMMENTED** [review]
Updated to #9000.

**Review by cocreature — APPROVED** [review]

**Comment by mziolekda** [comment]
Manual tests passed on Windows.

**Comment by mziolekda** [comment]
Manual tests passed on Linux

**Pull request merged**
