### PR TITLE
Use labeled metrics for the CacheMetrics [PLEN-163][PLEN-167]

### PR DESCRIPTION
**Pull request by nicu-da**
This simplifies the cache metrics.
This removes the need to have @GroupTag for metrics documentation.

<table>
<tr>
	<td>Old metric
	<td>New Metric
<tr>
	<td>daml.{{prefix}}.{{cache_name}}.hits
	<td>daml.cache.hits {name={{cache_name}}}
<tr>
	<td>daml.{{prefix}}.{{cache_name}}.misses
	<td>daml.cache.misses {name={{cache_name}}}
<tr>
	<td>daml.{{prefix}}.{{cache_name}}.evictions
	<td>daml.cache.evictions {name={{cache_name}}}
<tr>
	<td>daml.{{prefix}}.{{cache_name}}.evicted_weight
	<td>daml.cache.evicted_weight {name={{cache_name}}}
<tr>
	<td>daml.{{prefix}}.{{cache_name}}.size
	<td>daml.cache.size {name={{cache_name}}}
<tr>
	<td>daml.{{prefix}}.{{cache_name}}.weight
	<td>daml.cache.weight {name={{cache_name}}}
</table>

### CODE REVIEW

**Review by lucb-da — DISMISSED** [review]
All instances of `CacheMetrics` have to be updated to only specify a name, not a `MetricName` with prefix.
I assume this compiles fine only because there is an implicite conversion from `MetricName` to `String` somewhere.

**Comment by nicu-da** [comment]
> All instances of `CacheMetrics` have to be updated to only specify a name, not a `MetricName` with prefix. I assume this compiles fine only because there is an implicite conversion from `MetricName` to `String` somewhere.

Yes, but that's the intended behavior, as a Metric name outputs nicely to a string

**Review by lucb-da — COMMENTED** [review]
I won't block this PR for it, but it doesn't fell right to me to use the same old names while we are removing constraints.
At the minimum, we should get the different teams to review the names that are used, see if they want to fix some, or get better names.

The names in the cache metrics looks OK, even if `daml` and `cache` in them is likely a waste of space.
But the names in the executor metrics likely can be improved a lot
```
# HELP daml_cache_hits 
# TYPE daml_cache_hits gauge
daml_cache_hits{daml_version="0.0.0",name="daml.execution.cache.contract_state",} 843.0 1677600568376
daml_cache_hits{daml_version="0.0.0",name="daml.execution.cache.key_state",} 422.0 1677600568376
# HELP daml_executor_pool_size Number of worker threads present in the pool.
# TYPE daml_executor_pool_size gauge
daml_executor_pool_size{daml_version="0.0.0",name="daml.lapi.threadpool.api-services",type="fork_join",} 16.0 1677600568376
daml_executor_pool_size{daml_version="0.0.0",name="daml.parallel_indexer.inputmapping.executor",type="thread_pool",} 16.0 1677600568376
daml_executor_pool_size{daml_version="0.0.0",name="daml.lapi.threadpool.in_memory_fan_out",type="fork_join",} 16.0 1677600568376
daml_executor_pool_size{daml_version="0.0.0",name="daml.index.db.threadpool.connection.api-server",type="thread_pool",} 16.0 1677600568376
daml_executor_pool_size{daml_version="0.0.0",name="daml.lapi.threadpool.index_bypass.update_in_memory_state",type="thread_pool",} 1.0 1677600568376
daml_executor_pool_size{daml_version="0.0.0",name="daml.index.db.threadpool.connection.indexer",type="thread_pool",} 17.0 1677600568376
daml_executor_pool_size{daml_version="0.0.0",name="daml.lapi.threadpool.index_bypass.prepare_updates",type="fork_join",} 1.0 1677600568376
daml_executor_pool_size{daml_version="0.0.0",name="daml.parallel_indexer.batching.executor",type="thread_pool",} 4.0 1677600568376
```
(metrics from sandbox-on-x)

**Comment by miklos-da** [comment]
@mziolekda You might want to consider adjusting the labels for these metrics as suggested by @lucb-da.

**Review by miklos-da — APPROVED** [review]
Approving as these are all metrics qualified as internal metrics, hence, we may change them between subsequent releases.

**Pull request merged**
