### PR TITLE
Backport ci changes 1.8.x-special-patch (#8549)

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
This updates the config to match #8374 & the corresponding new Azure setup.

CHANGELOG_BEGIN
CHANGELOG_END

### CODE REVIEW

**Comment by cocreature** [comment]
For comparison, https://github.com/digital-asset/daml/pull/8549 ported the changes back to the actual 1.8.x branch and this is identical.

**Review by cocreature — APPROVED** [review]
Thanks!

**Review by mziolekda — APPROVED** [review]

**Comment by garyverhaegen-da** [comment]
> For comparison, #8549 ported the changes back to the actual 1.8.x branch and this is identical.

Almost — the first commit is indeed a cherry-pick of #8549, but we do need to change the branch name on line 12 of `ci/prs.yml` (second commit) for CI to run.

**Comment by stefanobaghino-da** [comment]
I just wanted to point out that this PR is _exactly_ #9000.

**Comment by garyverhaegen-da** [comment]
> I just wanted to point out that this PR is _exactly_ #9000.

I guess it's fitting then that it ends up being way _over_ what I expected it to be.

**Comment by garyverhaegen-da** [comment]
Note that we have deliberately decided not to update the Bazel version in dev-env depiste the (benign) changes in `ci/patch_bazel_windows`.

**Pull request merged**
