### PR TITLE
incident-118: investigate & fix

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
This first commit just duplicates the existing configuration. Further commits will make actual changes so they can be tracked by looking at individual commits (rather than try to think up the diff by looking at entirely new files).

CHANGELOG_BEGIN
CHANGELOG_END

### CODE REVIEW

**Comment by garyverhaegen-da** [comment]
@cocreature Would you mind approving the following plan?
- deploy c383131268b57daf1aa475bd2fa358558b832075 (NOT the opening commit)
- look at logs
- do other changes and deployments based on what I see there
- explicitly mention here every commit that gets deployed, and keep those commits in the history.

So I don't need to bug you for each individual deploy.

**Review by cocreature — APPROVED** [review]
Approving your plan, thanks for looking into this!

**Comment by garyverhaegen-da** [comment]
I can't reproduce the issue anymore so I'll revert. Plan is to first spin up a new 10-machine cluster with the logging agent, then change the existing one (after draining jobs), then destroy the temp one. (Because changing config kills all machines and thus is disruptive to running jobs.)

**Comment by garyverhaegen-da** [comment]
Deploying a4a3aea5e9a79f3f67603e3de86373959ac0bf18.

**Comment by garyverhaegen-da** [comment]
Temp machines are up and ready to serve jobs, old machines are disabled at the Azure level and all jobs have been drained. Starting transition by deploying aad1d43.

**Comment by garyverhaegen-da** [comment]
Jobs drained; removing temp cluster by deploying 988df3e.

**Comment by garyverhaegen-da** [comment]
@cocreature This is ready to merge. It gets us back to the pre-incident configuration with no change, and I have no clue what went wrong. I'm not enthused by the situation, but it's the best resolution I can get to at the moment.

**Review by cocreature — APPROVED** [review]
Thanks!

**Pull request merged**
