### PR TITLE
Document IDE support for language-support/js

### LINKED ISSUE #67: Integrate with IDEs
The current Bazel build setup prevent the user from getting useful information from IDEs for the Node.js bindings.

We should address this to improve the usability, especially for outside contributors and newcomers to the project.

### PR DESCRIPTION
**Pull request by stefanobaghino-da**
Closes #67

### CODE REVIEW

**Comment by rautenrieth-da** [comment]
Unrelated question: Should the `install.sh` script not also install npm dependencies (e.g., [these ones](https://github.com/digital-asset/daml/blob/da93a86104991ddebdb03415e2834d462a7009ca/language-support/js/daml-grpc/BUILD#L24)) into the local node_modules folder?

**Comment by stefanobaghino-da** [comment]
> I like the `install.sh` script.

I don't. :laughing: But I did it in 10 minutes and it gets the job done, so it's enough for the time being. :wink: But thanks for the appreciation. :slightly_smiling_face: 

> Unrelated question: Should the install.sh script not also install npm dependencies (e.g., these ones) into the local node_modules folder?

In theory it should not be needed: `npm` and `yarn` should recursively look for `node_modules` with the `require`d modules going up the path until the root is reached ([docs](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders)). Since dependencies are managed centrally by Bazel in the WORKSPACE root, all dependencies should be found _sooner or later_. I find this approach to be brittle and error prone, but at the moment that's what we have. :slightly_frowning_face:

**Comment by rautenrieth-da** [comment]
> I don't.

Maybe it can be improved, but I like the idea that users run one script and it sets up everything for local development.

> In theory it should not be needed

Did you test it? I was looking into creating a similar script for Navigator (to have IDEs pick up on bazel generated files and bazel managed dependencies). The centrally managed dependencies are stored outside of the repository, so I would expect the node module resolution to not find them. They would work if bazel installed them to `<repo root>/node_modules`, but they are installed at `<repo root>/<bazel symlink magic>/node_modules`.

**Comment by stefanobaghino-da** [comment]
That's interesting, I used to have a `node_modules` directory in my repo root before leaving. Probably something changed or the switch to `yarn` had this side-effect. I'll double check, thanks for bringing this up.

**Pull request merged**
