### PR TITLE
Add daml.yaml in temp directory during SDK install

### LINKED ISSUE #5720: DAML install fails if /tmp/daml.yaml is not writeable
DAML installer should use a separate temp dir instead to store `/tmp/daml.yaml` .
_Reproduce:_
Alice creates `/tmp/daml.yaml` (e.g. by starting a DAML install and interrupt it). Then Bob cannot do the install DAML until Alice removes the file.
```
$ curl -sSL https://get.daml.com/ | sh
Determining latest SDK version...
Latest SDK version is 1.0.0
Downloading DAML SDK 1.0.0. This may take a while.
######################################################################## 100.0%##O=#  #                                                                      
Extracting SDK release tarball.
daml: daml.yaml is an invalid YAML file
  context: Determining SDK version and path.
  details: 
    path: /tmp/daml.yaml
    internal: YAML exception:
Yaml file not found: /tmp/daml.yaml
FAILED TO INSTALL!
```

### PR DESCRIPTION
**Pull request by sofiafaro-da**
By adding a daml.yaml in the temp directory, we prevent issues that
could arise from a spurious daml.yaml existing in parent directories
(e.g. in /tmp). The daml.yaml contents are not important for the
installation, but if there's an error while reading daml.yaml, the
installation would fail.

This fixes #5720 in a backward-compatible way. I tested the fix manually.
I'm not sure there's an easy way to automate the test.

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by cocreature** [comment]
I’m a bit confused, I thought the right fix here was to stop the daml installer from looking for a `daml.yaml` in the first place? Or is there a good reason why it has to do that during installation.

**Comment by sofiafaro-da** [comment]
> I’m a bit confused, I thought the right fix here was to stop the daml installer from looking for a `daml.yaml` in the first place? Or is there a good reason why it has to do that during installation.

We can also do that, but adding a daml.yaml here will prevent the bad behavior even when installing older versions.

**Comment by cocreature** [comment]
> > 
> 
> We can also do that, but adding a daml.yaml here will prevent the bad behavior even when installing older versions.

True but only if you go via `get.daml.com` so not for windows, not for manual installations on Linux/MacOS and maybe also not during upgrades (not quite sure if they run into this). Given that this has only come up once so there is no particular pressure to hotfix old releases, fixing it in the installer seems like a more robust solution.

**Comment by sofiafaro-da** [comment]
> > We can also do that, but adding a daml.yaml here will prevent the bad behavior even when installing older versions.
> 
> True but only if you go via `get.daml.com` so not for windows, not for manual installations on Linux/MacOS and maybe also not during upgrades (not quite sure if they run into this). Given that this has only come up once so there is no particular pressure to hotfix old releases, fixing it in the installer seems like a more robust solution.

Ok, fair enough, closing.

**Pull request closed without merging**
