### PR TITLE
Include .proto files in ScalaPB source jar

### LINKED ISSUE #7830: Include .proto files in ScalaPB source jar
The `jar` of [ledger-api-scalapb](https://mvnrepository.com/artifact/com.daml/ledger-api-scalapb) should contain the original `.proto` files, which is expected by tooling. See the jar of [proto-google-common-protos](https://repo1.maven.org/maven2/com/google/api/grpc/proto-google-common-protos/2.0.0/) for an example.

[This will allow](https://scalapb.github.io/docs/faq/#how-do-i-generate-scala-code-for-protos-from-another-jar) the `.proto` files to be used by tooling such as `ScalaPB` to customise the compiled bindings, and by [Akka gRPC](https://doc.akka.io/docs/akka-grpc/current/index.html).

### PR DESCRIPTION
**Pull request by iggy-da**
Closes #7830. The `jar` of [ledger-api-scalapb](https://mvnrepository.com/artifact/com.daml/ledger-api-scalapb) should contain the original `.proto` files, which is expected by tooling. See the jar of [proto-google-common-protos](https://repo1.maven.org/maven2/com/google/api/grpc/proto-google-common-protos/2.0.0/) for an example.

[This will allow](https://scalapb.github.io/docs/faq/#how-do-i-generate-scala-code-for-protos-from-another-jar) the `.proto` files to be used by tooling such as `ScalaPB` to customise the compiled bindings, and by [Akka gRPC](https://doc.akka.io/docs/akka-grpc/current/index.html).

### CODE REVIEW

**Comment by SamirTalwar-DA** [comment]
I had no idea this was possible. Thanks!

**Comment by iggy-da** [comment]
Added changelog message + fixed formatting for build

**Review by SamirTalwar-DA — APPROVED** [review]
Tested and it seems to work.

I am not sure how to attach these in IntelliJ, but I expect it's useful regardless.

**Pull request merged**
