### PR TITLE
[infra] revert logging change

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
Reverting #16393 now that Google has fixed things on their side.

### CODE REVIEW

**Comment by garyverhaegen-da** [comment]
Alternatively, we could just delete these lines altogether. I don't think we should keep them commented though.

**Comment by asangeethada** [comment]
The only thing is, if we remove the lines we wont get all of syslogs just the ones from google resources. Are we okay with that ? @nycnewman

**Comment by garyverhaegen-da** [comment]
> The only thing is, if we remove the lines we wont get all of syslogs just the ones from google resources. Are we okay with that ? @nycnewman

I'm fine with keeping them if they're actually useful.

**Review by asangeethada — APPROVED** [review]
Adding back the logging agent until we can define the logs we get without it sounds better.  Thank you!

**Comment by garyverhaegen-da** [comment]
Change applied, nodes seem to be working.

**Pull request merged**
