### PR TITLE
HOTFIX damlc: make ghc-options public, refactor

### PR DESCRIPTION
**Pull request by jberthold-da**
Follow-up on #346 , making the option public and refactoring the code to use a comma-separated list.  

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/docs/source/support/release-notes.rst), if appropriate

### CODE REVIEW

**Comment by jberthold-da** [comment]
When playing with it, I found it counter-intuitive to pass one option at a time, like:
`da run damlc -- compile MyFile.daml --ghc-option -Werror --ghc-option -Wall -ghc-option -fno-warn-unused-imports ...`
Thought if we present this to common users we'd want it to look a bit neat. Happy to revert to the old version otherwise.

**Comment by jberthold-da** [comment]
Agree on the composition, that was better before. Using it more than once must be possible, so I will refactor it again

**Comment by neil-da** [comment]
I would have done `--ghc-option=-Werror --ghc-option=-Wall` which makes it a bit clearer. I worry one day you'll want to pass a ghc option with commas in it...

**Comment by jberthold-da** [comment]
The next iteration allows for this to work:
```
run damlc -- compile File.daml --ghc-option "-Werror -Wmissing-patterns -Wwhatever" --ghc-option -Wall
```

**Comment by neil-da** [comment]
What if you want to pass an argument with spaces to GHC?

**Comment by jberthold-da** [comment]
> What if you want to pass an argument with spaces to GHC?

I usually don't :) The use case is rather limited and I think it will be acceptable that we cannot pass arguments with space.

**Pull request merged**
