### PR TITLE
switch CI nodes from n1-standard-8 to c2-*

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
A while back (#4520), I did a bunch of performance tests when trying to size up the requirements for the hosted macOS nodes we needed to buy. As part of that testing, it looked like `c2-standard-8` nodes were faster (full build down from ~95 to ~75 minutes) and marginally cheaper ($0.4176 vs $0.4280) than the `n1-standard-8` we are currently using.

Then I got distracted, and I forgot to upgrade our existing machines.

CHANGELOG_BEGIN
CHANGELOG_END

### CODE REVIEW

**Comment by SamirTalwar-DA** [comment]
Awesome. I had the same results when running performance tests on Sandbox, so this isn't surprising.

**Comment by garyverhaegen-da** [comment]
`terraform apply` just completed successfully (after fixing a typo), and as expected only touched the Linux and Windows CI nodes. I'll report back in an hour or so when (hopefully) the new nodes are up and running.

**Comment by garyverhaegen-da** [comment]
Node creation is failing because we apparently have a quota of maximum 24 C2 CPUs. At the moment we have 2 Windows nodes and one Linux node starting up. I may have to revert this depending on how long it takes to adjust the quotas.

**Comment by garyverhaegen-da** [comment]
It looks like our quota increase request was small enough to be approved automatically, so nodes should be coming up soon-ish (they say about 15 minutes for the change to take effect).

**Comment by garyverhaegen-da** [comment]
All nodes are now created at the GCP level; some are still booting up, but the ones we do have have run successful jobs (this PR), so it looks like we're in the clear.

**Pull request merged**
