### PR TITLE
Timeout for LedgerIdentityClient

### LINKED ISSUE #14097: Timeout for LedgerIdentityClient
### What is the problem you want to solve?

`DamlLedgerClient.connect()` gets stuck when Daml Ledger API is not responsive.

### What is the solution you would propose?

As the `connect()` method waits for `LedgerIdentityClient.getLedgerIdentity()` to respond, a timeout for that operation would fix the problem.

#14098 fixes it.

### Describe alternatives you've considered

None

### Additional context

This is similar to #10383.

### PR DESCRIPTION
**Pull request by dparmar**
This PR fixes #14097. It adds per request deadline to `LedgerIdentityClient.getLedgerIdentity()` which in turn would be useful to timeout `DamlLedgerClient.connect()` when Daml Ledger API is non responsive.

### CODE REVIEW

**Review by ray-roestenburg-da — APPROVED** [review]

**Comment by dparmar** [comment]
Hi @ray-roestenburg-da , Thanks for approving the PR. However it seems `Some checks haven’t completed yet` status is preventing the branch to be merged. Appreciate your help.

**Pull request merged**
