### PR TITLE
LF: drop buggy/useless check in SBCheckPrecond

### PR DESCRIPTION
**Pull request by remyhaemmerle-da**
Drop strange check introduced in #727.

CHANGELOG_BEGIN
CHANGELOG_END

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by cocreature — APPROVED** [review]
Thanks!
I guess it’s not possible to hit this unless you handwrite your speedy expressions?

**Comment by remyhaemmerle-da** [comment]
> Thanks!
> I guess it’s not possible to hit this unless you handwrite your speedy expressions?

Yes.

**Comment by hurryabit** [comment]
@remyhaemmerle-da Nice catch. Do you remember how this ended up there in the first place? Some left overs from debugging?

**Comment by remyhaemmerle-da** [comment]
I introduced it in #727 together with the built-in SBCheckPrecond`.
I do not remember how this ended up there, and was very perplex when I saw it`this morning.

I will guess it is a left overs from debugging the indices of variables in the speedy stack.

**Pull request merged**
