### PR TITLE
Run blackduck on branch, update key vulnerabilities, revert canton version, run latest blackduck detect

### PR DESCRIPTION
**Pull request by dasormeter**

### CODE REVIEW

**Comment by garyverhaegen-da** [comment]
The existing condition didn't work so I fixed it in https://github.com/digital-asset/daml/pull/17402; I also included your naming changes, though not the other ones as I don't fully understand them.

**Review by garyverhaegen-da — APPROVED** [review]

**Comment by garyverhaegen-da** [comment]
How/why did you update yarn.lock?

**Comment by dasormeter** [comment]
> How/why did you update yarn.lock?

Why do we use yarn rather than npm for the root lock file?

I updated the yarn lock file because there are a number of root vulnerabilities that need to be addressed

Since yarn doesn't have a `yarn audit fix` like npm i applied it with npm and then back-applied to the yarn.lock file

```
npm i --package-lock-only
npm audit fix
rm yarn.lock
yarn import
rm package-lock.json
yarn audit
```

**Comment by dasormeter** [comment]
@garyverhaegen-da i had to revert the canton uptick PR as it seems to be breaking the bazel build

in this run it is failing in 
```
daml/dev-env/bin/bazel cquery --noimplicit_deps kind(j.*import, deps(//...)) --output build
```

but it looks to be failing on all prs based off master at the moment

**Comment by dasormeter** [comment]
Might want to do something like this again but closing for now as various things have moved on since this was originally authored

**Pull request closed without merging**
