### PR TITLE
[Doc] Getting started: use node v16

### PR DESCRIPTION
**Pull request by simonletort-da**
Fixes https://github.com/digital-asset/daml/issues/13062 and https://github.com/digital-asset/daml/issues/14084

create-daml-app works out of the box with node v16, but not v17 nor v18. (see 2 issues listed above)
**I suggest to explicitly advise users to use node v16**.

Screen Shot 2022-09-14 at 6 53 48 PM

CHANGELOG_BEGIN
CHANGELOG_END

### CODE REVIEW

**Comment by bame-da** [comment]
Thanks @simonletort-da . Sound like a good idea. I've asked @ray-roestenburg-da as his team owns the involved libraries and linked issues.

**Review by ray-roestenburg-da — APPROVED** [review]

**Comment by ray-roestenburg-da** [comment]
Thanks @simonletort-da

**Comment by simonletort-da** [comment]
@ray-roestenburg-da what's the process to get this PR merged?

**Comment by ray-roestenburg-da** [comment]
I guess the PRs build is stuck? @garyverhaegen-da maybe knows how to fix this?

**Review by ray-roestenburg-da — APPROVED** [review]

**Comment by garyverhaegen-da** [comment]
PR build is disabled for PRs opened from forks. If you're a DA employee, please don't do that and instead request write access to the repo directly.

**Comment by simonletort-da** [comment]
CHANGELOG_BEGIN
CHANGELOG_END

**Comment by stefanobaghino-da** [comment]
@simonletort-da The changelog entry must be part of the body of your commit message. Details on a well-formatted changelog entry are available on the contribution guidelines.

**Comment by simonletort-da** [comment]
Thanks @stefanobaghino-da. Changelog added to the commit message.

**Comment by stefanobaghino-da** [comment]
Re-activating auto-merge since @ray-roestenburg-da already activated it previously without any functional change to this PR.

**Pull request merged**
