### PR TITLE
Bump sonatype timeout to absurdity

### PR DESCRIPTION
**Pull request by cocreature**
changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by remyhaemmerle-da — APPROVED** [review]

**Review by SamirTalwar-DA — APPROVED** [review]

**Comment by stefanobaghino-da** [comment]
Would the longer feedback loop possibly impact the release?

**Comment by cocreature** [comment]
> Would the longer feedback loop possibly impact the release?

not sure what you mean by that, if sonatype is slow we have to wait longer before the release is out. No way around that afaict.

**Comment by stefanobaghino-da** [comment]
> > Would the longer feedback loop possibly impact the release?
> 
> not sure what you mean by that, if sonatype is slow we have to wait longer before the release is out. No way around that afaict.

It was just meant as a speculative question, I wasn't meaning anything in particular. I was just wondering if we could end up triggering a timeout on CI, or other things, like causing Sonatype to blacklist us for too many requests. Anything that comes to mind.

**Comment by cocreature** [comment]
> > 
> 
> It was just meant as a speculative question, I wasn't meaning anything in particular. I was just wondering if we could end up triggering a timeout on CI, or other things, like causing Sonatype to blacklist us for too many requests. Anything that comes to mind.

our CI jobs have longer timeouts than the 2h here so no issues there. And we have an exponential backoff on the retries so I don’t expect that sonatype will get angry. In fact we probably put less load on their system by having one release run to completion than rerunning a bunch of releases that keep failing.

**Pull request merged**
