### PR TITLE
Use munit for diffs in ledger-api-test-tool

### PR DESCRIPTION
**Pull request by cocreature**
As everyone knows that has worked on the ledger API test tool, diffx
makes compilation very very slow (>150s for TransactionServiceIT).

As some people (myself included) know, trying to get diffx to not be
slow is also a giant nightmare (have fun debugging mutually recursive
implicits derived by Scala macros)

So this PR takes a different approach:

Drop diffx completely and replace it by munit. This leads to slightly
different diffs but I think they’re close enough and importantly munit
involves absolutely no macros for those diffs so compilation takes 5s
for TransactionServiceIT.

changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by cocreature** [comment]
Comparison of diffs:
diffx



munit
Screenshot from 2021-05-20 19-10-57

The main difference I see is that we get false positives on ArraySeq vs vector. Doesn’t seem that bad imho.

**Review by kamil-da — APPROVED** [review]
The speed-up is awesome!

**Review by tudor-da — APPROVED** [review]
Nice one!

**Review by stefanobaghino-da — APPROVED** [review]
Now all we have to do is replace Scalatest with MUnit everywhere. :trollface:

**Pull request merged**
