### PR TITLE
Bump ledger api version to 2.0 [DPP-863]

### PR DESCRIPTION
**Pull request by mziolekda**
We have removed both the reset service and support for the legacy error codes. These are breaking changes, which require a major version bump.
Moreover, our users have an easier job thinking about versions if the  Daml Connect version aligns with the Ledger API version. Therefore we are doing the Ledger API 2.0 version bump as part of the daml 2.0.

CHANGELOG_BEGIN
Ledger API version 2.0
CHANGELOG_END

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by cocreature** [comment]
I’m confused, why?

**Comment by mziolekda** [comment]
Because of this:
https://github.com/digital-asset/daml/issues/12174

**Comment by cocreature** [comment]
But why do we need a new major ledger API version? Afaik we’re not breaking anything in a major way (at least not more than say error codes before or the other relatively minor changes we usually brush under the carpet).

And we don’t have a major vmbc release so a new major ledger API version actually violates our compat guarantees.

**Review by cocreature — APPROVED** [review]

**Comment by stefanobaghino-da** [comment]
For the record, why was #12958 dropped in favor of this? I don't see any answer to @cocreature's questions.

**Comment by adriaanm-da** [comment]
I'd also like to have a clarification on the PR, for future reference.

**Comment by mziolekda** [comment]
Updated the PR description to mention the reasons for major version bump.

**Comment by stefanobaghino-da** [comment]
> Updated the PR description to mention the reasons for major version bump.

Ok, so the main reason seems to be aligning the Ledger API and Daml version. The breaking change point seems to be moot, as there is no answer regarding why a minor bump was also considered valid.

**Pull request merged**
