### PR TITLE
Make Template ID optional in exercise; exercise by key

### PR DESCRIPTION
**Pull request by S11001001**
The exercise endpoint in HTTP JSON API currently requires a template ID, even when a contract ID is provided. In general for contract reference we want to support two forms:

1. contract ID with optional template ID (for sanity checking only, not required to disambiguate), or
2. contract key with _required_ template ID

We should support this for exercise as well as lookup (which already supports it).

Structurally dependent on #3755.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/unreleased.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by hurryabit** [comment]
I'm not convinced that is a good idea. What's the rationale for doing it?

**Comment by S11001001** [comment]
@hurryabit This refers only to the HTTP JSON API; contract ID is sufficient to disambiguate. As a rule we don't require anything we can derive in the HTTP JSON API.

**Comment by hurryabit** [comment]
Can we close this?

**Comment by leo-da** [comment]
> Can we close this?

@hurryabit we want to do this, but it is not our top priority. Current priorities (sorted):
https://github.com/digital-asset/daml/milestone/23
https://github.com/digital-asset/daml/milestone/21

**Comment by S11001001** [comment]
Obsoleted by #4049.

**Pull request closed without merging**
