### PR TITLE
Adapt the compatibility exclusions 

### PR DESCRIPTION
**Pull request by nicu-da**
- Include in the offsets the last snapshot before the completion offset was included in the response

changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by garyverhaegen-da** [comment]
This seems like a good time to test the self-service compat run.

**Comment by nicu-da** [comment]
Compat failures seem to be flakes:

Linux: 
```
FAIL: //:daml-ledger-1.9.0-platform-0.0.0 (see /home/vsts/.cache/bazel/_bazel_vsts/f05a05e8b35f4d681be42d81d8c4ed64/execroot/compatibility/bazel-out/k8-opt/testlogs/daml-ledger-1.9.0-platform-0.0.0/test.log)
INFO: From Testing //:daml-ledger-1.9.0-platform-0.0.0:
==================== Test output for //:daml-ledger-1.9.0-platform-0.0.0:
Deployment
  authentication
    Bearer prefix:    Picked up _JAVA_OPTIONS: -Xss4m -Xms128m -Xmx1g
OK (0.76s)
    no Bearer prefix: OK (0.05s)
  unauthenticated
    fetchTest:        Picked up _JAVA_OPTIONS: -Xss4m -Xms128m -Xmx1g
Failure: Command "CreateProcess {cmdspec = RawCommand "/home/vsts/.cache/bazel/_bazel_vsts/f05a05e8b35f4d681be42d81d8c4ed64/sandbox/linux-sandbox/4338/execroot/compatibility/bazel-out/k8-opt/bin/daml-ledger-1.9.0-platform-0.0.0.runfiles/compatibility/external/daml-sdk-1.9.0/daml" ["ledger","upload-dar","--host","localhost","--port","35023",".daml/dist/proj1-0.0.1.dar","--timeout=120"], cwd = Nothing, env = Nothing, std_in = Inherit, std_out = Inherit, std_err = Inherit, close_fds = False, create_group = False, delegate_ctlc = False, detach_console = False, create_new_console = False, new_session = False, child_group = Nothing, child_user = Nothing, use_process_jobs = False}" exited with ExitFailure 1
stdout: 
Uploading .daml/dist/proj1-0.0.1.dar to localhost:35023
An exception was thrown during the upload-dar command
- GRPCIOBadStatusCode StatusUnimplemented (StatusDetails {unStatusDetails = "Method not found: com.daml.ledger.api.v1.admin.PackageManagementService/UploadDarFile"})
One reason for this to occur is if the size of DAR file being uploaded exceeds the gRPC maximum message size. The default value for this is 4Mb, but it may be increased when the ledger is (re)started. Please check with your ledger operator.



stderr: 


FAIL (1.68s)
      build/upload (1.68s)
        ExitFailure 1

1 out of 3 tests failed (12.00s)
```

Windows:

```
25-11-2021 13:52:36.013 [http-json-ledger-api-akka.actor.default-dispatcher-8] INFO  com.daml.http.WebSocketService - New websocket client has connected, current number of clients:12, context: {instance_uuid: "e5ef292c-7dd1-49cd-ac79-126e4a6f3c34", request_id: "78a4791e-8fd4-4237-ab02-a72b6ff02f6f"} 
FAIL src/index.test.ts (49.822 s)
  ● Console

    console.debug
      Registered template fc20b9eb79564d57d41943ec8500fc79546d7348de730dd69fcf18191b1e190a:User:Message.

      at Object.registerTemplate (../../../../../language-support/ts/daml-types/index.ts:98:13)

    console.debug
      Registered template fc20b9eb79564d57d41943ec8500fc79546d7348de730dd69fcf18191b1e190a:User:User.

      at Object.registerTemplate (../../../../../language-support/ts/daml-types/index.ts:98:13)

  ● error when adding a user that you are already following

    expect(jest.fn()).toHaveBeenCalled()

    Expected number of calls: >= 1
    Received number of calls:    0

      453 |   await follow(page, party2);
      454 |
    > 455 |   expect(dismissError).toHaveBeenCalled();
    Run Puppeteer end-to-end tests                    (65.00s)
      callProcess: C:/users/u/_bazel_u/igiwx5st/external/nodejs_dev_env/nodejs_dev_env/npm.cmd "run" "test" "--ci" "--all" "--scripts-prepend-node-path" (exit 1): failed

1 out of 1 tests failed (125.39s)
```


Will trigger a normal re-run so that the build is green and so we can merge it if everyone agrees with the flakes

**Comment by nicu-da** [comment]
@cocreature @garyverhaegen-da all good to merge this?

**Comment by cocreature** [comment]
merge away

**Comment by nicu-da** [comment]
@cocreature I need an approval for that though ⚓

**Review by cocreature — APPROVED** [review]
Thanks!

**Comment by cocreature** [comment]
> @cocreature I need an approval for that though anchor

apologies my bad

**Comment by nicu-da** [comment]
Thank you!

**Pull request merged**
