### PR TITLE
mark participant-integration-api-tests flaky

### PR DESCRIPTION
**Pull request by S11001001**
As requested by @remyhaemmerle-da. Doing this makes collecting further cases for #7521 even less likely; this is not a problem as long as someone can reproduce when attempting to address this issue.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by cocreature — APPROVED** [review]
:cry:

**Comment by SamirTalwar-DA** [comment]
Just saw this. Is there any chance we could split the flaky test out into a separate suite?

**Comment by S11001001** [comment]
@SamirTalwar-DA I think it should not be marked flaky at all, so think even less that we should make a special effort to ensconce it in a cozy flakiness blanket.

**Comment by stefanobaghino-da** [comment]
https://github.com/digital-asset/daml/pull/8336 will revert this as it should greatly reduce the probability of this flake to come up (ideally down to 0).

**Pull request merged**
