### PR TITLE
Remove older isLoading function calls.

### PR DESCRIPTION
**Pull request by leonidr-da**
changelog_begin
changelog_end

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by hurryabit** [comment]
@leonidr-da Can you please add a
```
CHANGELOG_BEGIN
CHANGELOG_END
```
to you commit message in order to pass the `check_changelog_entry`.

**Comment by hurryabit** [comment]
@robin-da You have a point that the documentation is now insufficient. I'll push another commit to this PR to address it.

**Comment by hurryabit** [comment]
@robin-da Can you please check that it is better now?

**Comment by leonidr-da** [comment]
👍

**Pull request merged**
