### PR TITLE
Simplify #6382

### PR DESCRIPTION
**Pull request by stefanobaghino-da**
Simplify https://github.com/digital-asset/daml/pull/6382

### CODE REVIEW

**Comment by oliverse-da** [comment]
Looks good - running the test locally to ensure it passes.

**Comment by stefanobaghino-da** [comment]
> Looks good - running the test locally to ensure it passes.

I would also recommend making sure that a bug-inducing change will make it fail. :wink:

**Comment by oliverse-da** [comment]
I fixed the test slightly. However I observed that getParties returns an empty result when I run the test:

Adding a dummy transaction locally on each participant makes the parties visible: 03c513ac19e6686a8b1061c559b621cb95a7c186 . Not sure if this an artifact of the test framework or the ledger I was running the test against.

**Comment by stefanobaghino-da** [comment]
Probably the framework. Feel free to merge at will then. :slightly_smiling_face:

**Comment by stefanobaghino-da** [comment]
> Adding a dummy transaction locally on each participant makes the parties visible: [03c513a](https://github.com/digital-asset/daml/commit/03c513ac19e6686a8b1061c559b621cb95a7c186) . Not sure if this an artifact of the test framework or the ledger I was running the test against.

Probably the test framework. Consider we allow to no wait for parties in the tool to make sure that participants that don't make local parties local don't get stuck. :wink:

**Pull request merged**
