### PR TITLE
Block concurrent SDK installations.

### LINKED ISSUE #9612: Guard against concurrent SDK installations
Currently, the assistant will fall over if you try to install the same SDK version in parallel.

The most sensible solution that I see here seems to be to write out a lock file before modifying anything in `~/.daml` and deleting it afterwards.

There are two options I see for what a concurrent invocation can do:
1. Error out with a clean error.
2. Block until the first one is finished.

I think 2 probably leads to a nicer UX. E.g., consider a build system which does parallel `daml build` invocations which end up installing the same SDK version. It doesn’t really make sense to fail a build because of that. Arguably the build system should enforce that the SDK is already installed but we still want to provide a nice UX if users don’t do that.

### PR DESCRIPTION
**Pull request by sofiafaro-da**
Fixes #9612

changelog_begin

- [Daml Assistant] The assistant will now avoid
  installing SDK versions concurrently, waiting
  for the previous installation to finish before
  starting the next installation (if still
  necessary). This fixes a bug where the SDK
  would become corrupted because two
  installations were started concurrently.

changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by cocreature — APPROVED** [review]
Nice work! A test would be great but this looks rather painful to test so perhaps more sensible to not add one.

**Comment by oliverse-da** [comment]
Hi @sofiafaro-da , quick question regarding the "if still necessary" aspect:

> - [Daml Assistant] The assistant will now avoid
>   installing SDK versions concurrently, waiting
>   for the previous installation to finish before
>   starting the next installation (if still
>   necessary). 

On our nightly performance runner server, @matthiasS-da has observed that we may perform multiple downloads. Does that look possible / plausible?

**Comment by sofiafaro-da** [comment]
@oliverse-da Are these multiple installs for the same SDK version? I would expect multiple downloads only if there are different SDK versions being installed, or if an install fails for some reason.

I wouldn't expect multiple *concurrent* downloads ever, unless you're using something other than the daml assistant to start the install (e.g. the get.daml.com script).

**Comment by oliverse-da** [comment]
Thanks @sofiafaro-da - as discussed with @matthiasS-da - if this happens again, we will produce a proper report. He mentioned he had an intermittent internet connection, so retries are a possibilities. I also didn't think they could be parallel, but perhaps serial downloads (e.g. retries).

**Pull request merged**
