### PR TITLE
infra: add some docs / comments

### PR DESCRIPTION
**Pull request by flokli**
### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/docs/source/support/release-notes.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by garyverhaegen-da** [comment]
automerge strategy will not work for external PRs.

**Comment by flokli** [comment]
@garyverhaegen-da, can you approve and manually push the magic button? It's just docs, that are not even rendered, really shouldn't break CI...

**Pull request merged**
