### PR TITLE
es: drop jobs-* indices

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
We are currently ingesting Bazel events in two forms:

In the `events-*` indices, each Bazel event is recorded as a separate ES object, with the corresponding job name as a field that can serve to aggregate all of the events for a given job.

In the `jobs-*` indices, each job is ingested as a single (composite) ES object, with the individual events as elements in a list-type field.

When I set up the cluster, I wasn't sure which one would be more useful, so I included both. We now have a bit more usage experience and it turns out the `events-*` form is the only one we use, so I think we should stop ingesting everything twice and from now on create only the `events-*` ones.

CHANGELOG_BEGIN
CHANGELOG_END

### CODE REVIEW

**Comment by garyverhaegen-da** [comment]
There's no urgency on this — I'd prefer to wait for @aherrmann-da's stamp.

**Review by cocreature — APPROVED** [review]
lgtm but waiting for Andreas sounds good

**Comment by stefanobaghino-da** [comment]
> lgtm but waiting for Andreas sounds good

Andreas will not be available for a couple of weeks.

**Comment by cocreature** [comment]
> Andreas will not be available for a couple of weeks.

sure but @garyverhaegen-da said there is no urgency and he prefers to wait

**Review by stefanobaghino-da — APPROVED** [review]
LGTM 🙇🏻

**Comment by stefanobaghino-da** [comment]
> > Andreas will not be available for a couple of weeks.
> 
> sure but @garyverhaegen-da said there is no urgency and he prefers to wait

Absolutely, I just wanted to point out that feedback from Andreas will need to wait for a couple of weeks. 🙂

**Comment by stefanobaghino-da** [comment]
> LGTM 🙇🏻

No rush in merging this, feel free to wait for Andreas' opinion on this before merging.

**Review by aherrmann-da — APPROVED** [review]
Thank you, LGTM

**Comment by garyverhaegen-da** [comment]
Deployed. All seems to be running fine.

**Pull request merged**
