### PR TITLE
Fix contract lookup endpoint

### PR DESCRIPTION
**Pull request by leo-da**
Fixes: #3755 

### TODO:
- [x] Add find by contract ID integration test
- [x] Add find by contract ID documentation
- [x] Add find by contract key integration test
- [x] Add find by contract key documentation

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags, if appropriate
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by hurryabit** [comment]
What was broken?

**Comment by leo-da** [comment]
1. We did not except POST:
https://github.com/digital-asset/daml/pull/3809/files#diff-9a2bbd4c1840d1c14abcb953d382713bL131-R131
2. We could not handle find by contract ID without a template ID provided.

**Comment by hurryabit** [comment]
I wasn't aware there's a `lookup` endpoint. Could we please get documentation for this?

**Pull request merged**
