### PR TITLE
bump netty

### PR DESCRIPTION
**Pull request by garyverhaegen-da**

### CODE REVIEW

**Comment by moisesackerman-da** [comment]
there's also a maven pin file under `sdk/compatibility/`, we might need to repin that too

**Review by moisesackerman-da — APPROVED** [review]
thank you Gary!

**Comment by garyverhaegen-da** [comment]
> there's also a maven pin file under `sdk/compatibility/`, we might need to repin that too

I was not aware of that, thanks for flagging.

**Comment by moisesackerman-da** [comment]
> I was not aware of that, thanks for flagging.

:bow: 
I tried to update it locally with the same `bazel run @unpinned_maven//:pin` but under the compat dir. However the pin file didn't change and it still contains references to netty `4.1.100.Final`, I'm not sure why.

**Comment by garyverhaegen-da** [comment]
> 🙇 I tried to update it locally with the same `bazel run @unpinned_maven//:pin` but under the compat dir. However the pin file didn't change and it still contains references to netty `4.1.100.Final`, I'm not sure why.

If I change the daml version in `sdk/compatibility/WORKSPACE` and run the `bazel run @unpinned_maven//:pin` command afterwards, it does modify the `sdk/compatibility/maven_install.json` file. So the process is the same and it does work. What's thoroughly unclear to me is what these dependencies here are for and whether they're meant to be in sync with the parent workspace.

**Comment by garyverhaegen-da** [comment]
To clarify the change I meant:
```patch
diff --git a/sdk/compatibility/WORKSPACE b/sdk/compatibility/WORKSPACE
index e258010f52..e568bf2b5a 100644
--- a/sdk/compatibility/WORKSPACE
+++ b/sdk/compatibility/WORKSPACE
@@ -342,7 +342,7 @@ load("@scala_version//:index.bzl", "scala_artifacts", "scala_major_version", "sc
 maven_install(
     name = "maven",
     artifacts = [
-        "com.daml:bindings-akka_2.13:{}".format("2.7.6"),
+        "com.daml:bindings-akka_2.13:{}".format("2.7.9"),
         "com.daml:daml-lf-archive-reader_2.13:{}".format(latest_stable_version),
         "com.daml:daml-lf-transaction_2.13:{}".format(latest_stable_version),
         "com.daml:ledger-api-common_2.13:{}".format(latest_stable_version),
```

**Pull request merged**
