### PR TITLE
participant-integration-api: Drop unused participant_id columns.

### PR DESCRIPTION
**Pull request by SamirTalwar-DA**
We don't use the `participant_id` column in either the `configuration_entries` or `party_entries` tables of the index.

This does not change the participant state API, so ledger integrators should not need to make changes.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by SamirTalwar-DA** [comment]
Who generates the participant ID? Wouldn't this still be a problem if two participants claimed to have the same ID? I don't think we check it anywhere.

**Comment by stefanobaghino-da** [comment]
> Who generates the participant ID? Wouldn't this still be a problem if two participants claimed to have the same ID? I don't think we check it anywhere.

The submission identifier is a unique key on the table.

**Comment by SamirTalwar-DA** [comment]
Yes, and in HEAD it's the tuple of `(submission_id, participant_id)`. My point is that even with the current index, you could still easily have a collision, assuming the participant ID isn't validated anywhere.

Or you could have one participant with a bad random number generator sending submissions with the same ID.

I'm sure we need to figure out what currently happens and what we would like to happen, but I don't think this makes the situation worse.

https://github.com/digital-asset/daml/blob/7ce9748066e01cc4bb26ac1297fe091f435d91e9/ledger/participant-integration-api/src/main/resources/db/migration/postgres/V12__Add_configuration.sql#L35-L38

**Comment by SamirTalwar-DA** [comment]
Gonna hold off on merging this until all three of us can discuss this and make sure it's the right approach.

**Comment by stefanobaghino-da** [comment]
> Gonna hold off on merging this until all three of us can discuss this and make sure it's the right approach.

Wanna set up a meeting?

**Comment by SamirTalwar-DA** [comment]
Seems like all complaints have been rectified offline; hitting merge.

**Pull request merged**
