### PR TITLE
LF: avoid usage of GlobalKey.key in engine error

### PR DESCRIPTION
**Pull request by remyhaemmerle-da**
This will allow to drop the `key: Value[ContractId]` field from
GlobalKey in an upcomming PR.

addition, this is a nice addition for #9974 (no more transaction.Error)

CHANGELOG_BEGIN
CHANGELOG_END

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by cocreature — COMMENTED** [review]
Can you explain how this will work if we actually drop the value from `GlobalKey`/make it optional?
Consider the following scenario:
1. I pass in a `FetchByKey` command to `reinterpret` specifying only the key.
2. Now the engine sends `SResultNeedKey`
3. The ledger gives us `None`
4. We throw `ContractKeyNotFound` but we have no value here.
If we just make the value in `GlobalKey` optional that’s easy. But this seems to go in the opposite direction, you mandate that we have a value when throwing an error and it’s not clear to me how that will work.

**Comment by remyhaemmerle-da** [comment]
> Can you explain how this will work if we actually drop the value from `GlobalKey`/make it optional?
> Consider the following scenario:
> 
>     1. I pass in a `FetchByKey` command to `reinterpret` specifying only the key hash.
> 
>     2. Now the engine sends `SResultNeedKey`
> 
>     3. The ledger gives us `None`
> 
>     4. We throw `ContractKeyNotFound` but we have no value here.
>        If we just make the value in `GlobalKey` optional that’s easy. But this seems to go in the opposite direction, you mandate that we have a value when throwing an error and it’s not clear to me how that will work.

Good idea. 

My plan is to drop the value completely from GlobalKey. This PR shows this can be done without impact on the scenario service. 

Once the value field is drop from the GlobalKey, we could consider (no obligation):
 - adapt reinterpret of "by key" operations using only the hash of the key (but not the value).
 - drop completly the value from the node.  

In those cases I would make the key value "optional" in the Error.  If we  have the value in the error we display it properly (handy for the scenario service), otherwise we just print the hash.

One possibility would be to change the type of the Error as follows:

```
sealed abstract class ContractKey 
case class ContractKeyValue(templateId: Ref.Identifier) extends ContractKey
case class ContractKeyHash(globalKey: GlobalKey) extends ContractKey

case class ContractKeyNotFound(key: ContractKey)
```

**Comment by cocreature** [comment]
I got confused by what our target endstate is and a bit concerned about potential regressions in error messages so I opened https://github.com/digital-asset/daml/issues/10159 to have a discussion. Please take a look if you have some time.

I don’t think that needs to block this PR though, will review tomorrow morning.

**Comment by remyhaemmerle-da** [comment]
We decide to not remove value for Global key.

**Pull request closed without merging**
