### PR TITLE
Add `getContractsData`

### PR DESCRIPTION
**Pull request by tamaskalcza-da**
- [DAML Triggers] added a convenience function `getContractsData`

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [x] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by rohanjr** [comment]
If this is a common pattern I have no problem adding the definition (and am not fussed about the name).

**Comment by hurryabit** [comment]
I'm leaning with @cocreature here and would say that the implementation of `getContractsData` is too simple to warrant its own name, which is also not particularly shorter than its implementation.

**Comment by tamaskalcza-da** [comment]
In general shortness or simpleness of an implementation should not necessarily be a reason to ditch something. For example one could have such an argument against `fst` for example. For me the intent revealing code is more important.

Having said that, given the debate this proposal causes I'm okay to close this.

**Comment by cocreature** [comment]
I’m closing this for now. Thanks for the PR anyway! Happy to reconsider later if this comes up more frequently.

**Pull request closed without merging**
