### PR TITLE
Upgrade to nixpkgs 19.03

### PR DESCRIPTION
**Pull request by cocreature**
### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/docs/source/support/release-notes.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by cocreature** [comment]
Mostly because it’s going to take quite a few iterations to get this to actually work so I don’t want to waste anyones time until it goes through CI.

**Comment by neil-da** [comment]
Any chance we can get a document Upgrading.md in the root that describes how to upgrade Nix? I'm going to want a section on Nix, Bazel, Stackage and a few others in there in the fullness of time.

**Comment by cocreature** [comment]
Sure, I’ll add something. But most of the work comes from having to fix issues arising from the update and these vary significantly from upgrade to upgrade so it’s somewhat hard to capture them in a readme.

**Comment by neil-da** [comment]
Yep, mostly we need to know where to start and any issues that recur a lot. I'm only hoping for a paragraph or two.

**Pull request merged**
