### PR TITLE
Run most tests for ledger-dump

### PR DESCRIPTION
**Pull request by dajmaki**
We exclude the tests that create lots of data.
CommandDeduplicationIT is disabled as kvutils does not yet
have time-based deduplication.

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by SamirTalwar-DA** [comment]
You can just omit the argument entirely, I believe. If you provide no `--include` or `--exclude` arguments, all tests except `ConfigManagementServiceIT` (which you should also exclude, because it can interfere with other tests), `LotsOfPartiesIT`, and `TransactionScaleIT` will run.

I'm not sure why you're excluding `CommandDeduplicationIT`.

**Comment by stefanobaghino-da** [comment]
> You can just omit the argument entirely, I believe. If you provide no `--include` or `--exclude` arguments, all tests except `ConfigManagementServiceIT` (which you should also exclude, because it can interfere with other tests), `LotsOfPartiesIT`, and `TransactionScaleIT` will run.
> 
> I'm not sure why you're excluding `CommandDeduplicationIT`.

Probably the description answers your question.

> CommandDeduplicationIT is disabled as kvutils does not yet
have time-based deduplication.

**Comment by SamirTalwar-DA** [comment]
Note to self: read more.

Then you can probably just get away with `--exclude=CommandDeduplicationIT`, no? 🙂

**Comment by stefanobaghino-da** [comment]
> Note to self: read more.
> 
> Then you can probably just get away with `--exclude=CommandDeduplicationIT`, no?

You're not the only one who misses the description now and then. :wink:

**Pull request merged**
