### PR TITLE
Remove package.json for bourbon package that does not appear to be ne…

### PR DESCRIPTION
**Pull request by dasormeter**
Include yarn lock file based on package.json for Bourbon components within the docs directory so that underlying libraries used can be correctly determined through standard npm commands

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by hurryabit** [comment]
@dasormeter does blackduck have a way to put this file on some sort of blacklist instead?

**Comment by dasormeter** [comment]
if this is still needed let's check in the lock file then (in line with the other node packages) -- blackduck is running the usual npm commands to get dependent libraries and needs the lock file to make sure the libraries are known and are not non-deterministically resolved by evaluating the package.json

blackduck basically needs the `npm ls` command to run smoothly, which in turn needs a lock file to have reliably frozen dependencies.

there is some weirdness with the annotated daml type libraries that prevents this from working with the language-support/ts dirs, so we can handle that separately.

> language-support/ts/codegen/tests/ts
> language-support/ts/daml-types
> language-support/ts/daml-react
> language-support/ts/daml-ledger

**Comment by dasormeter** [comment]
closing, replaced by #5644

**Comment by dasormeter** [comment]
> if this is still needed let's check in the lock file then (in line with the other node packages) -- blackduck is running the usual npm commands to get dependent libraries and needs the lock file to make sure the libraries are known and are not non-deterministically resolved by evaluating the package.json
> 
> blackduck basically needs the `npm ls` command to run smoothly, which in turn needs a lock file to have reliably frozen dependencies.
> 
> there is some weirdness with the annotated daml type libraries that prevents this from working with the language-support/ts dirs, so we can handle that separately.
> 
> > language-support/ts/codegen/tests/ts
> > language-support/ts/daml-types
> > language-support/ts/daml-react
> > language-support/ts/daml-ledger

Separate issue #5643 raised for the language-support/ts related directories

**Pull request closed without merging**
