### PR TITLE
Add dependency proto3-suite for Setup.hs

### PR DESCRIPTION
**Pull request by tmcgilchrist**
The Setup.hs attempts to call out to programs installed by `proto3-suite` to generate code based off the proto files.
There should be a `setup-depends:` on `proto3-suite`.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by jberthold-da — APPROVED** [review]
:+1: thanks!

**Review by cocreature — APPROVED** [review]
looks sensible, thanks!
you’re missing an (empty) changelog entry to get through CI

**Comment by tmcgilchrist** [comment]
Added a noop changelog 🤞🏻

**Comment by garyverhaegen-da** [comment]
You'll probably need to rebase on top of #9920 once it's merged. Apologies for that.

**Pull request merged**
