### PR TITLE
snapshot

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
Do over of #7644, which is not releaseable because of #7651.

CHANGELOG_BEGIN
CHANGELOG_END

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by garyverhaegen-da** [comment]
For a moment there I thought I'd finally found a use for that `.0.` in the version scheme, but this had failed in the `linux` job, not in the `release` job.

**Comment by tudor-da** [comment]
Isn't this a duplicate of https://github.com/digital-asset/daml/pull/7653 or the other way around?

**Comment by garyverhaegen-da** [comment]
Closing in favour of #7653.

**Comment by cocreature** [comment]
apologies, I got the email for this after I had created mine already.

**Comment by garyverhaegen-da** [comment]
> apologies, I got the email for this after I had created mine already.

All good. I'll just cherish the fact that the PR numbers prove I was faster.

**Pull request closed without merging**
