### PR TITLE
disble flaky tests in  canton-conformance-test

### PR DESCRIPTION
**Pull request by remyhaemmerle-da**
CHANGELOG_BEGIN
CHANGELOG_END

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by cocreature — APPROVED** [review]
Thanks, Can you please open an issue for this and link to it from the `flaky` line?

**Comment by remyhaemmerle-da** [comment]
This works around #7316.

**Comment by remyhaemmerle-da** [comment]
cc @oliverse-da

**Comment by oliverse-da** [comment]
Could we instead exclude the two individual `TransactionServiceIT` tests? I can make the change.

**Comment by remyhaemmerle-da** [comment]
> Could we instead exclude the two individual `TransactionServiceIT` tests? I can make the change.

Please go ahead and push on top my branch.

**Comment by oliverse-da** [comment]
> > Could we instead exclude the two individual `TransactionServiceIT` tests? I can make the change.
> 
> Please go ahead and push on top my branch.

Ok, so the two tests that flake are `TransactionServiceIT:TXInvisibleTransactionTreeByEventId` and `TransactionServiceIT:TXFlatTransactionByIdSameAsTransactionStream`, right?

**Review by remyhaemmerle-da — COMMENTED** [review]
changes by @oliverse-da looks good to me.

**Pull request merged**
