### PR TITLE
Check in DAR file for Java codegen test against DAML-LF 1.1

### PR DESCRIPTION
**Pull request by hurryabit**
This is a prerequisite for dropping DAML-LF 1.1 support from the compiler.

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/docs/source/support/release-notes.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

---
This change is [Reviewable](https://reviewable.io/reviews/digital-asset/daml/1406)

### CODE REVIEW

**Comment by bitonic** [comment]
@hurryabit fine by me for now, but this approach does not scale, since git does not handle binary files nicely.

**Comment by ndmitchell** [comment]
Git handles binary files fine as log as there aren't a huge number and they don't change too often. How big is the DAR? How often do we plan to roll LF versions? I suspect we might be fine with this approach.

**Comment by hurryabit** [comment]
Right now the checked in DAR files are about 250 kB. I expect us to release new version of DAML-LF at most every two weeks on average.

**Comment by ndmitchell** [comment]
At 6Mb/year I suggest we ignore this problem for the next 5 years then revisit, by which time git might deal well with such files.

**Pull request merged**
