### PR TITLE
Remove a comment regarding the consuming method of the Choice class

### PR DESCRIPTION
**Pull request by hurryabit**
The comment has been out of date since the new "dictionary sanitization" was
implemented.

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/docs/source/support/release-notes.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

---
This change is [Reviewable](https://reviewable.io/reviews/digital-asset/daml/628)

### CODE REVIEW

**Comment by neil-da** [comment]
Are you sure? Shayne tried removing the lambda, and the thing failed, so it still seems to be necessary.

**Comment by hurryabit** [comment]
I changed it to `consuming = const PreConsuming` and it still worked.

**Comment by neil-da** [comment]
`consuming = preconsuming` would be the ideal definition, and would let us remove a special case in the compiler. If you can't write that we need a comment, if you can write that, we should. Shayne tried that and it failed, but maybe for unrelated reasons?

**Comment by shayne-fletcher-da** [comment]
I did try `consuming = preconsuming` but as mentioned earlier, this gave rise to non-termination in the integration tests.

**Comment by hurryabit** [comment]
@neil-da What special case are you referring to? The one for `$dmconsuming`? We can't remove that one because `$dmconsuming` is defined in a different module.

**Pull request merged**
