### PR TITLE
Add akka slf4j library as dependency of super fat daml-sdk.jar

### PR DESCRIPTION
**Pull request by hurryabit**
### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags, if appropriate
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

---
This change is [Reviewable](https://reviewable.io/reviews/digital-asset/daml/3965)

### CODE REVIEW

**Comment by cocreature** [comment]
To add a bit more context to this: The unused scala dependency checker thingy that we merged recently broke everything in the fat jar. All commands just seem to exit without any errors (you still get some initial startup messages but it doesn’t get to the banner). After some experiments, @hurryabit figured out that adding the SLF4j logger made things work again. I’m admittedly not entirely sure what is going wrong here (I would have expected an error on a missing dependency) and I also don’t understand why the integration tests did not catch this but at least for now this seems to fix this.

**Comment by stefanobaghino-da** [comment]
Have you tried with `logback-classic` instead of `akka-slf4j`? I'm not sure you use Akka in `daml-sdk`.

**Comment by stefanobaghino-da** [comment]
You may have hit [this problem](http://www.slf4j.org/codes.html#noProviders).

**Comment by aherrmann-da** [comment]
Removing instances of `{ std_out = UseHandle devNull }` in the daml-assistant integration tests shows that the sandbox output depends on whether `@maven//:com_typesafe_akka_akka_slf4j_2_12`. So, there's no implicit dependency on this target in the integration tests. I don't understand why the integration tests pass anyway.

**Comment by aherrmann-da** [comment]
@stefanobaghino-da `@maven//:ch_qos_logback_logback_classic` is in the `runtime_deps` of the SDK. Is something else needed as well?

**Comment by stefanobaghino-da** [comment]
Mh, ok, thanks for the detailed reply, I'm quite surprised.

**Pull request merged**
