### PR TITLE
Makes Struct lookup O(1)

### PR DESCRIPTION
**Pull request by nmarton-da**
Motivation: visualvm sampling of speedy interpreter execution

CHANGELOG_BEGIN
CHANGELOG_END

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by remyhaemmerle-da** [comment]
I don't think we want to improve the efficiency of lookup inside `Struct` at the cost of increasing the memory finger print of the class. This class is used to represent the type of structural record (structural records are not serializable so do not live outside the engine). 

The lookup is not used for the types, so this suggestion will increase unnecessarily the size of the `Package` and `PackageSignature`.
The only place where the lookup will actual improve efficiency is for the projection built-in (i.e. `SBStructProj`). 
I will argue that, if this is an issue it is better to fix it more explicitly (by either compiling the Projection differently or putting directly the `index` map insid `SValueStruct`).

An intermediary solution would be to make the `index` map a lazy value, but I don't really like this solution neither, because it make more difficult to control/predict memory finger print of the object. 

If we decide to not go for @nmarton-da suggestion, we probably should: 
* add a comment with the considerations I exposed here.
* remove the lookup methods from `Strut` to make the user aware of the linear cost.  

@hurryabit @nickchapman-da What do you think ?

**Review by hurryabit — CHANGES_REQUESTED** [review]
IIRC, we have enough information in the DAML-LF type checker to annotate every `EStructProj` with the index of the field (this is only true since we started sorting the fields). This will make things even faster. I once started looking into this but couldn't finish it because the fields were not yet sorted. It should be a quite small change, I'll pick it up either this afternoon or on Monday.

**Comment by remyhaemmerle-da** [comment]
> IIRC, we have enough information in the DAML-LF type checker to annotate every `EStructProj` with the index of the field (this is only true since we started sorting the fields).

@nmarton-da makes me remark that `EStructUdp` is also concerned.

**Comment by nmarton-da** [comment]
> I don't think we want to improve the efficiency of lookup inside `Struct` at the cost of increasing the memory finger print of the class. This class is used to represent the type of structural record (structural records are not serializable so do not live outside the engine).
> 
> The lookup is not used for the types, so this suggestion will increase unnecessarily the size of the `Package` and `PackageSignature`.
> The only place where the lookup will actual improve efficiency is for the projection built-in (i.e. `SBStructProj`).
> I will argue that, if this is an issue it is better to fix it more explicitly (by either compiling the Projection differently or putting directly the `index` map insid `SValueStruct`).
> 
> An intermediary solution would be to make the `index` map a lazy value, but I don't really like this solution neither, because it make more difficult to control/predict memory finger print of the object.
agreed, also please note lazy is threadsafe -> slower
> 
> If we decide to not go for @nmarton-da suggestion, we probably should:
> 
>     * add a comment with the considerations I exposed here.
> 
>     * remove the lookup methods from `Strut` to make the user aware of the linear cost.
> 
> 
> @hurryabit @nickchapman-da What do you think ?

**Comment by hurryabit** [comment]
We can do the same for `EStructUpd` although no benchmark could have detected any issues with that since we never emit `ESstructUpd` from the compiler.

**Comment by nmarton-da** [comment]
> IIRC, we have enough information in the DAML-LF type checker to annotate every `EStructProj` with the index of the field (this is only true since we started sorting the fields). This will make things even faster. I once started looking into this but couldn't finish it because the fields were not yet sorted. It should be a quite small change, I'll pick it up either this afternoon or on Monday.

Watch out how many identical Maps you will end up instanciating! Not sure about cardinality, but I guess from the Struct we have one, but from `EStructProj` and `EStructUpd` we could have many

**Comment by remyhaemmerle-da** [comment]
The performance issue should be fixed by #7740 and #7742.

**Comment by nmarton-da** [comment]
> The performance issue should be fixed by #7740 and #7742.

splendid! closing this one

**Pull request closed without merging**
