### PR TITLE
Port LedgerConfigurationServiceIT

### LINKED ISSUE #2853: Port LedgerConfigurationServiceIT to the Ledger API Test Tool
Port `LedgerConfigurationServiceIT` to the Ledger API Test Tool.

### LINKED ISSUE #2858: Port SemanticLedgerConfigurationIT to the Ledger API Test Tool
Port `SemanticLedgerConfigurationIT` to the Ledger API Test Tool.

### PR DESCRIPTION
**Pull request by stefanobaghino-da**
Fixes #2853
Fixes #2858

Port tests to the possible extent (the other one is an actual integration test for the sandbox).

Simplifies a bit the helpers to retrieve the configuration from a participant.

Both LedgerConfigurationIT and SemanticLedgerConfigurationIT have been ported to a single test suite (I don't see that much sense in keeping them separated).

I've also introduced a new helper to submit commands without waiting, to be used when we just want to validate submission (as it is the case when dealing with ledger configuration parameters).

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/unreleased.rst), if appropriate
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by stefanobaghino-da** [comment]
Since I have a bit more time to go I'll try to see if I can fit #2858 into this PR.

**Comment by stefanobaghino-da** [comment]
The first tests commands with a simulated skew (both LET and MRT are shifted, making sure the skew is greater than the limits returned by the ledger configuration service), the latter simulates that an unskewed command is accepted if it abides by the boundaries as returned by the `LedgerConfigurationService` (the MRT is adjusted to test the returned boundaries). The latter was originally split into `LedgerConfigurationServiceIT` and `SemanticLedgerConfigurationServiceIT` but I felt the split to be a bit factitious.

I can put them together in a single file if you think it makes sense. Should I?

**Comment by gerolf-da** [comment]
Considering that both "new" tests seem to test the behavior of the command service related to LET and skew, I think it could make sense to put them all in one test suite.

**Comment by stefanobaghino-da** [comment]
@gerolf-da The latest commits should have addressed your point.

**Pull request merged**
