### PR TITLE
Update rules_jvm_external to 4.4.2

### PR DESCRIPTION
**Pull request by gerolf-da**
rules_jvm_external 4.0 introduced the @maven//:outdated command, which checks the dependencies for newer versions. This can help us keep the dependency versions up-to-date.

CHANGELOG_BEGIN
CHANGELOG_END

### CODE REVIEW

**Review by garyverhaegen-da — APPROVED** [review]
Thanks!

Do you have any plan to follow-up with something that actually uses that new command? Some sort of cron job, an update to the BAZEL-JVM.md file, something else?

**Comment by gerolf-da** [comment]
I don't know about a cron job. As a first step, I'm mostly glad that this functionality already exists and that it's quite straightforward to make it available internally.

**Comment by garyverhaegen-da** [comment]
> I don't know about a cron job. As a first step, I'm mostly glad that this functionality already exists and that it's quite straightforward to make it available internally.

Fair enough, I was just wondering.

**Comment by gerolf-da** [comment]
I did add a small section to BAZEL-JVM.md already in this PR though.

**Comment by garyverhaegen-da** [comment]
Nice, thanks!

**Pull request merged**
