### PR TITLE
Fix resource cleanup in CommonStorageBackend.ledgerEnd

### PR DESCRIPTION
**Pull request by cocreature**
Got flagged by VeraCode (I think, it really doesn’t want to tell you
what exactly it doesn’t like).

If we throw in fetch we will never cleanup.

changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by nmarton-da** [comment]
this part of code is under construction by @rautenrieth-da at DPP-460, where we most likely will switch to anorm as in other places (renders this change unnecessary)
if you do not need this urgently I would suggest to close this and wait.
if you need this to activate some additional CI validation, and this is in the way, please feel free to proceed.

**Comment by cocreature** [comment]
>  if you need this to activate some additional CI validation, and this is in the way, please feel free to proceed.

We (or rather Ed) runs VeraCode once a month on our code and this was one thing it flagged this time. Given that we already have this PR and it shouldn’t make it harder to do the changes you want to do, my preference would be to merge it but your/your team’s choice. I can deal with the false positive for now as well.

**Comment by rautenrieth-da** [comment]
Fixed by https://github.com/digital-asset/daml/pull/10472, which used anorm instead of the plain Java interfaces.

**Pull request closed without merging**
