### PR TITLE
Fix a few docs redirects

### PR DESCRIPTION
**Pull request by bame-da**
CHANGELOG_BEGIN
CHANGELOG_END

First and foremost fixes a 404 on the `Testing Your Web App` ToC entry.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by bame-da** [comment]
@garyverhaegen-da if it were an option to manually re-render the affected page and overwrite the redirect with it in the S3 bucket, that would be a good workaround for 2.0.0. You have my approval to do so.

**Comment by garyverhaegen-da** [comment]
> @garyverhaegen-da if it were an option to manually re-render the affected page and overwrite the redirect with it in the S3 bucket, that would be a good workaround for 2.0.0. You have my approval to do so.

Thanks! Will get to that as soon as I'm able, though I'm off today so it will be a bit later unfortunately.

**Comment by cocreature** [comment]
> Thanks! Will get to that as soon as I'm able, though I'm off today so it will be a bit later unfortunately.

this can wait until tomorrow

**Review by stefanobaghino-da — APPROVED** [review]

**Comment by garyverhaegen-da** [comment]
All changes manually applied on both `/` and `/2.0.0./`; cache invalidation started.

**Pull request merged**
