### PR TITLE
index parties alongside template IDs on PostgreSQL

### PR DESCRIPTION
**Pull request by S11001001**
There is a template ID index that is used according to `explain` already; the goal here is to incorporate the `signatories`/`observers` intersection check in an index that works alongside the template ID index.

For #11600, #11602.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by S11001001** [comment]
QueryBenchmarkPostgres, `-p batchSize=10 -p extraParties=99 -p extraTemplates=99` (yielding 100k contracts with 0.01% match), silly mode:

```
10  0.042 ± 0.001   s/op
```

merge-base with master (no changes)
```
10  0.001 ±  0.001   s/op
// or batch-size 1000 for 1M contracts
10  0.005 ±  0.001   s/op
```

with just adding the party index, not altering the existing index at all:
```
10  0.037 ± 0.001   s/op
```

**Comment by akshayshirahatti-da** [comment]
so not sure what I am doing wrong but the GIN idx was not being picked up when using multiple columns i.e `(signatories || observers)`. I decided to add a new column `stakeholders` and create a composite GIN index for `(tpid, stakeholders)` this needed us to install the extension of `btree_gin`(unfortunately this needs us to depend on `postgresql-contrib` module). [this commit](https://github.com/digital-asset/daml/commit/0ddb0c11f23f91103a528cd377f451f493e944ae) should have all the relevant changes.

```
# \d contract;
                 Table "public.contract"
     Column     |  Type  | Collation | Nullable | Default 
----------------+--------+-----------+----------+---------
 contract_id    | text   |           | not null | 
 tpid           | bigint |           | not null | 
 key            | jsonb  |           | not null | 
 key_hash       | text   |           |          | 
 payload        | jsonb  |           | not null | 
 signatories    | text[] |           | not null | 
 observers      | text[] |           | not null | 
 stakeholders   | text[] |           | not null | 
 agreement_text | text   |           | not null | 
Indexes:
    "contract_k" PRIMARY KEY, btree (contract_id)
    "ckey_hash_idx" btree (key_hash)
    "contract_stakeholders_idx" gin (tpid, stakeholders)
    "contract_tpid_idx" btree (tpid)
Foreign-key constraints:
    "contract_tpid_fkey" FOREIGN KEY (tpid) REFERENCES template_id(tpid)

# explain select * from contract where (stakeholders &&  Array['Alice']) and tpid=1 ;
                                           QUERY PLAN                                            
-------------------------------------------------------------------------------------------------
 Bitmap Heap Scan on contract  (cost=230.88..283.30 rows=14 width=132)
   Recheck Cond: ((stakeholders && '{Alice}'::text[]) AND (tpid = 1))
   ->  BitmapAnd  (cost=230.88..230.88 rows=14 width=0)
         ->  Bitmap Index Scan on contract_stakeholders_idx  (cost=0.00..17.08 rows=143 width=0)
               Index Cond: (stakeholders && '{Alice}'::text[])
         ->  Bitmap Index Scan on contract_tpid_idx  (cost=0.00..213.54 rows=9767 width=0)
               Index Cond: (tpid = 1)
(7 rows)
```

Ran a test with and without this new index for more sparse party(or party heavy) dataset and I see the below results.

```
$ bazel run //ledger-service/http-json:contractdao-bench -- -f 1 -i 10 -wi 2 -bm avgt "QueryBenchmarkPostgres" -p batchSize=10 -p extraParties=999 -p extraTemplates=9
```

with GIN(tpid, stakeholders)

```
Result "com.daml.http.dbbackend.QueryBenchmarkPostgres.run":
  0.004 ±(99.9%) 0.001 s/op [Average]
  (min, avg, max) = (0.004, 0.004, 0.004), stdev = 0.001
  CI (99.9%): [0.003, 0.004] (assumes normal distribution)


# Run complete. Total time: 00:01:31

Benchmark                   (batchSize)  (extraParties)  (extraTemplates)  Mode  Cnt  Score   Error  Units
QueryBenchmarkPostgres.run           10             999                 9  avgt   10  0.004 ±  0.001   s/op
```

Without GIN(tpid,stakeholders)

```
Result "com.daml.http.dbbackend.QueryBenchmarkPostgres.run":
  0.008 ±(99.9%) 0.001 s/op [Average]
  (min, avg, max) = (0.007, 0.008, 0.009), stdev = 0.001
  CI (99.9%): [0.007, 0.009] (assumes normal distribution)


# Run complete. Total time: 00:01:45

Benchmark                   (batchSize)  (extraParties)  (extraTemplates)  Mode  Cnt  Score   Error  Units
QueryBenchmarkPostgres.run           10             999                 9  avgt   10  0.008 ± 0.001   s/op
```

Again the dataset is massively skewed towards more unique parties but , I just wanted to test the worst case

**Comment by S11001001** [comment]
@akshayshirahatti-da I included that in this PR and retested with batchSize 100, extraTemplates 99, extraParties 99 (1 million contracts):

```
0.041 ± 0.001   s/op    // array[tpid], signatories||observers index
0.004 ± 0.001   s/op    // merge base
0.022 ± 0.001   s/op    // stakeholders column and btree_gin
```

**Comment by S11001001** [comment]
@akshayshirahatti-da I also ran with settings closer to yours, with 100,999,9:

```
0.031 ± 0.001   s/op    // stakeholders column & btree_gin
0.033 ± 0.001   s/op    // merge base
```

It's hard to call this a meaningful improvement. But part of our problem is that we're not seeing any "bad" performance on even tpid-only for selecting 100k out of 1M contracts on these tests. (I'm also still on PG 9.6, who knows how that affects things.)

**Comment by akshayshirahatti-da** [comment]
@S11001001 FWIW my tests were run with postgres 10. Maybe try a larger dataset with more parties and fewer templates. As you noticed as well, we will only see significant improvements with the new index in cases where tpid index returns a large subset of the overall ACS.

**Comment by S11001001** [comment]
@akshayshirahatti-da My dataset in the last message was 1 million contracts with the same ratios as you used, i.e. 100K with the matching template ID.

**Comment by S11001001** [comment]
Single template ID, 1% party frequency, 100k contracts, full request lifecycle with `SyncQueryMegaAcs`:

```
// stakeholder col & btree_gin
> response time 90th percentile                         24 (OK=24     KO=-     )
> response time 95th percentile                         27 (OK=27     KO=-     )
> response time 99th percentile                         39 (OK=39     KO=-     )

// merge-base
> response time 90th percentile                         27 (OK=27     KO=-     )
> response time 95th percentile                         43 (OK=43     KO=-     )
> response time 99th percentile                         68 (OK=68     KO=-     )
```

**Comment by S11001001** [comment]
Same, but with 1% instead of 100% template ID:

```
1%/1% 100k stakeholders merge-base
> response time 90th percentile                         32 (OK=32     KO=-     )
> response time 95th percentile                         43 (OK=43     KO=-     )
> response time 99th percentile                         84 (OK=84     KO=-     )

merge-base
> response time 90th percentile                         25 (OK=25     KO=-     )
> response time 95th percentile                         31 (OK=31     KO=-     )
> response time 99th percentile                         45 (OK=45     KO=-     )
```

**Pull request closed without merging**
