### PR TITLE
Fix potential embarrassing spelling

### PR DESCRIPTION
**Pull request by rexng-da**
CHANGELOG_BEGIN
  [daml-script] Fix documentation spelling
CHANGELOG_END

### CODE REVIEW

**Review by remyhaemmerle-da — APPROVED** [review]
Thanks.

**Comment by remyhaemmerle-da** [comment]
The `CHANGELOG_BEGIN/CHANGELOGE_END` entry needs to be the message of one of the commits (I added it). 
In this case we do not need to track this kind of change, so a empty entry is better.

**Comment by rexng-da** [comment]
> The `CHANGELOG_BEGIN/CHANGELOGE_END` entry needs to be the message of one of the commits. I added it.

Thank you @remyhaemmerle-da

**Comment by remyhaemmerle-da** [comment]
Not sure @cocreature will feel very embarrassed.

**Pull request merged**
