### PR TITLE
Remove unused functionality

### PR DESCRIPTION
**Pull request by skisel-da**

### CODE REVIEW

**Comment by tudor-da** [comment]
Please run a full-compat in the CI for this

**Comment by tudor-da** [comment]
Please run a full-compat in the CI for this

**Review by rautenrieth-da — COMMENTED** [review]
Based on offline discussions, this is my understanding:

This PR changes the semantics of the dynamic ledger ID mode, and removes the writing of the port file.

This is safe because the dynamic ledger ID mode can only be enabled through the sandbox classic CLI, which is about to be removed in subsequent PRs. Similarly, the port file is not part of the SoX interface.

Interestingly, we have no tests that cover the semantics of `LedgerIdMode.Dynamic` (where it reuses the existing ledger id).

I think it's easier to remove the whole sandbox classic in one PR, together with the `LedgerIdMode` thing.

**Comment by skisel-da** [comment]
I will close this PR and reopen another one when we are ready to fully remove sandbox-classic

**Pull request closed without merging**
