### PR TITLE
Address NPM security vulnerabilities

### LINKED ISSUE #1479: Resolve node security vulnerabilities for DAML repo
image

image

image

### PR DESCRIPTION
**Pull request by dasormeter**
Resolve #1479 by updating lock files and updating or removing usage of problematic `fstream` and `remarkable` versions

@rautenrieth-da @stefanobaghino-da  i noticed that the root yarn.lock file seems to be well out of date so i regen'd via `yarn install` on this PR, which made the two problematic libraries go away for the root yarn.lock file. 

For the specific navigator frontend project, I had to tick the `modernizr` lib to get rid of remarkable and had to force fstream version with a `resolutions` override.

however, should it not be that all dependencies of any package.json anywhere in the daml repo should be represented in the parent package.json file?

@bame-da @bethaitman : do we even need `docs/theme/bower_components_static/bourbon/package.json`  anymore i included generation of a dummy lock file for this as the package.json is in source and this is the only file that didn't have a lock file previously

### CODE REVIEW

**Comment by stefanobaghino-da** [comment]
Mh, the lock file not being updated is probably due to how Bazel interacts with Yarn, I suppose. Or maybe we're skipping some necessary step to keep it up to date? In the normal workflow, any manipulation of dependencies via the package manager should update the lock file.

**Comment by bethaitman** [comment]
I don't see what would have changed to mean that we no longer need that in the docs theme, but I don't know it well - @bame-da may know better.

**Comment by stefanobaghino-da** [comment]
Now that I give this a better read, I don't think you should ever user `yarn` directly, but rather go through the one managed by `bazel`.

**Comment by dasormeter** [comment]
@stefanobaghino-da How do you invoke the yarn managed by bazel?  is there only one global, all-inclusive set of dependencies?  Does this source from package.json or a separate definition of node dependencies?  is there a lock file equiv that can be generated from bazel?

**Comment by stefanobaghino-da** [comment]
Running the installation manually is covered [here](https://github.com/bazelbuild/rules_nodejs#using-self-managed-dependencies). However, this would follow the "self-managed dependencies" workflow, which I'm fairly sure this repository does not use. What is used instead is the "Bazel-managed dependencies" workflow (described [here](https://github.com/bazelbuild/rules_nodejs#using-bazel-managed-dependencies)).

I'm not entirely sure of the reliability of the lock file in this latter scenario, so it may be that running `npm audit` actually has no meaning in this setting. Not as is, at least.

@majcherm-da worked on transitioning to Yarn, probably he has a better understanding of the situation. He may have a better understanding of what would be the rights steps to follow to ensure a meaningful audit run on the repo.

**Comment by rautenrieth-da** [comment]
> i noticed that the root yarn.lock file seems to be well out of date so i regen'd via yarn install on this PR, which made the two problematic libraries go away for the root yarn.lock file.

The root `package.json` and `yarn.lock` files are not related to any of our NPM projects, right? The description reads `package for bazel-managed nodejs dependencies`, and it only contains some general dev dependencies.

There are multiple `yarn_install` entries in the WORKSPACE, and as far as I can see, no Bazel target in our repository depends on `@npm` (the root package.json/yarn.lock files).

```
yarn_install(
    name = "npm",
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
)
yarn_install(
    name = "navigator_frontend_deps",
    package_json = "//navigator/frontend:package.json",
    yarn_lock = "//navigator/frontend:yarn.lock",
)
```

Maybe we can even delete the root package?

> Now that I give this a better read, I don't think you should ever user yarn directly, but rather go through the one managed by bazel.

You mean we should run `bazel run @nodejs//:yarn` instead of plain `yarn`? The only difference would be that we are guaranteed to use a yarn version that is compatible with the `yarn_install` workspace step, right?

**Comment by dasormeter** [comment]
replaced by #1872 and #1874

**Pull request closed without merging**
