### PR TITLE
Backport fixes for read-set generation for 1.6.x [KVL-774]

### PR DESCRIPTION
**Pull request by miklos-da**
Summary of backported PRs:
- [x] #8052 
- [x] #8082 
- [x] #8146 
- [x] #8180 
- [x] #8194 

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by SamirTalwar-DA** [comment]
If it's easy, can you also backport #8203 and #8204? This will give us some more confidence around the fixes.

**Comment by miklos-da** [comment]
> If it's easy, can you also backport #8203 and #8204? This will give us some more confidence around the fixes.

If you backport the contract code for `SimplePackage` then I'm happy to do that.

**Review by SamirTalwar-DA — APPROVED** [review]
:shipit:

**Review by fabiotudone-da — APPROVED** [review]

**Comment by gerolf-da** [comment]
@miklos-da: It's too late now, but these changes would've needed some actual text in the changelog markers. This is used to produce the release notes.

**Comment by miklos-da** [comment]
> @miklos-da: It's too late now, but these changes would've needed some actual text in the changelog markers. This is used to produce the release notes.

Good point.

**Comment by garyverhaegen-da** [comment]
Note that release notes are compiled by a human (usually @bame-da) based on reading the changelog, so there's always a chance to correct these kinds of issues by coordinating with them.

**Pull request merged**
