### PR TITLE
Update protobuf docs template to handle oneOf

### PR DESCRIPTION
**Pull request by cocreature**
Builds upon #1180 to render the oneof fields a bit nicer.

Note that we also need to kill newlines in the descriptions. That’s
not an issue in the plugin but in how rst renders tables.

See https://github.com/digital-asset/daml/issues/11761 for the old rendering.

New rendering:
Screenshot 2021-11-25 at 19-46-29 Ledger API Reference — Daml SDK 0 0 0 documentation

I roughly followed how this is handled in the example in the plugin https://github.com/pseudomuto/protoc-gen-doc/blob/2dde01902b28e8b2201d935467bc4308ec912255/examples/templates/grpc-md.tmpl#L49. if someone has a better idea, I’m happy to change it.

changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by cocreature** [comment]
@carrielaben-da any suggestions for rendering this in a nicer way?

**Comment by andreaslochbihler-da** [comment]
In your screenshot, the documentation of the one-of block itself still seems missing: https://github.com/digital-asset/daml/blob/main/ledger-api/grpc-definitions/com/daml/ledger/api/v1/commands.proto#L60-L62

**Comment by cocreature** [comment]
> In your screenshot, the documentation of the one-of block itself still seems missing: https://github.com/digital-asset/daml/blob/main/ledger-api/grpc-definitions/com/daml/ledger/api/v1/commands.proto#L60-L62 Do we have to move those comments to the individual fields or are they shown somewhere else?

as far as I can tell we don’t get access to that. We only get an annotation on a field that it’s part of a oneof but nothing about the surrounding oneof itself.

**Comment by cocreature** [comment]
In other words, yes I believe we have to move documentation to individual fields.

**Comment by meiersi-da** [comment]
Thanks @cocreature . That's a good improvement. :+1:

**Review by gerolf-da — APPROVED** [review]
Thank you, @cocreature!

**Pull request merged**
