### PR TITLE
remove MissingH

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
I noticed all uses of this library had been removed by #3943, but the library itself wasn't.

### CODE REVIEW

**Comment by cocreature** [comment]
Actually should those files not also include transitive dependencies? I’m not sure if we still transitively depend on `MissingH`.

**Comment by garyverhaegen-da** [comment]
They should indeed include transitive dependencies. I thought Bazel would not let us have implicit transitive dependencies, but I suppose we're bypassing that through Stack here?

**Comment by garyverhaegen-da** [comment]
Re: auto-generating those files, I totally agree. Any idea how they were first generated?

**Comment by cocreature** [comment]
I think @dasormeter might have done that but I’m not sure.

Regarding the transitive deps from hackage, I _think_ all of them have to be listed in `packages` so if removing it from there doesn’t break CI we’re probably fine but I’m not entirely sure. @aherrmann-da Is my understanding here correct?

**Comment by garyverhaegen-da** [comment]
I did some digging and found the original discussion/explanation of how that file was created. I'll spend a bit of time this afternoon looking at whether we can automate it.

**Comment by aherrmann-da** [comment]
The `packages` attribute to `stack_snapshot` lists all *direct* dependencies. But, transitive dependencies don't have to be listed explicitly. You can find all transitive packages with `bazel query @stackage//...`.

**Comment by cocreature** [comment]
@aherrmann-da Thanks! Looks like it’s not in the transitive deps so I’m happy to merge this. We can figure out automation of these files later.

**Comment by garyverhaegen-da** [comment]
Note that that query command doesn't work on macOS; I suspect because of the default case-insensitive filesystem (Bazel trying to read a Bash `build` [script](https://github.com/ndmitchell/hlint/blob/master/cc/build) in `external/stackage/hlint-2.2.5/cc/` as a Bazel package definition). I'm not sure we can do anything about that though.

**Comment by aherrmann-da** [comment]
That sort of issue was the motivation for the `BUILD.bazel` file name, see https://github.com/bazelbuild/bazel/issues/2331. Unfortunately, I'm not aware of a way to enforce that naming (globally, or within a workspace). For this particular query, you can work around the issue by passing `--keep_going`.

**Pull request merged**
