### PR TITLE
fix (some) copyright headers

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
This commit fixes a few copyright headers that have been missed in the
automatic update on Jan 1, as well as the generation code in the compat
workspace so it generates the right headers.

CHANGELOG_BEGIN
CHANGELOG_END

### CODE REVIEW

**Comment by garyverhaegen-da** [comment]
An obvious related task is to review the copyright header update script and investigate why it missed these; I've made a note to do that eventually, but I don't think it's high priority.

**Review by cocreature — APPROVED** [review]
Thanks!

**Review by miklos-da — APPROVED** [review]

**Review by SamirTalwar-DA — APPROVED** [review]
Good catch!

**Pull request merged**
