### PR TITLE
Improve Java codegen decoder docs

### PR DESCRIPTION
**Pull request by stefanobaghino-da**
Also undoes work done as part of #3098. My apologies to @richardkapolnai-da for not recognizing this before. Thanks for the contribution anyhow, it made us aware of a lack of proper documentation for an existing feature. I hope this goes in the right direction.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/unreleased.rst), if appropriate
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by richardkapolnai-da** [comment]
I have difficulties in understanding how these features are related exactly:
- #3097 introduces helper to create `Template` from `CreatedContract`, which is needed by the bots (see [Bot.wire](https://docs.daml.com/app-dev/bindings-java/index.html#writing-automations-bot))
- the generated and documented Decoder creates `Contract` from `CreatedEvent`, which sounds useful, not I don't understand how it could be used from a bot.

Sorry for my lack of education, maybe could you add some hint to the docs how to use it for Bot.wire?

**Comment by stefanobaghino-da** [comment]
Unfortunately I'm not an expert on the whole `Bot` framework. From the little I could understand from the code I saw, it looks like you're using `Template` to get to an handle to an actual contract, which in the codegen would be rather represented as a class extending `Contract` with actual methods that in turn invoke the proper choice on a `Template`. In short I believe you could use the `Decoder` to achieve what you were doing before but you'd have to change your approach to fully use the generated classes.

I'd ask @gerolf-da to step in and verify if I'm not saying anything wrong, as I mentioned I know very very little about bots.

**Comment by gerolf-da** [comment]
@richardkapolnai-da: @stefanobaghino-da is right, and this was a complete oversight on our part in the original pull request. A `CreatedEvent` represents a `Contract`, which contains both a `ContractId` and the data of the contract (i.e. the `Template`). With the template alone you cannot exercise a choice but only produce a `CreateCommand` for creating a contract. Choices can only be exercised on an existing `Contract` with a `ContractId`.

**Comment by stefanobaghino-da** [comment]
Stale, closing, the work done was minimal and can be safely archived and picked up later.

**Pull request closed without merging**
