### PR TITLE
#2326, GHC 8.4 compatibility

### PR DESCRIPTION
**Pull request by ndmitchell**
Fixed it up. After that, hie-core built with GHC 8.4 can compile hie-core.

I also added a message about which GHC you used on startup, since that seems to be a common mistake people are making.

### CODE REVIEW

**Comment by cocreature** [comment]
It would be great if you could also add a `stack.yaml` file for 8.4. That should make it easy to add a CI job to make sure we don’t break this again.

**Comment by cocreature** [comment]
CI is failing due to hlint.

**Comment by ndmitchell** [comment]
Added a stack84.yaml, so now you can successfully run:

```
C:\Neil\daml\compiler\hie-core>stack build --stack-yaml stack84.yaml && stack test --stack-yaml stack84.yaml
```

Also fixed the HLint errors and a warning.

**Comment by cocreature** [comment]
Thanks for the updates! HLint is sadly, still unhappy. I recommend that you run the `fmt.sh` script in the project root to verify things.

**Comment by ndmitchell** [comment]
Fixed HLint (I didn't have it installed on this machine...)

**Comment by ndmitchell** [comment]
```
//ledger/sandbox:sandbox-scala-tests_test_suite_src_test_suite_scala_com_digitalasset_platform_sandbox_ScenarioLoadingITPostgres.scala FAILED in 27.0s
```

Looks like a flake.

**Pull request merged**
