### PR TITLE
Fix the external name of daml3-script.dar to mention 2.dev

### PR DESCRIPTION
**Pull request by paulbrauner-da**
Part of #17366, this one slipped through the cracks.

### CODE REVIEW

**Review by samuel-williams-da — COMMENTED** [review]
I'm happy to merge but I'd like Gary or Remy to actually approve - i'm not familiar enough with this code

**Review by garyverhaegen-da — APPROVED** [review]
LGTM, but is there perhaps a way to make this more likely to be found in the future? Is there another place in the repo we could get this information from rather than hardcoding it here?

**Comment by samuel-williams-da** [comment]
Perhaps we could create a file group as we do with daml2-script, but just containing this dar with the correct name?
Iirc, daml2-script just copies all the files in the file group without rename

**Comment by paulbrauner-da** [comment]
Well, I could extract the lf version from the dar using

```
daml damlc inspect daml3-script-2.dev.dar | grep '^daml-lf' | awk '{print $2}'
```

I don't know how hacky that would be considered.

**Comment by paulbrauner-da** [comment]
Oh, I missed @samuel-williams-da's comment, that sounds probably cleaner.

**Comment by garyverhaegen-da** [comment]
> Perhaps we could create a file group as we do with daml2-script, but just containing this dar with the correct name? Iirc, daml2-script just copies all the files in the file group without rename

This doesn't run from within Bazel. I may be missing something but how would a filegroup in Bazel help us here?

> Well, I could extract the lf version from the dar using
> 
> ```
> daml damlc inspect daml3-script-2.dev.dar | grep '^daml-lf' | awk '{print $2}'
> ```
> 
> I don't know how hacky that would be considered.

We don't have a daml installation ready at this step. It's supposed to be a simple mostly-curl job.

I was thinking more of a file we can grep somewhere. Alternatively if the file generated by Bazel had the lf version in its name already at least this would fail on our side in the daily snapshot build, rather than when users try to use a release.

**Comment by paulbrauner-da** [comment]
> This doesn't run from within Bazel. I may be missing something but how would a filegroup in Bazel help us here?

It doesn't but it invokes bazel. For daml-script (the non daml3 version) we do `bazel build` a file group and copy the result: https://github.com/digital-asset/daml/blob/6cdc601f43297b2b8eee33cb143349d6b535233a/ci/copy-unix-release-artifacts.sh#L94. I'm working on doing the same for daml3, and to make sure this will work for all 2.x versions, not just 2.dev.

**Review by samuel-williams-da — APPROVED** [review]
Nice! I like this :)

**Comment by paulbrauner-da** [comment]
I checked that `daml-sdk-head` produces an SDK with `daml3-script-2.dev.dar` in the expected location. Same for `ci/copy-unix-release-artifacts.sh foo linux /tmp/ci`. Enabling auto-merge.

**Pull request merged**
