### PR TITLE
speeding and cleaning up the assistant integration tests

### PR DESCRIPTION
**Pull request by robin-da**
This cleans up the daml assistant integration tests. The time is cut down to
about 3min from previously 15. This is done by minimizing the number of `daml
start` invocations.

Sadly the diff is quite a mess, you'll have to look at the whole file. Sorry
for that!

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by SamirTalwar-DA** [comment]
If this fixes the flaky tests I will be so happy. ^_^

**Comment by hurryabit** [comment]
@robin-da I haven't looked at the details yet but before I start I'd like to get a better understanding of _how_ it is minimizing the number of `dam start` invocations. Are we merging tests? Are we reusing `daml start` invocations between tests? Are we dropping tests?

**Comment by robin-da** [comment]
@hurryabit The time is cut by running `daml start` only one time and then only testing for the actual outcome in the tests. For example, instead of running `daml start` and then testing whether the init script was run, we run `daml start` in the beginning and then check whether the initial script was run by querying the sandbox. We check that `daml start` comes up with a relative path, by invocing the first `daml start` with a relative project path instead of running an extra invocation of `daml start` for this. This makes the tests faster, but has the downside that it will not be as easy to pinpoint an error case when something fails. I guess we'll have to strike a compromise here between speed and compartmentalization of tests. There should be no dropped tests.

**Review by hurryabit — APPROVED** [review]
I didn't check the full diff but the result looks quite reasonable. Thanks.

Did I understand it correctly that we're now running `daml start` only one time and then with a relative path? If so, we should add tests that show that the other ways of running it, I guess without a path and/or with an absolute path, also still work. This means we need to run `daml start` multiple times but still far less often than before.

**Comment by robin-da** [comment]
@hurryabit ok, I added two more `daml start` startups to test for relative/absolute path. This adds 1min more to the tests.

**Comment by hurryabit** [comment]
@robin-da Thanks a lot for adding the other two test cases. A minute is not too bad. Although I would prefer to not spend it, I think we're spending it well in this case.

**Pull request merged**
