### PR TITLE
CI: use the windows pool

### PR DESCRIPTION
**Pull request by aherrmann-da**
building on top of #368. Now that we have a pool of windows agents, make use of them.

Re-opened #599 here so Azure can run automatically.

Depends on #1047, don't merge before.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/docs/source/support/release-notes.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by neil-da** [comment]
CC @majcherm-da - seems you two are in the same area? Hopefully nicely in sync :)

**Comment by majcherm-da** [comment]
@neil-da yes, that's correct, will clean up PRs after I make it work. This one contains JDK update as well - I'm trying to limit the # of moving parts.

**Comment by cocreature** [comment]
I think this can be closed, right @aherrmann?

**Comment by aherrmann-da** [comment]
Closed in favor of https://github.com/digital-asset/daml/pull/1069

**Pull request closed without merging**
