### PR TITLE
Deprecate the "daml 1.2" version header.

### PR DESCRIPTION
**Pull request by sofiafaro-da**
changelog_begin

- [DAML] The "daml 1.2" version header is now deprecated.

changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by cocreature — APPROVED** [review]
Awesome, thank you! Maybe worth adding a test for this?

**Comment by sofiafaro-da** [comment]
> Awesome, thank you! Maybe worth adding a test for this?

It's in there! :-) https://github.com/digital-asset/daml/pull/7513/files#diff-87816f5b1d0c6fa32e92f6f649e3260bR2

**Comment by cocreature** [comment]
Perfect thanks! Not sure how I managed to miss that :)

**Review by hurryabit — COMMENTED** [review]
Great work. Thanks a lot!

**Pull request merged**
