### PR TITLE
Remove unnecessary `@SuppressWarnings("org.wartremover.warts.Any")`.

### PR DESCRIPTION
**Pull request by SamirTalwar-DA**
We don't use this warning any more, so there's no need to suppress it.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by S11001001** [comment]
I left these in place because I have some optimism that the wartremover issues will be fixed; we removed it not because it is a bad wart, but because its bugs cause more trouble than they are worth. Removing these suppressions will only make it harder to reintroduce should they be fixed.

**Comment by cocreature** [comment]
That’s fair, I don’t feel very strongly about this. I don’t think leaving it in is all that useful but neither is removing it.

**Comment by SamirTalwar-DA** [comment]
I think that most of these were put there specifically to suppress the false positives (e.g. `.view`, actor `receive` methods, types that are too clever for Wartremover or me to understand).

If the wart is improved to the point where it's useful, they'll be unnecessary.

I think it's worth revisiting the few cases where a new and improved wart flags issues to ensure there's really a problem.

**Comment by S11001001** [comment]
Most of the ones that _were_ there were dealing with false positives. I removed those in the original PR, though.

**Comment by SamirTalwar-DA** [comment]
@S11001001, can you point to valid suppressions in this PR?

I would have expected that if a suppression was valid, that would point to a potential problem in our code, in that we are making use of `Any` to subvert the type system. I don't see anywhere here where we do that; they all seem to be along the lines of "Wartremover is not smart enough yet".

**Comment by S11001001** [comment]
> can you point to valid suppressions in this PR?

I will describe a few examples ⬇️ 

> I would have expected that if a suppression was valid, that would point to a potential problem in our code, in that we are making use of `Any` to subvert the type system.

This is not an implication of a usage of `Any`, merely a correlation.

For one set of examples, `Any` can occur indirectly; if working with an interface entails working with `Any`, then `Any`s will occur in the inferred types, regardless of how sound you make it. One such example is in `SomeArrayEquals`. Any `Equality` instance is another example. The `n` interpolator is yet another. All these refer to or infer `Any` as a necessary consequence of conforming to the design of some other component.

Another legitimate usage is for polymorphism. In contravariant positions, `Any` equals `A` with an outer `forall A` with no other bounds, similar to how `Nothing` may be used in covariant positions. You might think `just use an `[A]` binder, but this is often significantly less convenient, and it is not any kind of subversion to use `Any` in this way. There are several examples of this in this PR, too.

There are a few false positives from #6132 I missed that I can see in your diff, but the majority are not. If you like, I can enumerate those by marking in comments; they are far fewer.

The goal of a suppression is to distinguish such relatively legitimate uses, and also to call them out to the reader (as inferred ones will certainly not be greppable), permitting that legitimacy to be reexamined. It is not the case that the daml codebase against a bugfixed `Any` wart would not contain several such suppressions, including almost all of the ones here.

**Comment by SamirTalwar-DA** [comment]
@S11001001: What you say makes sense. I think it would be lovely if the `Any` wart allowed for it in a contravariant context (and `Nothing` was allowed in a covariant context), but according to https://github.com/wartremover/wartremover/issues/263, this is unlikely to happen.

While I think there's value in revisiting these if and when we reintroduce the warning, and I'm not a big fan of comments because maybe someday, clearly you've put a lot of thought into this and I understand your reasoning for keeping these suppressions around for now. I would like to revisit this if we still haven't brought the warning back by, say, end of 2020.

I'll close this PR for now. 🙂

**Pull request closed without merging**
