### PR TITLE
Disable pushing Bazel metrics on PRs from forks

### PR DESCRIPTION
**Pull request by cocreature**
We don’t have credentials there so the job just fails.

changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by garyverhaegen-da — APPROVED** [review]

**Review by aherrmann-da — COMMENTED** [review]
Thanks!

**Comment by realvictorprm** [comment]
Now this is interesting, did we have some metrics from user repositories :smile: ?

**Comment by cocreature** [comment]
no we had PRs from user-repositories failing CI since they do not have credentials to push

**Comment by realvictorprm** [comment]
I didn't expect that reason, somewhat funny :smile: Thanks

**Comment by garyverhaegen-da** [comment]
To clarify, the issue here was that our build process was trying to push files to a GCS bucket, from a CI run, using a secret made available by Azure (to serve as the login credential to get write access to the GCS bucket).

Azure does not make secrets available to builds of forks, so the "login with GCS to get write access" step failed.

**Pull request merged**
