### PR TITLE
kvutils: Use the contextualized logger in the committer.

### PR DESCRIPTION
**Pull request by SamirTalwar-DA**
This means we don't have to provide context explicitly on each log line; it'll get passed through.

We include extra logging context, extracted from the state at each step.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by SamirTalwar-DA** [comment]
Unfortunately this PR is mostly boilerplate changes due to passing logging contexts around explicitly. Perhaps we can change `Step` to be a trait? This will increase boilerplate at the declarations but remove it from the call sites.

**Comment by fabiotudone-da** [comment]
> Unfortunately this PR is mostly boilerplate changes due to passing logging contexts around explicitly. Perhaps we can change `Step` to be a trait? This will increase boilerplate at the declarations but remove it from the call sites.

I think turning `Step` into a trait can't harm, quite the opposite. If you also see it reducing the diff, I an in favor of it.

**Comment by SamirTalwar-DA** [comment]
I made the change but it enlarges the diff considerably. So I think we should do it separately.

**Review by fabiotudone-da — APPROVED** [review]
It looks much better now IMO, thanks!

**Pull request merged**
