### PR TITLE
Remove unused dependencies to da_scala_test(_suite)

### PR DESCRIPTION
**Pull request by aherrmann-da**
Enables rules_scala's unused dependency checker by setting the attribute `unused_dependency_checker_mode = "error"` and removes unused dependencies on `da_scala_test` targets. This avoids unnecessary dependencies which is better for parallel builds and caching.

rules_scala does not currently support `unused_dependency_checker_mode` on `scala_test_suite`. However, their dependencies can be pruned by temporarily converting them to use `scala_test` instead. This was done in this PR as well.

Some `da_scala_test(_suite)` targets had their `deps` attribute factored out to a `testDependencies` variable or similar. This makes "unused dependency checker" warnings harder to fix, so they have been inlined.

 The unused dependency checker also revealed that we were using two different scalatest targets in the build. One provided by rules_scala, and the other due to transitive dependency in rules_jvm_external. This has been fixed by adding an override to point rules_jvm_external to the rules_scala provided target.

`scala_binary` and `scala_library` will be handled in separate PRs.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags, if appropriate
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by leo-da** [comment]
I like the check. However the dependency inlining... is that really required? We will have to specify the same deps twice for compile and test targets. Or is this the "bazel best practice" approach?

**Comment by aherrmann-da** [comment]
> I like the check. However the dependency inlining... is that really required? We will have to specify the same deps twice for compile and test targets. Or is this the "bazel best practice" approach?

It's more explicit, so in that sense closer to "bazel best practice". It also makes it easier to fix future unused dependency warnings. E.g. if a dependency is removed in a test, but not in the library.

It's not strictly required. Though, to me it seems easier to maintain.

**Comment by aherrmann-da** [comment]
> LGTM;

Thanks!

> but if it is up to me... I would make it an error, not warning.

Sorry, was badly phrased on my part. It is an error. The errors look like this
```
error: Target '@maven//:io_circe_circe_yaml_2_12' is specified as a dependency to //daml-assistant/scala-daml-project-config:scala-daml-project-config-tests but isn't used, please remove it from the deps.
You can use the following buildozer command:
buildozer 'remove deps @maven//:io_circe_circe_yaml_2_12' //daml-assistant/scala-daml-project-config:scala-daml-project-config-tests
```

**Comment by SamirTalwar** [comment]
Looks good. I would inline the various `compile_dependencies`-esque variables now they're only used once.

**Comment by aherrmann-da** [comment]
> Looks good. I would inline the various `compile_dependencies`-esque variables now they're only used once.

Agreed, planning to do this with `scala_library|binary`.

**Comment by stefanobaghino-da** [comment]
I like this *a lot*, thanks! :tada:

**Pull request merged**
