### PR TITLE
daml-lf: add hook for experimental builtins

### PR DESCRIPTION
**Pull request by remyhaemmerle-da**
This PR advance the state of #3710

Here we add a hook in daml-lf archive to quickly add new experimental built-in without having to update the archive decoder nor the type checker. 

`take :: Int64 -> Text -> Text` is provided as example.

### Pull Request Checklist

- [X] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [X] Include appropriate tests
- [X] Set a descriptive title and thorough description
- [X] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags, if appropriate
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by associahedron** [comment]
This seems unnecessary in light of #3734

**Comment by cocreature** [comment]
I also think this doesn’t buy us that much. If you look at #3734, we have 372 new lines in total

* 167 of those which have pretty much all the complexity are in `SBuiltin.scala` which is unaffected by this change.
* 68 of those are in `DA.Text.daml` which is also unaffected by this change.

So even if we assume that all other changes would not be necessary with this change (which is not true, e.g. the LF conversion will still need some changes although they might get simpler), this seems to save you very little time during writing while probably causing more time during debugging since you might easily screw something up that would have been caught by that additional work.

**Comment by stefanobaghino-da** [comment]
@remy this seems to be stale. If it's no longer needed, I'd ask you to close this.

**Comment by remy** [comment]
Any chance you could use the right GitHub handle? Otherwise I keep getting cc'ed into your repo.

**Comment by stefanobaghino-da** [comment]
> Any chance you could use the right GitHub handle? Otherwise I keep getting cc'ed into your repo.

Sorry for that. I'll pay more attention.

**Comment by stefanobaghino-da** [comment]
@remyhaemmerle-da this seems to be stale. If it's no longer needed, I'd ask you to close this.

**Pull request closed without merging**
