### PR TITLE
Update Java example instructions to use new repository

### PR DESCRIPTION
**Pull request by bethaitman-da**

### CODE REVIEW

**Comment by gerolf-da** [comment]
@bethaitman-da: do you intend to modify `docs/source/app-dev/bindings-java/index.rst` as well?

**Comment by bethaitman-da** [comment]
@gerolf-da For some reason I thought the instructions on those had been updated to talk about GitHub already - my bad. I'll sort that out too.

**Comment by gerolf-da** [comment]
Thanks so much, @bethaitman-da!

**Comment by gerolf-da** [comment]
Fixes #182.

**Pull request merged**
