### PR TITLE
Adapt JSON API server to the new explicit disclosure Ledger API interface

### PR DESCRIPTION
**Pull request by tudor-da**
This PR adapts the standalone JSON API server to the Ledger API changes introduced in https://github.com/digital-asset/daml/pull/17606 and amended in https://github.com/digital-asset/daml/pull/17705.

**Summary**
The `DisclosedContract.metadata` and `DisclosedContract.arguments` are replaced by `DisclosedContract.createdEventBlob`. This change is implemented in a non-backwards-compatible manner.

### CODE REVIEW

**Comment by tudor-da** [comment]
Thanks @raphael-speyer-da ! I've addressed your comments. Additionally I've added a commit that switches to `Base64` vanilla encoding for the createdEventBlob instead of the `Base64Url` (at @moritzkiefer-da 's suggestion).

Quoting his initial suggestion:
> One question: We currently use url base64 encoding for the created event blob. We did the same before for the blob. However, I'm not quite convinced this is a good idea. There is no reason to use it, this does not appear in a URL and generally any base64 library defaults to standard base64 encoding and some (e.g. JS) don't even have builtin support for url base64 encoding.

> So how about we just change that to standard base64 encoding while we still can without worrying about backwards compat?

**Comment by raphael-speyer-da** [comment]
Thanks @tudor-da . I've added a commit for the TypeScript codgen tests, but I had to short-circuit the end of an integration test, because it appears canton does not currently populate this `created_event_blob` field yet, and the test is for explicit disclosure. Once that data is there, you should be able to just remove the short-circuit there.

**Review by raphael-speyer-da — APPROVED** [review]

**Comment by tudor-da** [comment]
> Thanks @tudor-da . I've added a commit for the TypeScript codgen tests, but I had to short-circuit the end of an integration test, because it appears canton does not currently populate this `created_event_blob` field yet, and the test is for explicit disclosure. Once that data is there, you should be able to just remove the short-circuit there.

There is no concrete plan yet to populate the `created_event_blob` for the `EventQueryService` or for any pointwise query for that matter. Currently one can fetch the `created_event_blob` from the transaction (tree) or ACS streams (see how we did it in the JSON API integration test). 

The implementation of the TS changes in your commit look sane from my side so I'm fine if you want to merge like this and address the integration test changes later.

**Comment by tudor-da** [comment]
LGTM @raphael-speyer-da , thanks for your contribution. I'll merge when it's green

**Pull request merged**
