### PR TITLE
Use snakeyaml 2.0 [#16412].

### PR DESCRIPTION
**Pull request by atriantafyllos-da**
https://github.com/digital-asset/daml/issues/16412

Snakeyaml 1.33, which is knowingly vulnerable, was pulled in by `circe-yaml` (14.2). Upgrading to 15.0RC1 pulls snakeyaml 2.0 which has not any known vulnerabilities atm.
For more see: #16412

### CODE REVIEW

**Review by tudor-da — APPROVED** [review]
🤞 On another note, I guess we need to update in Canton as well as it's using the same circe dep version

**Comment by tudor-da** [comment]
Ah I was afraid of this. this forced update of snakeyaml breaks binary compatibility (see `NoSuchMethod` errors in logs)

**Comment by atriantafyllos-da** [comment]
> Ah I was afraid of this. this forced update of snakeyaml breaks binary compatibility (see `NoSuchMethod` errors in logs)

Yes I am trying to see if upgrading io.circe:circe-yaml to 0.14.3-RC3 will solve the problem. @tudor-da @mziolekda wdyt?

**Comment by tudor-da** [comment]
> > Ah I was afraid of this. this forced update of snakeyaml breaks binary compatibility (see `NoSuchMethod` errors in logs)
> 
> Yes I am trying to see if upgrading io.circe:circe-yaml to 0.14.3-RC3 will solve the problem. @tudor-da @mziolekda wdyt?

Unfortunately, that one is still relying on snakeyaml 1.33

**Comment by atriantafyllos-da** [comment]
@mziolekda Can 2.6 be shipped without resolving this issue?

**Comment by mziolekda** [comment]
Unfortunately, it cannot go out without it, we'll wait for the circe upgrade which hopefully will come any hour/day

**Comment by atriantafyllos-da** [comment]
Upgraded circe-yaml to 15.0-RC1.

**Review by mziolekda — APPROVED** [review]

**Comment by mziolekda** [comment]
Tnaks Andreas, as there is no official version still, I am accepting this PR that introduces version 0.15.0-RC1 of circe-yaml. It is better to be on an unofficial patched release than to be on an official but vulnerable.

**Pull request merged**
