### PR TITLE
Engine: make package validation optional.

### PR DESCRIPTION
**Pull request by remyhaemmerle-da**
This is part of #7399.

This enable skipping packages validation in the engine when they are
comming from a trusted source.

CHANGELOG_BEGIN
CHANGELOG_END

### Pull Request Checklist

- [X] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [X] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by cocreature — APPROVED** [review]
LGTM thank you! Does this interact with the lightweight validation we have for scenarios in any way? Should it?

**Comment by remyhaemmerle-da** [comment]
>  Does this interact with the lightweight validation we have for scenarios in any way? Should it?

Since #5666, the lightweight validation we have for scenarios apply only for uploaded modules not for uploaded packages.
For uploaded modules are (optionally), the scenario service (optionally) performs itself the validation and then use an ad-hoc  method of the compiler that do not do perform any validation. 
Uploaded packages are compiled using the standard compilation, that (first) validate the packages.

**Comment by cocreature** [comment]
Makes sense, thanks :+1:

**Review by hurryabit — COMMENTED** [review]
Nice. Thank you.

Do we want a command line flag for sandbox to skip validation?

**Pull request merged**
