### PR TITLE
Make ledger api multi-party subscription transaction test singlenode

### PR DESCRIPTION
**Pull request by oliverse-da**
"Archives should always come after creations when subscribing as more than on party"
used to have the assumption that Alice and Bob's (single stakeholder) Dummy contracts
are visibile to both participant nodes which is not the case in multinode. Scoped
checks to be per-party.

### Pull Request Checklist

- [X] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [X] Include appropriate tests
- [X] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/unreleased.rst), if appropriate
- [ ] Normal production system change, include purpose of change in description

### CODE REVIEW

**Comment by oliverse-da** [comment]
> This is not the right solution, the problem is that this test is not supposed to work across participants in the first place, so this should be turned into a single participant test. I'd suggest waiting until #3401 is merged.

Made test single-participant. I can wait until #3401 is merged.

**Comment by stefanobaghino-da** [comment]
My suggestion was to wait for #3401 to be merged because you'll need to change some code to allocate. The PR changes factors participants/parties allocation out of the individual test cases.

**Comment by oliverse-da** [comment]
> My suggestion was to wait for #3401 to be merged because you'll need to change some code to allocate. The PR changes factors participants/parties allocation out of the individual test cases.

Looks like #3401 is merged now, so I will rebase.

**Pull request merged**
