### PR TITLE
Centralize metric names

### PR DESCRIPTION
**Pull request by gerolf-da**
CHANGELOG_BEGIN
CHANGELOG_END

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by gerolf-da** [comment]
@SamirTalwar-DA, @stefanobaghino-da, @rautenrieth-da: opening this as a draft for discussion.
The metrics are defined in a hierarchy  in [`Metrics`](https://github.com/digital-asset/daml/pull/5790/files#diff-c455b5ef86f3eac1e49aba3a837c4d95) and let's take [`MeteredLedgerDao`](https://github.com/digital-asset/daml/pull/5790/commits/ac8c96dbbbb62fddcf3d0335704bc827df9c451b#diff-e4c4e3f81888bd3c830e84808a1606d9R49) as an example.

**Comment by stefanobaghino-da** [comment]
I love it.

**Comment by gerolf-da** [comment]
What do you think about keeping on passing `MetricsRegistry` around and only instantiating the `Metrics` class where it is actually needed? I started swapping out `MetricsRegistry` for `Metrics` in the parameters, but I'm thinking that it's not really necessary, except that it maybe discourages use of the registry directly for ad-hoc metrics?

**Comment by gerolf-da** [comment]
@SamirTalwar-DA: the metric paths haven't changed at all. it's just that the definition of the metrics is now in a centralized place. This only helps with finding out with metrics we already have without running through the codebase like a headless chicken :)

**Comment by SamirTalwar-DA** [comment]
OK, great. I see now that the last commit moved some back where they should be. I thought it was moving them away.

**Pull request merged**
