### PR TITLE
Minor improvements to getting started doc

### PR DESCRIPTION
**Pull request by shaul-da**

### CODE REVIEW

**Review by robin-da — APPROVED** [review]
Thanks!

**Comment by hurryabit** [comment]
@shaul-da Welcome to the party! 🥳

Thanks for the suggestions. In order for your PR to pass CI, you need add a commit whose message contains the following two lines:
```
CHANGELOG_BEGIN
CHANGELOG_END
```
Usually, a description of the _user facing_ change would go between these to tags, but there's nothing really changing in this regard here.

@garyverhaegen-da Could you please add @shaul-da to the list of contributors so we don't need to run `/azp run` for him. Merci.

**Comment by garyverhaegen-da** [comment]
> @garyverhaegen-da Could you please add @shaul-da to the list of contributors so we don't need to run `/azp run` for him. Merci.

@shaul-da I've sent an invite to add you to the org. To have CI running automatically you will need to push your branches directly to this repo, rather than your personal fork. (We can't do anything about this PR.)

**Pull request merged**
