### PR TITLE
Mandatory config options in trigger service docs

### PR DESCRIPTION
**Pull request by matevarga-da**
I found during testing related to support ticket 00003571, that the only necessary configuration option to define in the configuration file for the trigger service is the ledger-api section.

CHANGELOG_BEGIN
CHANGELOG_END

### CODE REVIEW

**Comment by stefanobaghino-da** [comment]
Would you mind rebasing? I can have a look and possibly merge.

**Review by loiskilberg-da — APPROVED** [review]

**Comment by matevarga-da** [comment]
@stefanobaghino-da It looks like the file I modified is no longer there. Was it moved to the docs.daml.com repo?

**Comment by loiskilberg-da** [comment]
@matevarga-da @stefanobaghino-da I believe the file did indeed move to docs.daml.com. @garyverhaegen-da could probably help if needed?

**Comment by matevarga-da** [comment]
Moving this to the docs.daml.com repo.

**Comment by garyverhaegen-da** [comment]
For the record: https://github.com/digital-asset/docs.daml.com/pull/193.

**Pull request closed without merging**
