### PR TITLE
DLint: Disable "Redundant pure" lint by default

### PR DESCRIPTION
**Pull request by hurryabit**
When using `ApplicativeDo`, e.g. in Daml Scripts, a final pure might be
necessary although it would be redundant in a monadic context. This
leads to spurious warnings from the linter which I found quite
confusing.

CHANGELOG_BEGIN
CHANGELOG_END

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

---
This change is [Reviewable](https://reviewable.io/reviews/digital-asset/daml/8733)

### CODE REVIEW

**Review by sofiafaro-da — APPROVED** [review]
Thank you!

**Review by cocreature — APPROVED** [review]
Thanks! Just because I’m curious, do you know if the pure is generally required by applicative do or if this is a weird side effect of us hacking `*>` into `>>` in some cases in do notation?

**Comment by hurryabit** [comment]
> Thanks! Just because I’m curious, do you know if the pure is generally required by applicative do or if this is a weird side effect of us hacking `>>` into `>>=` in some cases?

Unfortunately, I don't know. But it seems quite plausible that this is related.

**Comment by cocreature** [comment]
There are a bunch of test failures triggered by this due to missing diagnostics. Should just be a matter of deleting them in a few places.

**Pull request merged**
