### PR TITLE
ci: publish the bazel test logs

### PR DESCRIPTION
**Pull request by jonas-chevalier-da**
As a developer I want to be able to inspect the detailed test logs when those are
failing.

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/docs/source/support/release-notes.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by jonas-chevalier-da** [comment]
do we always want the test logs or only on failure?

**Comment by neil-da** [comment]
I don't think anyone cares if they succeeded. What's the cost of doing it always though? In terms of cash/time or whatever.

**Comment by jonas-chevalier-da** [comment]
@neil-da it adds another 57s to the build

**Comment by jonas-chevalier-da** [comment]
changed it to only publish on failure

**Pull request merged**
