### PR TITLE
Remove Extractor

### PR DESCRIPTION
**Pull request by stefanobaghino-da**
Extractor is being removed after a long time being in Labs status.

This should improve the flakiness on CI.

:fire:

changelog_begin
Extractor has been removed from the SDK
changelog_end

The removal of Extractor has been confirmed by Drew and Fil via @davidrichards-da.

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by cocreature — COMMENTED** [review]
You need to drop it from the SDK as well.

**Comment by stefanobaghino-da** [comment]
> You need to drop it from the SDK as well.

I got excited and opened this up to early, moving this to draft.

**Comment by stefanobaghino-da** [comment]
@cocreature, removal of

- documentation https://github.com/digital-asset/daml/pull/12188/commits/5800cd8cf6046d8d34cabea090e67f731bb0f711 
- CODEOWNER reference https://github.com/digital-asset/daml/pull/12188/commits/0a18fd9da9fb1071c5b9297496eca1ea1f50f3f4
- Daml-LF build files references https://github.com/digital-asset/daml/pull/12188/commits/4eec0fba29ea07f6a5d448e4b8669dc0fffcbe8f
- Daml SDK assistant https://github.com/digital-asset/daml/pull/12188/commits/a53b93b85c438b492e06d6e00cc5bd0a6c1d70d6
- SDK https://github.com/digital-asset/daml/pull/12188/commits/51992d70c96cc560ee91458779a7522c8074c3b8

Something I forgot?

**Comment by stefanobaghino-da** [comment]
I did a second round and noticed I missed a reference to it in `CONTRIBUTING.md`, fixed by https://github.com/digital-asset/daml/pull/12188/commits/dd2b772f985a72c63495bf1b4e4277c1cd0d858f.

**Review by cocreature — APPROVED** [review]
:fire:

**Pull request merged**
