### PR TITLE
fix preview

### PR DESCRIPTION
**Pull request by garyverhaegen-da**

### CODE REVIEW

**Review by nickchapman-da — APPROVED** [review]
Thanks!

**Comment by stefanobaghino-da** [comment]
What was the problem?

**Comment by nickchapman-da** [comment]
> What was the problem?

`docs/scripts/preview.sh` was not updating (on Linux) because the timestamps on the html files in the unpacked archive do not change (always Jan 1st 2000) even when the contents change.

**Comment by stefanobaghino-da** [comment]
> > What was the problem?
> 
> `docs/scripts/preview.sh` was not updating (on Linux) because the timestamps on the html files in the unpacked archive do not change (always Jan 1st 2000) even when the contents change.

Got it, thank you! 🙇🏻‍♂️

**Pull request merged**
