### PR TITLE
trigger service: allow non-empty schema

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
Untested as yet.

CHANGELOG_BEGIN
CHANGELOG_END

### CODE REVIEW

**Review by stefanobaghino-da — COMMENTED** [review]
No objections on my side, but I wouldn't rush using this to put all our tables in a single schema to solve our problems. Adding some sort of test would also be good.

**Review by aherrmann-da — APPROVED** [review]
LGTM

Re testing: Perhaps a test-case around `triggerDao.initialize` with a prior schema setup and `allowExistingSchema = false|true` to test that it fails|succeeds as expected would do.
This really only tests that the flag is forwarded to flyway correctly.
It assumes that flyway works, so we don't need to test it itself.
It also assumes that the trigger service will work as expected once the migration completed, so we don't need to duplicate the entire postgres and oracle test suites for each setting.

**Comment by garyverhaegen-da** [comment]
We now believe that adding table prefixes is a better approach, so there is no need for this anymore.

**Comment by stefanobaghino-da** [comment]
> We now believe that adding table prefixes is a better approach, so there is no need for this anymore.

I'm not entirely sure this rules out this needs to be in, though. Not necessary to open this PR here, but I would test the final solution thoroughly to make sure we don't actually need this in as well. /cc @aherrmann-da

**Pull request closed without merging**
