### PR TITLE
remove create-daml-app

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
Why?

This is a terrible introductory application. We have no expertise in web development (it's terribly outdated and we don't have the knowledge to update it), so steering newcomers in that direction is disputable at best. This example (and the associated documentation) spends more time discussing (a very old version of) TypeScript than Daml. The use-case presented is not one that showcases the strength of either the Daml language or the underlying Canton ledger. It's not even a distributed application as it assumes a single ledger.

At best, this template presents Daml as a DDL for simple wep API definitions, but one where the resulting generated code provides no support for authentication, external API calls, or any common server-side tasks like sending emails.

Why now?

As we start working in parallel on 2.9 and 3.0, we are faced with the perspective of having to do two weekly snapshots and thus having to test both of them. Removing create-daml-app from the 3.0 branch alleviates the testing burden quite a bit.

Daml 3.0 will be a long-term effort, and we have plenty of time to figure out what should replace create-daml-app for this new version. If this template was bad at showcasing Daml 2 strength, it's an even worse fit for Daml 3.

Note that this PR removes a lot fo additional tests, notably compatibility ones. They live on in the main-2.x branch, where compatibility tests also run.

### CODE REVIEW

**Review by marciw-da — COMMENTED** [review]
Hmm, I don't think we're ready to do this. AFAIK, the plan is to keep some version of create-daml-app as *one* getting started experience -- not the only one and not the main one. We're figuring this out as part of the ref app work, but so far I'm hearing from several stakeholders that we want to keep create-daml-app in some form.

I don't disagree with your assessment! But I don't think we have consensus on this yet.

**Comment by basvangijzel-DA** [comment]
I am in favour of getting rid of it for now. I don't think it's worth making this part of integration testing/release testing for internal releases for a year. We should find a solution for the stakeholders before we release 3.0, but I think we can cull this now.

**Comment by garyverhaegen-da** [comment]
> Hmm, I don't think we're ready to do this. AFAIK, the plan is to keep some version of create-daml-app as _one_ getting started experience -- not the only one and not the main one. We're figuring this out as part of the ref app work, but so far I'm hearing from several stakeholders that we want to keep create-daml-app in some form.
> 
> I don't disagree with your assessment! But I don't think we have consensus on this yet.

You make it sound like you don't disagree but know people who might. Could you please ask those people to opine here?

**Comment by marciw-da** [comment]
> > Hmm, I don't think we're ready to do this. AFAIK, the plan is to keep some version of create-daml-app as _one_ getting started experience -- not the only one and not the main one. We're figuring this out as part of the ref app work, but so far I'm hearing from several stakeholders that we want to keep create-daml-app in some form.
> > I don't disagree with your assessment! But I don't think we have consensus on this yet.
> 
> You make it sound like you don't disagree but know people who might. Could you please ask those people to opine here?

I looked back at my notes and the "keep it" discussion was for 2.9 rather than 3.0. So I'm OK with removing it for 3.0. Maybe @bame-da could give a quick thumbs up though.

**Review by marciw-da — APPROVED** [review]

**Review by gerolf-da — APPROVED** [review]
Thank you @garyverhaegen-da. Both @bame-da and @rgugliel-da are fine with removing create-daml-app from daml 3

**Pull request merged**
