### PR TITLE
ghc-lib:remove unused let bindings

### LINKED ISSUE #13431: Archive choice does not need let bindings
Currently, the autogenerated Archive choice still includes let bindings. Given that we control them this is somewhat redundant and we could just omit them to speed things up slightly.

### PR DESCRIPTION
**Pull request by robin-da**
This updates ghc-lib, such that no unused let bindings are created in
Archive choices.

Corresponding PR for ghc: https://github.com/digital-asset/ghc/pull/114

Fixes #13431.

CHANGELOG_BEGIN
CHANGELOG_END

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by garyverhaegen-da** [comment]
Shouldn't we be using a commit that's actually in the da-master-8.8.1 branch? Currently this PR targets an unmerged commit.

**Review by sofiafaro-da — APPROVED** [review]
Looks good. Unfortunately I don't see a good way to test this. It would be nice to update `InterfaceDesugared.daml`

@garyverhaegen-da The way this usually works is we test that everything works against the GHC PR first before code review, then once both PRs are approved, the GHC PR is merged, and then this PR is tested against the new GHC da-master-8.8.1 branch, and then merged into main.

**Comment by garyverhaegen-da** [comment]
> Looks good. Unfortunately I don't see a good way to test this. It would be nice to update `InterfaceDesugared.daml`
> 
> @garyverhaegen-da The way this usually works is we test that everything is tested against the GHC PR first before code review, then once both PRs are approved, the GHC PR is merged, and then this PR is targeted against the new GHC da-master-8.8.1 branch, and then tested & merged into main.

Makes sense, thanks for the explanation.

**Comment by robin-da** [comment]
@sofiafaro-da I updated the `InterfaceDesugared.daml` file as well.

**Comment by sofiafaro-da** [comment]
> @sofiafaro-da I updated the `InterfaceDesugared.daml` file as well.

Thanks! Looks good!

**Comment by cocreature** [comment]
> Looks good. Unfortunately I don't see a good way to test this. It would be nice to update `InterfaceDesugared.daml`

we noticed this issue originally in the visualizer. If you have a let binding that calls `create`, you get an arrow from Archive -> Create which is clearly very confusing. Not sure if that’s super sensible as a test since it feels a bit indirect but at least worth considering.

**Pull request merged**
