### PR TITLE
remove stale license check scripts

### PR DESCRIPTION
**Pull request by dasormeter**
Remove stale license check scripts and rst files for navigator and daml compiler

### CODE REVIEW

**Comment by dasormeter** [comment]
@cocreature these have not been changed in more than a year and no one is using them so they can go independent of the blackduck pending PR. and yes blackduck does both license and security vulnerability checks

**Comment by dasormeter** [comment]
looks like there are some file level dependencies to the rsts in compiler/damlc/lib/DA/Cli/Damlc.hs : will clean that up too on this PR

**Comment by dasormeter** [comment]
> @dasormeter Can you please double-check with security and legal that removing these files is ok?

@hurryabit they are stale and not used for anything today -- the root NOTICES file is all that is used

**Comment by hurryabit** [comment]
@dasormeter I assume we don't need any of those files for generating the `NOTICES` file, do we?

**Comment by dasormeter** [comment]
gary has accomplished this cleanup in a more targeted way : closing

**Pull request closed without merging**
