### PR TITLE
Get rid of ./build.sh scripts for damlc migrate

### PR DESCRIPTION
**Pull request by cocreature**
Now that we have the build-options fields that makes for a much nicer
interface.

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/unreleased.rst), if appropriate
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by cocreature** [comment]
@associahedron `damlc migrate` creates a completely new project so I don’t think that’s an issue.

**Comment by cocreature** [comment]
Yes, they are even modified this PR :stuck_out_tongue:

**Comment by hurryabit** [comment]
Oops, I didn't realize that was a test... My bad. :blush:

**Comment by cocreature** [comment]
That said, we are desperately lacking more extensive tests for upgrading so while this particular code path is tested, your comment is still very valid.

**Pull request merged**
