### PR TITLE
Release version 1.6.1-snapshot.20201021.5317.0.aafe46a5. [KVL-666]

### PR DESCRIPTION
**Pull request by SamirTalwar-DA**
Cut from the 1.6.x release branch.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [x] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by cocreature — APPROVED** [review]
thanks!

**Review by gerolf-da — APPROVED** [review]
Thanks, @SamirTalwar-DA!

**Comment by SamirTalwar-DA** [comment]
Only took 4 attempts!

**Comment by SamirTalwar-DA** [comment]
Manual tests passed on Linux.

**Comment by SamirTalwar-DA** [comment]
Manual tests passed on Windows.

**Pull request merged**
