### PR TITLE
narrow LF codeowners; add ledger-service codeowners

### PR DESCRIPTION
**Pull request by S11001001**
It's useless to have a daml-lf codeowner; narrow it down. We also need a http-json codeowner (and the utilities surrounding it). I'd like people to explicitly request if they'd like my input rather than codeowners always forcing the issue; I've marked out versioning explicitly, though, because it requires so much care.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by stefanobaghino-da** [comment]
Would it make sense to add @remyhaemmerle-da as an owner of `daml-lf`?

**Comment by remyhaemmerle-da** [comment]
> Would it make sense to add @remyhaemmerle-da as an owner of `daml-lf`?

:+1:

**Comment by S11001001** [comment]
@remyhaemmerle-da I don't think you really want that :) but feel free to add yourself

**Comment by remyhaemmerle-da** [comment]
@S11001001 I will think about it :)

**Pull request merged**
