### PR TITLE
use .dars consistently in tests rather than .dalfs

### PR DESCRIPTION
**Pull request by francesco-da**
### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/docs/source/support/release-notes.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by cocreature** [comment]
There are still some tests that need fixing:
```
//language-support/scala/codegen-sample-app:tests
//language-support/scala/codegen-sample-app:daml-lf-codegen-sample-app_src
//language-support/scala/codegen-sample-app:ScalaCodeGenIT
//language-support/scala/codegen-sample-app:daml-lf-codegen-sample-app-testing
//language-support/scala/codegen-sample-app:daml-lf-codegen-sample-app
//language-support/scala/codegen-sample-app:MyMain-codegen-out.srcjar
//language-support/scala/codegen-sample-app:MyMain-codegen.srcjar
//language-support/scala/codegen-sample-app:MyMain-codegen
//language-support/scala/codegen-sample-app:MyMain.dalf
//language-support/scala/codegen-sample-app:MyMain
//extractor:extractor-scala-tests
//extractor:extractor-scala-tests_test_suite_src_test_suite_scala_com_digitalasset_extractor_TransactionSpec.scala
//extractor:extractor-scala-tests_test_suite_src_test_suite_scala_com_digitalasset_extractor_RecordsAndVariantsSpec.scala
//extractor:extractor-scala-tests_test_suite_src_test_suite_scala_com_digitalasset_extractor_OptionalSpec.scala
//extractor:extractor-scala-tests_test_suite_src_test_suite_scala_com_digitalasset_extractor_MapsSpec.scala
//extractor:extractor-scala-tests_test_suite_src_test_suite_scala_com_digitalasset_extractor_ListsSpec.scala
//extractor:extractor-scala-tests_test_suite_src_test_suite_scala_com_digitalasset_extractor_BasicPrimitiveTypesSpec.scala
//extractor:TransactionExample.dar
//extractor:TransactionExample
//extractor:PrimitiveTypes.dar
//extractor:PrimitiveTypes
```

**Comment by leo-da** [comment]
`language-support/scala/...` tests are being addressed as part of the: https://github.com/digital-asset/daml/pull/366

**Comment by bitonic** [comment]
@cocreature the extractor tests are fixed, and see #366 for the rest.

**Comment by cocreature** [comment]
@bitonic The extractor tests still reference the deprecated damlc see `bazel query "rdeps(//..., //daml-foundations/daml-tools/da-hs-damlc-app:da-hs-damlc-app-deprecated)"`. Looks like it should hopefully be quite easy to fix.

**Pull request merged**
