### PR TITLE
Update puppeteer for M1 support

### PR DESCRIPTION
**Pull request by aherrmann-da**
The puppeteer version that we pinned in the create-daml-app template was incompatible with M1. It wants to download a Chromium installation but assumes that none is available on M1 and fails. Later versions (^10.0.0) download an x86_64 release and rely on Rosetta. See https://github.com/puppeteer/puppeteer/issues/6622#issuecomment-906476717

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by aherrmann-da** [comment]
This turns into a bit of a rabbit whole. It seems that M1 requires a puppeteer update, which requires a react-script update, which implies a webpack update, which no longer includes shims for js builtins, which breaks create-(daml|react)-app, see https://github.com/facebook/create-react-app/issues/11756. I tried the proposed react-app-rewired fix, but the error remains
```
Module not found: Error: Can't resolve 'crypto' in '/private/var/folders/s6/2zfqcp895qd0bg00lzmdk7j80000gn/T/extra-dir-80150191221/not-create-daml-app/ui/node_modules/jwt-simple/lib'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
                                                                                                                                        
If you want to include a polyfill, you need to:                                                                                         
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'                               
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }                       
```
I'm not terribly familiar with these aspects of create-daml-app, so I might be holding it wrong.
Maybe someone more familiar with this could take a look at it? Perhaps @garyverhaegen-da or @robin-da?

**Comment by garyverhaegen-da** [comment]
I haven't really worked on create-daml-app recently but I'll try to take a look next week.

**Comment by aherrmann-da** [comment]
@garyverhaegen-da Did you have a chance to look into this?

**Comment by garyverhaegen-da** [comment]
> @garyverhaegen-da Did you have a chance to look into this?

Not yet, sorry.

**Comment by aherrmann-da** [comment]
> > @garyverhaegen-da Did you have a chance to look into this?
> 
> Not yet, sorry.

No worries, I understand there's lots to do.
I spoke with @adriaanm-da this morning and we agreed that it's best to just skip this test on M1 for now to unblock the M1 work.

**Comment by garyverhaegen-da** [comment]
So the problem right now seems to be that config-overrides is not being loaded at all. I'm trying to figure out how to tell webpack to load it but I'm not familiar with this tooling at all.

**Comment by aherrmann** [comment]
Thank you for digging into this!

> which isn't ideal. Given your chat with @adriaanm-da I'll leave it at that for now.

Sounds reasonable :+1:

**Comment by garyverhaegen-da** [comment]
Well, I'm not sure what happened here, but we're now running CI on m1 and these tests don't seem to fail. I've also just updated the create-daml-app tests to succeed on my m1 machine (#15031). So I'm going to assume this has somehow been solved upstream in the meantime and close this one.

**Pull request closed without merging**
