### PR TITLE
interfaces: LFConversion support for requires

### PR DESCRIPTION
**Pull request by sofiafaro-da**
Part of #11978.
Adds a test that "requires" is enforced.

changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by akrmn — COMMENTED** [review]
LGTM. 

I think this should work for transitive requirements, but could you please add a test to that effect?

**Review by akrmn — APPROVED** [review]

**Comment by sofiafaro-da** [comment]
> LGTM.
> 
> I think this should work for transitive requirements, but could you please add a test to that effect?

It's hard to test transitive requirements specifically at this point, when it comes to enforcing "requires". Suppose you have an interface C requires B, and B requires A. And you want template T to implement C. The only way for this to work is for T to implement B (since C requires B). But the only way for T to implement B is for T to also implement A (since B requires A). So in fact T implementing C requires T implementing A indirectly. So if you want to write a test for transitive requirements, it's just going to devolve into a test for normal requirement (like this one).

OTOH transitive requirements are kind of more difficult when it comes to dealing with methods and exercises on interfaces, and I'm worried that this will actually be a bit more difficult to solve. So I would leave a test of transitive requirements for later.

**Comment by akrmn** [comment]
Ah that's fair, I see what you mean about the transitive test just devolving into the test for normal requirements. We can take care of the methods and choices later. Thanks!

**Review by cocreature — APPROVED** [review]
Thanks!

**Pull request merged**
