### PR TITLE
Convert LSP tests

### PR DESCRIPTION
**Pull request by samuel-williams-da**
Addresses #16614 
Also potentially allows the tests to be run on windows, doing a 100x test run

### CODE REVIEW

**Comment by samuel-williams-da** [comment]
Ran the tests 100 times on windows, flaked 3 times, leaving the comment + `flaky = True` in

**Comment by akrmn** [comment]
> leaving the comment + `flaky = True` in

I don't see any bazel changes, and `runScripts` still skips the argument when `isWindows`. Perhaps you forgot to push one commit?

**Review by akrmn — APPROVED** [review]
LGTM, thank you @samuel-williams-da!

**Comment by samuel-williams-da** [comment]
Ah right, I did the test in a separate commit and reverted it, i expect the files to be unchanged, as they were flaky before and still are sadly

**Pull request merged**
