### PR TITLE
Add function version of infix operator `<&>` to DA.Functor

### PR DESCRIPTION
**Pull request by tmcgilchrist-da**
### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/unreleased.rst), if appropriate
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by tmcgilchrist-da** [comment]
@hurryabit sure if you want to keep that identifier free, from a Haskell perspective I thought having the infix version `<&>` it would follow to add the equivalent non-infix. 

It's definitely not `mapA` though a flipped version of that would be useful as well.

`mapA :: (Applicative m) => (a -> m b) -> [a] -> m [b]`
`mapA :: (Traversable t, Applicative f) => (a -> f b) -> t a -> f (t b)`

**Comment by ndmitchell** [comment]
I removed for leaving it to the base library. I still think that forM/mapM duality implies a for/map duality, but it's possible that forM/mapM duality is the mistake here.

**Comment by associahedron** [comment]
What would be least surprising for people coming from other functional programming languages? Let's see what other FP languages do.

-----------

Haskell

```
map :: (a -> b) -> [a] -> [b]Uses
base Prelude Data.List GHC.List GHC.OldList
map f xs is the list obtained by applying f to each element of xs, i.e., ...

for :: (Traversable t, Applicative f) => t a -> (a -> f b) -> f (t b)Uses
base Data.Traversable, ...
for is traverse with its arguments flipped. For a version that ignores the results see for_.

for_ :: (Foldable t, Applicative f) => t a -> (a -> f b) -> f ()Uses
base Data.Foldable, ...
for_ is traverse_ with its arguments flipped. For a version that doesn't ignore the results see for.
```

-----------

Idris:

```
Idris> :doc map
Prelude.Functor.map : Functor f => (func : a -> b) -> f a -> f b
    Apply a function across everything of type 'a' in a
    parameterised type
Idris> :doc for
Prelude.Traversable.for : Traversable t => Applicative f =>
    t a -> (a -> f b) -> f (t b)
    Like traverse but with the arguments flipped
Idris> :doc for_
Prelude.Traversable.for_ : Foldable t => Applicative f => t a ->
    (a -> f b) -> f ()
    Like traverse_ but with the arguments flipped
```

-----

Purescript:

```
map :: forall a b f. Functor f => (a -> b) -> f a -> f b

for :: forall a b m t. Applicative m => Traversable t => t a -> (a -> m b) -> m (t b)

   A version of traverse with its arguments flipped.

for_ :: forall a b f m. Applicative m => Foldable f => f a -> (a -> m b) -> m Unit

   A version of traverse_ with its arguments flipped.

```

-----

Elm: no typeclasses but `List.map`, `Maybe.map`, `Dict.map`, etc all exist without an accompanying `List.for`.

------

Conclusion: There is a broad consensus among FP languages that `for` is dual to `traverse`, and `for_` is dual to `traverse_`.  There is no `for / map` duality in general.

On this basis, I don't recommend adding `for` as a flipped counterpart to `map`.

In this light, perhaps it was a mistake for DAML to have `forA` and `forA_` as flipped versions of `mapA` and `mapA_`. Perhaps they should have been called `for` and `for_` instead.

**Comment by hurryabit** [comment]
I can see strong indicators that calling the function you want to add `for` might be the wrong thing _for the stdlib_. Thus, I reject this PR.
Despite this rejection, I'm thankful for your PR and would like to encourage you to make more contributions in the future.

**Pull request closed without merging**
