### PR TITLE
Merge conflicting release-notes.rst changes automatically

### PR DESCRIPTION
**Pull request by hurryabit**
... by keeping both entries.

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/docs/source/support/release-notes.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

---
This change is [Reviewable](https://reviewable.io/reviews/digital-asset/daml/893)

### CODE REVIEW

**Comment by bitonic** [comment]
from the docs

> Run 3-way file level merge for text files, but take lines from both versions, instead of leaving conflict markers. This tends to leave the added lines in the resulting file in random order and the user should verify the result. Do not use this if you do not understand the implications.

i'm not sure i _do_ understand the implications. does anybody here? @garyverhaegen-da , @moritzkiefer-da  maybe?

**Comment by garyverhaegen-da** [comment]
I'm a bit concerned that this will increase the likelihood of adding changes to the wrong release. How often do we have conflicts on the release notes? I've not seen one myself but I may be heavily biased on that front. I'm wondering if this is a problem that needs solving.

**Comment by garyverhaegen-da** [comment]
> from the docs
> 
> > Run 3-way file level merge for text files, but take lines from both versions, instead of leaving conflict markers. This tends to leave the added lines in the resulting file in random order and the user should verify the result. Do not use this if you do not understand the implications.
> 
> i'm not sure i _do_ understand the implications. does anybody here? @garyverhaegen-da , @moritzkiefer-da maybe?

I don't think there's anything magic beyond what is explained in the text: the resulting order may or may not be what you expect. I don't think that's an issue; I'm more concerned about the lack of human intervention for something that is exclusively going to be consumed by humans.

If we don't care about the order, and we really need to avoid conflicts, you could just have a changelog folder instead of a changelog file. Always add a new file, never remove one; creating a changelog between two versions becomes a simple git diff between two commits. Also no risk of having a changelog line in the wrong place.

**Comment by bethaitman** [comment]
In terms of the order - I'd expect that conflicts would usually be that two people have added a line to the top of the same list. In one list, it doesn't matter at all what the order is, because that's a list for one release. Unless I'm reasoning about this wrong?

In terms of @garyverhaegen-da's suggestion, that would mean that we'd need to process all those files into a release notes file before publishing the docs. I've worked with such a system before and it made release notes _much_ harder to understand and work with, so I'd rather not do that.

**Pull request merged**
