### PR TITLE
Release a new snapshot

### PR DESCRIPTION
**Pull request by cocreature**
Let’s see what I broke

changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by cocreature** [comment]
> Setting 'scala_2_13' to 'false'
bash is hard apparently

**Comment by cocreature** [comment]
> Setting 'scala_2_13' to 'true'

rebased on #8881, seems to work or at least get further now :crossed_fingers:

**Review by stefanobaghino-da — APPROVED** [review]

**Comment by stefanobaghino-da** [comment]
On `Agent: VSTS-WIN-M8M8`

> ERROR: D:/a/2/s/compiler/damlc/daml-ide-core/BUILD.bazel:11:19: output 'compiler/damlc/daml-ide-core/_obj/daml-ide-core/Development/IDE/Core/API.o' was not created

I guess it's safe to re-run (and the CI node to kill).

**Comment by cocreature** [comment]
killed the node and rebased on top of #8884

**Comment by cocreature** [comment]
manual tests passed on Linux and Windows.

**Pull request merged**
