### PR TITLE
kvutils: Improve submission performance.

### PR DESCRIPTION
**Pull request by SamirTalwar-DA**
We currently go through the following conversion process before submitting:

`DamlSubmission` → `Envelope` → `ByteString` → `Array[Byte]` → `Envelope` → `DamlSubmission`.

This is unnecessary, obviously, but is also expensive: parsing an envelope from a byte array is not cheap, especially when it involves decompression. (The compression, on the other hand, seems to be fine.)

This makes some changes to avoid all these hops, and passes the `DamlSubmission` directly to the `commit` function of a `LedgerWriter`.

I have changed `SubmissionValidator`’s method signatures to accept `submission: DamlSubmission` instead of `envelope: RawBytes` (where `type RawBytes = Array[Byte]`). If necessary, we can re-introduce the old method signatures, which would wrap the new methods, deserializing the submission and passing it through.

This will probably be easier to review if you inform GitHub that it should ignore whitespace changes.

### Changelog

- **[Ledger Integration Kit]** Performance improvements during submission.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by SamirTalwar-DA** [comment]
Even if we are sending it to another process or computer, the current way is very inefficient. We go from `DamlSubmission` → `Envelope` → `ByteString` → `Array[Byte]` → _wire_, when we could use `Envelope#writeTo` to avoid the latter two steps.

**Comment by gerolf-da** [comment]
Good point. @dajmaki, @miklos-da: could we get your take on this as well please?

**Comment by SamirTalwar-DA** [comment]
Closing this in favor of tackling bigger, better, more exciting problems.

**Comment by miklos-da** [comment]
> Even if we are sending it to another process or computer, the current way is very inefficient. We go from `DamlSubmission` → `Envelope` → `ByteString` → `Array[Byte]` → _wire_, when we could use `Envelope#writeTo` to avoid the latter two steps.

Yes, and because of that we are definitely going to remove the unnecessary step of `ByteString` → `Array[Byte]`. Further option would be to have the following signature for `LedgerWriter`:
```scala
  def commit(correlationId: String, envelope: ByteString.Output): Future[Unit]
```
or making `Envelope` an opaque object that contains the actual values and serializes/compresses on-demand (i.e., having methods to support zero-copy via `writeTo` or no serialization via `getValue`)

What do you think?

**Comment by SamirTalwar-DA** [comment]
Regarding the conversion to `ByteString`, yes, I think it's a great idea. If `Envelope` could avoid copying entirely, even better; it would save a lot of energy in _ledger-on-sql_.

**Pull request closed without merging**
