### PR TITLE
Remove daml-script json support

### PR DESCRIPTION
**Pull request by samuel-williams-da**
Remove Json support from daml2-script and daml3-script, along side the flags.
More complete forward port of #18500

### CODE REVIEW

**Review by remyhaemmerle-da — APPROVED** [review]
:fire:

**Comment by samuel-williams-da** [comment]
Export is failing to compile, just going to wait for https://github.com/digital-asset/daml/pull/18492 to merge

**Comment by garyverhaegen-da** [comment]
To clarify, this is JSON support as in "talking to the JSON API instead of the Ledger API", right? This isn't removing the `--input-file` and `--output-file` flags?

**Comment by samuel-williams-da** [comment]
Exactly yes, those flags still exist

**Pull request merged**
