### PR TITLE
Fix indent that creates an unneeded subparagraph

### PR DESCRIPTION
**Pull request by cgrigis-da**
The [Getting Started doc](https://docs.daml.com/getting-started/installation.html#mac-and-linux) incorrectly shows a subparagraph in the middle of a sentence.

CHANGELOG_BEGIN
CHANGELOG_END

### CODE REVIEW

**Review by stefanobaghino-da — APPROVED** [review]
### Before

before

### After

after

**Review by carrielaben-da — APPROVED** [review]
Looks good

**Comment by stefanobaghino-da** [comment]
@cgrigis-da You need to add a changelog entry to a commit body (not in the PR description) as described in the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md#pull-request-checklist). If you make your changes as a branch of this repo instead of your own, you will trigger CI automatically (provided that you have write access to the repo). If you don't, I believe @garyverhaegen-da can help you.

**Comment by cgrigis-da** [comment]
Aha, thank you!

**Pull request merged**
