### PR TITLE
Add groupContiguous method

### PR DESCRIPTION
**Pull request by stefanobaghino-da**
This will later be used to group together events from the database, sorted by transaction identifier, into transactions.

changelog_begin
changelog_end

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by stefanobaghino-da** [comment]
@gabor-aranyossy I think we spoke about something like this once. :wink:

**Comment by gabor-aranyossy** [comment]
@stefanobaghino-da  Might be, in what context? It looks handy btw. Have you considered having an optional upper limit for the size of Vector?

**Comment by stefanobaghino-da** [comment]
> @stefanobaghino-da Might be, in what context? It looks handy btw.

I don't know exactly, but I remember you asking about something like this (and then probably changing approach).

> Have you considered having an optional upper limit for the size of Vector?

Not really, if it was for general consumption it would probably make sense but in this case it's important that we keep grouped results together. Thanks for the feedback though!

**Comment by gabor-aranyossy** [comment]
It rings a bell actually.. I'll keep this approach in mind. Thanks!

**Pull request merged**
