### PR TITLE
Up-(actually down-)grade to ghc-lib-8.8.0.20190610

### PR DESCRIPTION
**Pull request by shayne-fletcher-da**
In this PR, we switch to `ghc-lib-8.8.0.20190610` compatible with GHC `8.8.1`.

### CODE REVIEW

**Comment by shayne-fletcher-da** [comment]
Frustratingly, out of all tests there is one error. From `//daml-foundations/daml-ghc/test-src/DA/Test/ShakeIDEClient.hs`:
```
    ,    testCase' "Cross-package goto definition" $ do
            foo <- makeModule "Foo"
                [ "test = scenario do"
                , "  p <- getParty \"Alice\""
                , "  pure ()"
                ]
            setFilesOfInterest [foo]
            expectNoErrors
            expectGoToDefinition (foo, 3, [7..14]) (In "DA.Internal.LF")
 ```
I tried running it up in a `daml-sdk-head` build. I find that goto definition on `getParty` and `pure` are returning "No definition".

Looking into the code some @rohanjr-da and I suppose this code is involved `//compiler/haskell-ide-core/src/Development/IDE/Functions/`:
```
        getSpan (Named name) = case nameSrcSpan name of
            sp@(RealSrcSpan _) -> pure $ Just sp
            UnhelpfulSpan _ -> runMaybeT $ do
                -- This case usually arises when the definition is in an external package.
                -- In this case the interface files contain garbage source spans
                -- so we instead read the .hie files to get useful source spans.
                let mod = nameModule name
                let unitId = moduleUnitId mod
                pkgConfig <- MaybeT $ pure $ lookupPackageConfig unitId pkgState
                hiePath <- MaybeT $ liftIO $ optLocateHieFile optPkgLocationOpts pkgConfig mod
                hieFile <- MaybeT $ use (GetHieFile hiePath) ""
                avail <- MaybeT $ pure $ listToMaybe (filterAvails (eqName name) $ hie_exports hieFile)
                srcPath <- MaybeT $ liftIO $ optLocateSrcFile optPkgLocationOpts pkgConfig mod
                -- The location will point to the source file used during compilation.
                -- This file might no longer exists and even if it does the path will be relative
                -- to the compilation directory which we don’t know.
                let span = setFileName srcPath $ nameSrcSpan $ availName avail
                pure span
```

When I compare the `da-unit-ids-8.8.1` branch with `ghc-8.8.1-alpha1` I see:
```
shaynefletcher:ghc ((1c53f5ee46...) *)$ git diff ghc-8.8.1-alpha1 upstream/da-unit-ids-8.8.1
diff --git a/compiler/basicTypes/Module.hs b/compiler/basicTypes/Module.hs
index 45fd4c19b5..840a29e9cd 100644
--- a/compiler/basicTypes/Module.hs
+++ b/compiler/basicTypes/Module.hs
@@ -1088,10 +1088,10 @@ See Note [The integer library] in PrelNames.
 integerUnitId, primUnitId,
   baseUnitId, rtsUnitId,
   thUnitId, mainUnitId, thisGhcUnitId, interactiveUnitId  :: UnitId
-primUnitId        = fsToUnitId (fsLit "ghc-prim")
-integerUnitId     = fsToUnitId (fsLit "integer-wired-in")
+primUnitId        = fsToUnitId (fsLit "daml-prim")
+integerUnitId     = primUnitId
    -- See Note [The integer library] in PrelNames
-baseUnitId        = fsToUnitId (fsLit "base")
+baseUnitId        = primUnitId
 rtsUnitId         = fsToUnitId (fsLit "rts")
 thUnitId          = fsToUnitId (fsLit "template-haskell")
 thisGhcUnitId     = fsToUnitId (fsLit "ghc")
```
which looks correct no?

Pretty stuck :(

@robin-da do you have any ideas what's going wrong?

**Comment by shayne-fletcher-da** [comment]
There's more. On the `ghc-8.8.1-alpha1` branch, the additional field `ml_hie_file` in `data ModLocation` (https://gitlab.haskell.org/ghc/ghc/blob/ghc-8.8.1-alpha1/compiler/basicTypes/Module.hs) exists.

So, this code in `//compiler/haskell-ide-core/src/Development/IDE/Functions/Compile.hs`
```
#ifndef GHC_STABLE
          , ml_hie_file = replaceExtension fp "hie"
#endif
```
has to become just,
```
          , ml_hie_file = replaceExtension fp "hie"
```.

Doing a `/usr/bin/find . -name "*.hie"` from `//` returns no files so I guess HIE file generation isn't working. @neil-da is this mechanism something you know about?

**Comment by shayne-fletcher-da** [comment]
Update : Making `ml_hie_file` appear unconditionally breaks `haskell-ide-core/package_env_haskell-ide-core-public`. Reverting.

**Comment by neil-da** [comment]
@cocreature added the HIE files to do goto definition properly. They aren't supported in 8.8. Removing them is frustrating, but I can't think of a better solution - this might kick out cross module goto definition...

**Comment by cocreature** [comment]
I am slightly confused. It sounds like there is some support for HIE files but it doesn’t work properly?

**Comment by shayne-fletcher-da** [comment]
@moritzkiefer-da It looks that way. Some sort of funny in-between state.

**Pull request merged**
