### PR TITLE
Haskell SdkVersion inversion

### PR DESCRIPTION
**Pull request by akrmn**
This PR tries to enable more shared cache hits by moving `//:sdk-version-hs-lib` off the bottom of the dependency tree. This is important because during PR builds, the versions defined in this package are all `0.0.0`, but on ~`main` builds~ release builds on the `main` branch, the values are instead defined in terms of the daily snapshot. This means that all the packages that depend on `//:sdk-version-hs-lib` need to be rebuilt during `main` builds, even if the only thing that actually changed was the version string.

The way this PR achieves that is by splitting `//:sdk-version-hs-lib` into two packages. The first package is `//sdk-version/hs:sdk-version-class-lib`, which defines a module `SdkVersion.Class` with a nullary (0-argument) type class `SdkVersioned` and the expressions from `//:sdk-version-hs-lib`, except with an `SdkVersioned` constraint. This means that all use sites of the former `//:sdk-version-hs-lib` now propagate that constraint. Crucially, this package does not depend on the actual values from `load("@build_environment//:configuration.bzl", "ghc_version", "mvn_version", "sdk_version")`.

The second package is `//sdk-version/hs:sdk-version-lib`. It defines a module `SdkVersion` which reexports `SdkVersion.Class` and defines the function `withSdkVersions :: (SdkVersioned => r) -> r`. This function discharges the `SdkVersioned` constraint by providing the actual values from `@build_environment//:configuration.bzl`.

The idea is that our libraries should exclusively use `//sdk-version/hs:sdk-version-class-lib`, thus propagating the `SdkVersioned` constraint. `//sdk-version/hs:sdk-version-lib` should only be used at top level executables and tests to provide the actual values.

With this in mind, the changes in this PR boil down to:
1. Removing `//:sdk-version-hs-lib`.
2. Defining `//sdk-version/hs:sdk-version-class-lib` and `//sdk-version/hs:sdk-version-lib`.
3. Adjusting imports in libraries (`import SdkVersion => import SdkVersion.Class`) and propagating `SdkVersioned` constraints.
4. Discharging the `SdkVersioned` constraints using `withSdkVersions`.

3 and 4 are about 90% of the diff, so the diff isn't really as bad as it looks

## January 2024 update:
After the changes described above, two of our haskell libraries with generated cabal files had `sdk-version-class-lib` as a dependency, namely `//libs-haskell/da-hs-base` and `//daml-assistant:daml-project-config`. Since, in my opinion, it does not make sense to make `sdk-version-class-lib` available as a cabal project, I instead opted to move out the parts of these two libraries that used `SdkVersioned`:
* I extracted the GCP logger logic from `//libs-haskell/da-hs-base` (the only use site of `SdkVersioned`) into a new library `//libs-haskell/da-gcp-logger`.
* In the case of `//daml-assistant:daml-project-config`, the only use of `SdkVersioned` was in the definition of `unresolvedBuiltinSdkVersion`, so I moved `unresolvedBuiltinSdkVersion` into `//sdk-version/hs:sdk-version-class-lib`. Then, instead of having `//sdk-version/hs:sdk-version-class-lib` depend on the entire `//daml-assistant:daml-project-config`, I moved the versioning data types from `//daml-assistant:daml-project-config` into a new library `//libs-haskell/da-version-types`. This new library does not depend on `sdk-version-class-lib` and it's reexported by `//daml-assistant:daml-project-config`. I've also added a generated cabal file for it in case someone out there was using the one for `daml-project-config`.

### CODE REVIEW

**Comment by akrmn** [comment]
test failures:
* `//daml-assistant:daml-project-config-cabal-file-matches`: it's simple to update the golden cabal file, but I need to look into the implications of adding a dependency on `//sdk-version/hs:sdk-version-class-lib`, since any consumers of this cabal file will also need the packaged version of that. It might be possible and preferable to remove the dependency altogether.
* `//libs-haskell/da-hs-base:da-hs-base-cabal-file-matches`: as above
* `//libs-haskell/da-hs-base:da-hs-base-telemetry-tests`: looks like a flake

**Review by garyverhaegen-da — APPROVED** [review]
Fully support this. Thanks a lot!

The caching situation is a tiny bit more nuanced though: most main commit builds still build with `0.0.0`. Only the release builds change the version.

Also, Windows is, as usual, special in a complicated and brittle way: because of various quirks (on the Bazel side: that the cache key on Windows depends on the full path; on the Azure Pipelines side: that the full path depends on the pipeline being run), main branch builds and PR builds never share a cache for Windows. (unless that's been changed in Bazel 5, I haven't checked since the upgrade.)

**Comment by akrmn** [comment]
> Fully support this. Thanks a lot!

:bow:

> The caching situation is a tiny bit more nuanced though: most main commit builds still build with `0.0.0`. Only the release builds change the version.

thanks for the nuance, I've updated the description

> Also, Windows is, as usual, special in a complicated and brittle way: because of various quirks (on the Bazel side: that the cache key on Windows depends on the full path; on the Azure Pipelines side: that the full path depends on the pipeline being run), main branch builds and PR builds never share a cache for Windows. (unless that's been changed in Bazel 5, I haven't checked since the upgrade.)

ah yes, I'm ignoring the Windows quirks for now. The idea is that if this works for Linux/macOS, it should also work for Windows _once those quirks get (🔮🪄) fixed_

**Comment by dylant-da** [comment]
Very cool! Seconding Sam's comment :D

**Review by dylant-da — APPROVED** [review]

**Pull request merged**
