### PR TITLE
Update nix to include bazel fix for Monterey

### PR DESCRIPTION
**Pull request by nicu-da**
Includes this fix: https://github.com/NixOS/nixpkgs/pull/147097

Graphviz_2.32 was removed https://github.com/NixOS/nixpkgs/pull/147397

changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by nicu-da** [comment]
> Looks like CI is failing due to a bunch of other changes

Yup, trying to figure them out now

**Comment by nicu-da** [comment]
@cocreature 

Tried to get a working state locally but failed miserably. 
The main issue is the following: 

```
ERROR: Could not find a version that satisfies the requirement importlib-metadata<4.3; python_version < "3.8" (from flake8) (from versions: none)
ERROR: No matching distribution found for importlib-metadata<4.3; python_version < "3.8"
error: builder for '/nix/store/1xd6c4qp969gaikjl9lvq302m4qamzlf-python3.7-flake8-4.0.1.drv' failed with exit code 1;
       last 10 log lines:
       > removing build/bdist.linux-x86_64/wheel
       > Finished executing setuptoolsBuildPhase
       > installing
       > Executing pipInstallPhase
       > /build/flake8-4.0.1/dist /build/flake8-4.0.1
       > Processing ./flake8-4.0.1-py2.py3-none-any.whl
       > Requirement already satisfied: pycodestyle<2.9.0,>=2.8.0 in /nix/store/jdyqbvq2qf66z2qbsn3g592wvxlk2yk9-python3.7-pycodestyle-2.8.0/lib/python3.7/site-packages (from flake8==4.0.1) (2.8.0)
       > Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in /nix/store/jsy8z0nkh83fnhx6r42ym7qvcxk1ri27-python3.7-mccabe-0.6.1/lib/python3.7/site-packages (from flake8==4.0.1) (0.6.1)
       > ERROR: Could not find a version that satisfies the requirement importlib-metadata<4.3; python_version < "3.8" (from flake8) (from versions: none)
       > ERROR: No matching distribution found for importlib-metadata<4.3; python_version < "3.8"
       For full logs, run 'nix log /nix/store/1xd6c4qp969gaikjl9lvq302m4qamzlf-python3.7-flake8-4.0.1.drv'.
```

I tried to overwrite `importlib-metadata` version which is defined by nixpkgs with `4.2.0` but that failed.

I did manage to make it run locally, but that was by removing `flake8` from the dependencies. I did not find any usage of it, but I would assume it's used. For now, that works locally for me at least, but would appreciate any help in moving this forward.

**Comment by cocreature** [comment]
> I did manage to make it run locally, but that was by removing `flake8` from the dependencies. I did not find any usage of it, but I would assume it's used. For now, that works locally for me at least, but would appreciate any help in moving this forward.

generally my assumption for this type of stuff is that if CI passes, drop it.

**Comment by nicu-da** [comment]
> > I did manage to make it run locally, but that was by removing `flake8` from the dependencies. I did not find any usage of it, but I would assume it's used. For now, that works locally for me at least, but would appreciate any help in moving this forward.
> 
> generally my assumption for this type of stuff is that if CI passes, drop it.

That sounds good to me as well. Will give it a shot

**Review by cocreature — APPROVED** [review]
Thanks!

**Comment by nicu-da** [comment]
Windows and macOS build seem to be okay-ish.
There's one roadblock for Linux, caused by

```
ERROR: /home/vsts/.cache/bazel/_bazel_vsts/d5c8b3f1185416e5207d53317d3a7876/external/grpc_nix/BUILD:3:11: SolibSymlink _solib_k8/_U@grpc_Unix_S_S_Cgrpc_Ulib___Ulib/libgrpc.so.19.0.0 failed: missing input file 'external/grpc_nix/lib/libgrpc.so.19.0.0', owner: '@grpc_nix//:lib/libgrpc.so.19.0.0'
ERROR: /home/vsts/.cache/bazel/_bazel_vsts/d5c8b3f1185416e5207d53317d3a7876/external/grpc_nix/BUILD:3:11 SolibSymlink _solib_k8/_U@grpc_Unix_S_S_Cgrpc_Ulib___Ulib/libgrpc.so.19.0.0 failed: 1 input file(s) do not exist
```

trying to figure out what changed

**Comment by cocreature** [comment]
> trying to figure out what changed

almost certainly a newer version, there are a few things that need updating for that:
1. We’ll have to bump the grpc version in `deps.bzl` to match the nix version 
2. We have to change the `srcs` for `grpc_nix` in `WORKSPACE`
3. We have to adapt the `patchelf` call in `bazel-haskell-deps.bzl` to the new version.

Thinking about this, we could probably try to reduce this to a single version number but grpc upgrades are also fairly rare so not super high prio imho.

**Review by cocreature — APPROVED** [review]
grpc upgrade looks good :+1:

**Pull request merged**
