### PR TITLE
Regularize scala mod-parser syntax for controllers

### PR DESCRIPTION
**Pull request by nickchapman-da**
Regularize scala mod-parser syntax for controllers in preparation for adding choice-observers.

From keyword "by" to identifier "controllers" + leading ","

changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by remyhaemmerle-da — APPROVED** [review]
This looks reasonable. We may have to check with kv team if they are using the parser.

**Comment by nickchapman-da** [comment]
> This looks reasonable. We may have to check with kv team if they are using the parser.

They are. I fixed the place I found

**Review by hurryabit — COMMENTED** [review]
Looks reasonable. Thank you.

**Comment by remyhaemmerle-da** [comment]
> > This looks reasonable. We may have to check with kv team if they are using the parser.
> 
> They are. I fixed the place I found

I meant, if they are using the parser _outside the main repo_.
I checked, they don't, so all good.

**Pull request merged**
