### PR TITLE
Fix pip and pipenv

### PR DESCRIPTION
**Pull request by aherrmann-da**
Since the latest nixpkgs update pip is no longer contained in the python
derivation but instead in its own `python37Packages.pip` derivation.

Additionally the pipenv version in nixpkgs is incompatible with the pip
version, as pipenv expects a module to be present which is only
available in later versions. This change overrides pip with a version
update to fix this issue.

Upstream nixpkgs has [already updated pip accordingly](https://hydra.nixos.org/build/104243425)

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/unreleased.rst), if appropriate
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by aherrmann-da** [comment]
@cocreature I think I got the same Nix build failure on macOS multiple times in a row. It might be a question of waiting for hydra/nixpkgs to catch up on macOS.

**Comment by cocreature** [comment]
@aherrmann-da It looks like it should already be fixed in the latest `nixpkgs`, see https://github.com/NixOS/nixpkgs/commit/efce3c1367d1b3227cef8854d520d888d9c482d1

**Comment by aherrmann-da** [comment]
@cocreature Thanks for looking it up. I've bumped the revision to include that fix and also rebased on master.

**Pull request merged**
