### PR TITLE
fix h2 ledger entries not null constraint check

### PR DESCRIPTION
**Pull request by davidpadbury-da**
### Description

I'm adding support in canton for running the ledger-api against postgres and [found some of our tests failed on the ledger_entries transaction constraint](https://github.com/digital-asset/daml/blob/02186ef06869a198051371453860e6e1ef2e3568/ledger/sandbox/src/main/resources/db/migration/postgres/V1__Init.sql#L43-L44) (in this scenario command id and app id were null). Wondered why it didn't impact us when running on the h2 version (our current setup). Found that the constraint in the h2 setup is using `field != null` which will always return true (`null != null` is `true` in sql).

Suggesting this change to make consistent.

Added @oliverse-da for heads up as we probably have to address something canton side once the constraints are correctly applied.

### Pull Request Checklist

- [X] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [X] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [X] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags, if appropriate
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by stefanobaghino-da** [comment]
Oh. Wow. That's unexpected.

giphy

Thanks!

**Comment by stefanobaghino-da** [comment]
By the way, I just noticed there is no changelog entry for this. It's perhaps worth mentioning the solved bug. The new procedure is described [here](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md#pull-request-checklist).

**Comment by davidpadbury-da** [comment]
oh right. it's a migration so can't just go update it 🤦‍♂

**Comment by davidpadbury-da** [comment]
thanks @stefanobaghino-da. will add.

**Comment by davidpadbury-da** [comment]
Added a changelog entry for sandbox in the commit message and have added the fix as a new h2 migration with checksum. 

I'm honestly a little wary of addressing this way as any existing data not conforming to the check will cause the migration to fail. If it's only us (canton) using h2 and therefore no existing h2 databases to migrate, it may be better just to patch the original migration file. Let me know what you think. Am in no hurry to get this merged.

**Comment by davidpadbury-da** [comment]
Now I dig into this a little on our side, I'm wondering if the checks should be there at all. The issue seems to be that the `application_id`, `command_id`, and `submitter` are required to write a transaction to the `ledger_entries` table.

However the entry is being generated from a [TransactionAccepted](https://github.com/digital-asset/daml/blob/master/ledger/participant-state/src/main/scala/com/daml/ledger/participant/state/v1/Update.scala#L192-L201) value which states that the [submitter info (which holds these fields) can be elided when we're on a participant that does not host the submitter](https://github.com/digital-asset/daml/blob/master/ledger/participant-state/src/main/scala/com/daml/ledger/participant/state/v1/Update.scala#L162-L166). This happens to be exactly the scenario I'm hitting.

Should the checks include `application_id`, `command_id` and `submitter` at all? (or perhaps could be modified to if any are specified then all should be?)

**Comment by oliverse-da** [comment]
> Now I dig into this a little on our side, I'm wondering if the checks should be there at all. The issue seems to be that the `application_id`, `command_id`, and `submitter` are required to write a transaction to the `ledger_entries` table.
> 
> However the entry is being generated from a [TransactionAccepted](https://github.com/digital-asset/daml/blob/master/ledger/participant-state/src/main/scala/com/daml/ledger/participant/state/v1/Update.scala#L192-L201) value which states that the [submitter info (which holds these fields) can be elided when we're on a participant that does not host the submitter](https://github.com/digital-asset/daml/blob/master/ledger/participant-state/src/main/scala/com/daml/ledger/participant/state/v1/Update.scala#L162-L166). This happens to be exactly the scenario I'm hitting.
> 
> Should the checks include `application_id`, `command_id` and `submitter` at all? (or perhaps could be modified to if any are specified then all should be?)

Your observation is correct @davidpadbury-da: non-submitting participants will not have "SubmitterInfo" set, and we are only seeing this in Canton as that is currently the only multi-participant environment that we test. Therefore this constrained should be loosened on Postgres as well - perhaps as you suggest by requiring all of the fields or none of them to be there.

**Comment by davidpadbury-da** [comment]
Closed in favor of #3970 that loosens the postgres schema to support optional submitter metadata while correcting the h2 schema check.

**Pull request closed without merging**
