### PR TITLE
Remove 'daml 1.2' from DAML source files

### PR DESCRIPTION
**Pull request by shayne-fletcher**
This PR does a bulk removal of `daml 1.2` from all DAML source files (excepting `compiler/damlc/tests/daml-tests/files/DamlHasVersion.daml` which we keep to make sure that the version prelude may optionally be present).

### CODE REVIEW

**Comment by shayne-fletcher** [comment]
> I would prefer to remove lines containing only `daml 1.2` entirely rather than replacing them with an empty line. The two empty lines at the top of many files look somewhat suspicious. I suppose that's something we can't really do in a follow-up PR since the markers for where to remove the empty lines will be gone.

If we do that there will be follow up work painfully adjusting line numbers in tests checking for errors that are now off by one.

**Comment by shayne-fletcher** [comment]
> Thanks! Can we please get a changelog entry that mentions that this is now optional?

I can. I left it out because @hurryabit suggested he wanted to keep it quiet for the moment while considering the communications strategy. I'll put a changelog note in.

**Comment by hurryabit** [comment]
> I can. I left it out because @hurryabit suggested he wanted to keep it quiet for the moment while considering the communications strategy. I'll put a changelog note in.

If we only say, that the `daml 1.2` pragma is now optional, were good in terms of comms strategy.

**Comment by shayne-fletcher** [comment]
Revised `daml-prim-src`, `daml-stdlib` and docs DAML files so that the `daml 1.2` lines are *deleted*.

**Comment by shayne-fletcher** [comment]
It turns out it is wrong to delete the `daml 1.2` lines under `docs`. This induces a multitude of changes in the `.rst` files that are tied to specific spans. Reverting to replacing with an empty line.

**Comment by hurryabit** [comment]
> It turns out it is wrong to delete the `daml 1.2` lines under `docs`. This induces a multitude of changes in the `.rst` files that are tied to specific spans. Reverting to replacing with an empty line.

Oh damn. Do some snippets still get included by line numbers rather than begin/end comments?That's very unfortunate.

**Comment by cocreature** [comment]
> Oh damn. Do some snippets still get included by line numbers rather than begin/end comments?That's very unfortunate.

At least the current quickstart uses line numbers everywhere.

**Pull request merged**
