### PR TITLE
reduce default concurrency of api-test-tool

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
This PR makes two small (?) changes to the Ledger API Test Tool. First, it realizes the original intention that tests should run in a randomized order, by explicily shuffling the list of tests (after selection through include/exclude etc.). The existing implementation relies on the ordering of `Map#values`, which, while not obviously connected to either insertion order or sort order on the keys, is nonetheless deterministic and hence results in all our tests always running in the same order (for the same selection).

Second, because shuffling the tests results in a very flaky build, this PR reduces the default concurrency from "as many threads as there are CPU cores on this machine" to 1. On my machine this reduces the performance of `//ledger/sandbox:conformance-test-static-time-h2database` from running in about 30 seconds to running in about 55 seconds, so this is definitely not negligible. However, trying to run with concurrency 2 on my machine yields a failure rate of about 20%, whereas setting concurrency to 1 succeeded 40 times in a row.

I believe the underlying issue is that, after the test tool has been implemented, the ledger API has been enhanced to support backpressure. This is, in general, a good thing, but the test tool has apparently not been updated to take it into account (say, with appropriate retry strategies). Implementing that would be better than limiting concurrency, but it would also be significantly more effort for me.

CHANGELOG_BEGIN
- [Ledger API Test Tool] Change default concurrency from "number of cores" to 1. You can still set explicit concurrency settings with ``--concurrent-test-runs INT``.
CHANGELOG_END

### CODE REVIEW

**Comment by garyverhaegen-da** [comment]
Apologies for not providing more context. This is meant as a step to reduce the uncertainty around #6314; in particular, I want to point out that #6314 has _not_ been merged yet, so there is no change in `ExecutionContext`s here. The only change is to shuffle the tests, and that is enough to observe the same level of flakiness I observed in #6314 (which obviously does not necessarily mean this is the _only_ source of flakiness added by #6314, but we can at least attempt to fix this one first).

I agree limiting concurrency is not a great option, and I'm happy to work on a better approach, but I'll need more guidance on how this is all fitting together. In particular, I was not able to find a good place in the code to throttle on the number of calls to the ledger API.

**Comment by cocreature** [comment]
@garyverhaegen-da can you reproduce the flakiness with shuffling but not limiting the concurrency limit locally? I just ran `//ledger/ledger-on-memory:conformance-test` and `//ledger/sandbox:next-conformance-test-wall-clock-time-memory` 50 times with the same shuffling as this PR but the old concurrency limit and I didn’t get a single failure.

**Comment by garyverhaegen-da** [comment]
> @garyverhaegen-da can you reproduce the flakiness with shuffling but not limiting the concurrency limit locally? I just ran `//ledger/ledger-on-memory:conformance-test` and `//ledger/sandbox:next-conformance-test-wall-clock-time-memory` 50 times with the same shuffling as this PR but the old concurrency limit and I didn’t get a single failure.

Yes. On my machine, adding the shuffling makes it flaky, adding the concurrency limit removes the flakiness.

**Comment by cocreature** [comment]
> Yes. On my machine, adding the shuffling makes it flaky, adding the concurrency limit removes the flakiness.

Interesting, maybe worth seeing on this PR what level of flakiness we get on CI if you just change `build.sh` to run those tests 50 times so we have something remotely reproducible?

**Comment by stefanobaghino-da** [comment]
It could be useful to keep track of explicitly using a seed when shuffling and keeping track what seed and ordering triggers the flakiness (the order could be enough, I would recommend using the seed in case we want to easily reproduce a given order without necessarily having to recompile the tests). As I mentioned, even with 8 test cases running in parallel, there should be no more than a few dozen outstanding commands, far away from the default threshold for back-pressure.

**Comment by stefanobaghino-da** [comment]
> it realizes the original intention that tests should run in a randomized order

It was not. The only intent was to not guarantee any order.

**Comment by stefanobaghino-da** [comment]
Given the different results that you two are getting, it would be probably also helpful to understand how you are testing it. We have multiple conformance tests and each of those can have a different behavior.

**Comment by garyverhaegen-da** [comment]
> > it realizes the original intention that tests should run in a randomized order
> 
> It was not. The only intent was to not guarantee any order.

Ah, sorry, it looks like I misunderstood. I still think guaranteeing that order does not matter is better than not guaranteeing the order, but if you disagree I can drop this and work on something else.

**Comment by stefanobaghino-da** [comment]
> > > it realizes the original intention that tests should run in a randomized order
> > 
> > 
> > It was not. The only intent was to not guarantee any order.
> 
> Ah, sorry, it looks like I misunderstood. I still think guaranteeing that order does not matter is better than not guaranteeing the order, but if you disagree I can drop this and work on something else.

I don't think it's bad to have this, as it highlights possible issues as you are doing right now. It was just to clarify that the intent was not to have tests run in any specific order, not even shuffled. :slightly_smiling_face: 

I'm running a test similar to the one Moritz did (running `//ledger/ledger-on-memory:conformance-test` 50 times, but I hardcoded the concurrency to 8) and I also haven't seen any failure. Out of curiosity, if you open a Scala shell, what does `Runtime.getRuntime.availableProcessors()` return?

**Comment by garyverhaegen-da** [comment]
> Out of curiosity, if you open a Scala shell, what does `Runtime.getRuntime.availableProcessors()` return?

8.

**Comment by cocreature** [comment]
Looking at the CI failures it only seems to affect sandbox-classic and indeed I can reproduce it there!

For `//ledger/sandbox:conformance-test-wall-clock-postgresql` I get 2/20 failures after adding the shuffle with no other change.

**Comment by garyverhaegen-da** [comment]
I ran the following on CI:
```
      - bash: |
          set -euo pipefail
          eval "$(dev-env/bin/dade-assist)"
          bazel test -t- --runs_per_test=50 //ledger/sandbox:conformance-test-static-time-h2database
          sed -i 's/concurrentTestRuns = 1,/concurrentTestRuns = Runtime.getRuntime.availableProcessors(),/' ledger/ledger-api-test-tool/src/main/scala/com/daml/ledger/api/testtool/Config.scala
          bazel test -t- --runs_per_test=50 //ledger/sandbox:conformance-test-static-time-h2database
```
on both Linux and macOS. For both, the first pass (which has shuffling but no concurrency) succeeded 50 times. On Linux, the results of the second pass were
```
2020-06-17T11:29:01.8623799Z //ledger/sandbox:conformance-test-static-time-h2database                 FAILED in 17 out of 50 in 37.0s
2020-06-17T11:29:01.8625359Z   Stats over 50 runs: max = 37.0s, min = 27.2s, avg = 32.5s, dev = 1.9s
```
and on macOS:
```
2020-06-17T11:28:08.6111550Z //ledger/sandbox:conformance-test-static-time-h2database                 FAILED in 30 out of 50 in 38.2s
2020-06-17T11:28:08.6112110Z   Stats over 50 runs: max = 38.2s, min = 19.9s, avg = 32.0s, dev = 3.2s
```
Full logs: [Linux](https://github.com/digital-asset/daml/files/4792266/144.txt), [macOS](https://github.com/digital-asset/daml/files/4792268/139.txt).

So I guess it's not specific to my machine, but it may not affect all the tests that rely on the ledger test tool.

I'll keep digging into specific orders as @stefanobaghino-da suggested.

**Comment by stefanobaghino-da** [comment]
I noticed that we have test suites in which e.g. `LotsOfParties` seems to not be ran separately. I'll dig into that.

**Comment by garyverhaegen-da** [comment]
> I noticed that we have test suites in which e.g. `LotsOfParties` seems to not be ran separately. I'll dig into that.

That does deem to be the intention of this (`//ledger/sandbox:conformance-test-static-time-h2database`) [test](https://github.com/digital-asset/daml/blob/master/ledger/sandbox/BUILD.bazel#L393):
```
    test_tool_args = [
        "--open-world",
        "--all-tests",
        "--exclude=ConfigManagementServiceIT",
        "--exclude=ClosedWorldIT",
    ],
```
`LotsOfParties` is a non-default test but not a perf one so it will be run together with the other ones if selected through `--all-tests` or `--include`.

**Comment by stefanobaghino-da** [comment]
> > I noticed that we have test suites in which e.g. `LotsOfParties` seems to not be ran separately. I'll dig into that.
> 
> That does deem to be the intention of this (`//ledger/sandbox:conformance-test-static-time-h2database`) [test](https://github.com/digital-asset/daml/blob/master/ledger/sandbox/BUILD.bazel#L393):
> 
> ```
>     test_tool_args = [
>         "--open-world",
>         "--all-tests",
>         "--exclude=ConfigManagementServiceIT",
>         "--exclude=ClosedWorldIT",
>     ],
> ```
> 
> `LotsOfParties` is a non-default test but not a perf one so it will be run together with the other ones if selected through `--all-tests` or `--include`.

Precisely what I'm looking into right now. Feel free to work on it yourself. The `--all-tests` is a legacy of the past when only `SemanticTests` was run by default. I would recommend running only the default tests (i.e. removing `--all-tests` and `--exclude`s and having individual runs for optional tests (there should be already examples on how we do that for `ConfigurationManagement`.

**Comment by cocreature** [comment]
Closing since we worked around the issue by fixing the order for now. We probably should still investigate the flakiness at some point however. Feel free to reopen if you still plan to make this change.

**Comment by garyverhaegen-da** [comment]
I was actually keeping this open as a reminder that we should still investigate why changing the order makes it flaky. I still believe the test tool should randomize test orders, but I've been convinced reducing the concurrency is not the appropriate fix.

**Comment by stefanobaghino-da** [comment]
> I was actually keeping this open as a reminder that we should still investigate why changing the order makes it flaky. I still believe the test tool should randomize test order, but I've been convinced reducing the concurrency is not the appropriate fix.

I added https://github.com/digital-asset/daml/issues/6518 to track it.

**Pull request closed without merging**
