### PR TITLE
trying out Monterey CI

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
We only have one machine at the moment so this should definitely not be
merged.

CHANGELOG_BEGIN
CHANGELOG_END

### CODE REVIEW

**Comment by cocreature** [comment]
We need to be somewhat careful here. I think some of our old releases don’t build on monterey so even if this works on `main` we might break bugfix releases for older SDKs.

**Comment by garyverhaegen-da** [comment]
There is no way to acquire new, pre-Monterey machines, so we'll have to move on eventually.

**Comment by cocreature** [comment]
I guess then we’ll have to potentially backport whatever changes are necessary to get old releases to build on monterey.  A bit annoying since nix upgrades are fairly involved but not impossible.

**Comment by garyverhaegen-da** [comment]
> I guess then we’ll have to potentially backport whatever changes are necessary to get old releases to build on monterey. A bit annoying since nix upgrades are fairly involved but not impossible.

I'm not saying we have to upgrade all of our nodes. I'd more in favour of a gradual approach, such as enabling this machine by default so our code gets built on Monterey at least some of the time, and then we can gradually change the composition of the CI cluster.

I'd agree that as long as we're officially supporting pre-Monterey versions on macOS we'll need to keep some pre-Monterey build machines too. But I don't think we have any client using macOS in production, so perhaps dropping macOS from old releases may be an option.

**Comment by garyverhaegen-da** [comment]
Writing it here because that's as good a place as any: we've decided to:

1. Add the Monterey machine to the normal rotation. (Going well so far.)
2. Switch most other machines, progressively over time, to Monterey.

We're not going to try to keep a pre-Monterey machine long-term, on the grounds that even if we do end up needing to patch old, pre-Monterey versions, we would not have developer machines so if the old branch doesn't work on Monterey we'll need to make it work anyway (or disable macOS on that branch).

**Pull request closed without merging**
