### PR TITLE
Check for alpha equivalence in data types

### PR DESCRIPTION
**Pull request by dylant-da**
Also fixes bug where datatypes are equivalent if given new type variables

### CODE REVIEW

**Review by samuel-williams-da — APPROVED** [review]
Looks good! I see your kind change test relies on the fact that the phantum type will default to `Type`, might we want to consider a case where
v1:
```
data MyStruct a b = MyStruct { field1 : a }
```
v2:
```
data MyStruct a b = MyStruct { field1 : a, field2 : Optional a }
```

Also, do the reference docs need updating with this?

**Comment by dylant-da** [comment]
I assume you meant 
```
data MyStruct a b = MyStruct { field1 : a, field2 : Optional b }
```
for v2? I've added a test case to make sure that passes.

**Comment by samuel-williams-da** [comment]
Ah oops, yes I did mean that

**Comment by dylant-da** [comment]
Ach, forgot to push the changes for Sam's review - creating new PR :(

**Pull request merged**
