### PR TITLE
Remove runtime-based coloring from LATT reports

### PR DESCRIPTION
**Pull request by stefanobaghino-da**
Main reasoning: the spectrum of acceptable timing for each test is very wide and using arbitrary times can lead the user to derive misleading information out of the test run.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags, if appropriate
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by SamirTalwar** [comment]
I'm finding this information very useful in identifying slow tests and slow code paths. How about a change to make it slightly less obnoxious instead?

We could change the thresholds so that yellow is at `timeout / 10`, and red is at `timeout / 2`. This will also mean that they're affected by scaling, which should help.

**Comment by dasormeter** [comment]
Agree - the feedback is useful to indicate slower running tests.  Perhaps a choice of coloring other than red, which I intuitively associate with "something is broken" rather than "something is slow"?

**Comment by SamirTalwar** [comment]
Green, yellow, purple?

**Comment by stefanobaghino-da** [comment]
> I'm finding this information very useful in identifying slow tests and slow code paths. How about a change to make it slightly less obnoxious instead?
> 
> We could change the thresholds so that yellow is at `timeout / 10`, and red is at `timeout / 2`. This will also mean that they're affected by scaling, which should help.
> 
> EDIT: I mean `scaledTimeout / 10` and `scaledTimeout / 2`, of course.

The numbers presented by this would make sense only if we adjust the timeout for each test to something that reflects the expected runtime. And I don't think we can make assumptions regarding how long tests are supposed to run on individual ledger implementations. It would force us to find suitable timeouts for arbitrary ledgers, which seems unfeasible.

If we want to have performance indications about a ledger, we should have a tool for that. And I do agree that that would be a very useful tool to have. :wink:

**Comment by SamirTalwar** [comment]
Fair enough. I still like the red (or purple) as an indicator as to which tests are likely to flicker on CI, but we can remove them for now and worry about performance testing later.

**Pull request merged**
