### PR TITLE
Enforce consistent formatting of BUILD files.

### PR DESCRIPTION
**Pull request by gleber-da**
This PR adds Buildifier tool into Bazel rules, enforces its formatting on CI and reformats all of BUILD files accordingly.

To check if files are well formatted, run:

    bazel run //:buildifier

To fix badly-formatted files run:

    bazel run //:buildifier-fix

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/docs/source/support/release-notes.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by cocreature** [comment]
Please don’t autoformat the files generated by `bazel-deps`.

**Comment by moritzkiefer-da** [comment]
Please don’t autoformat the files generated by `bazel-deps`.

**Comment by gleber-da** [comment]
@moritzkiefer-da Good catch. Fixed!

**Comment by gleber-da** [comment]
PTAL

**Comment by gleber-da** [comment]
@aherrmann-da Fixed. PTAL.

**Pull request merged**
