### PR TITLE
ledger-offset: Add a conversion to ByteString.

### PR DESCRIPTION
**Pull request by SamirTalwar-DA**
I seem to be doing this a lot.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by rautenrieth-da — COMMENTED** [review]
Where do you need this? I can't find a single place in this repository where we would convert an Offset to a ByteString.

**Review by fabiotudone-da — COMMENTED** [review]
I wonder, since this class is immutable, how about using lazy vals?

**Comment by SamirTalwar-DA** [comment]
@rautenrieth-da: I find myself using it a lot in another repository when converting offsets back and forth into protobuf values.

**Comment by SamirTalwar-DA** [comment]
@fabiotudone-da: I am not sure. In the case of `toByteString`, this just accesses a property on `bytes`, and I'm not sure using a `lazy val` to capture the result of this property access would improve performance. However, this is due to my naive understanding of how well the JVM needs help like this. What do you think?

For `toByteArray`, `toByteBuffer`, and `toInputStream`, the return value is mutable, and so we cannot keep it around.

**Comment by fabiotudone-da** [comment]
> @fabiotudone-da: I am not sure. In the case of `toByteString`, this just accesses a property on `bytes`, and I'm not sure using a `lazy val` to capture the result of this property access would improve performance. However, this is due to my naive understanding of how well the JVM needs help like this. What do you think?
> 
> For `toByteArray`, `toByteBuffer`, and `toInputStream`, the return value is mutable, and so we cannot keep it around.

True, definitely not possible/worth.

**Review by fabiotudone-da — APPROVED** [review]

**Review by hubert-da — APPROVED** [review]

**Pull request merged**
