### PR TITLE
run PRs build on PRs 1.2.x

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
This updates the config to match #8374 & the corresponding new Azure setup.

It's essentially the same as #8545, but on 1.2.x. `azure-pipelines.yml` has become a bit more complex between 1.1.x and 1.2.x, so there are a few more changes there, though conceptually they're the same: remove jobs that would never run on PRs, change yml template references to account for the change in cwd.

CHANGELOG_BEGIN
CHANGELOG_END

### CODE REVIEW

**Review by cocreature — APPROVED** [review]

**Comment by garyverhaegen-da** [comment]
@cocreature following discussion on Slack I have disabled the failing test and revoked your approval, so you can take a look and decide.

FWIW here is the disabled test on my machine as of 4ad3a39a01547f53e7b55e57ef4f71f94b60fa32:
```
//ledger/ledger-on-memory:conformance-test                               FAILED in 39 out of 40 in 60.9s
  Stats over 40 runs: max = 60.9s, min = 40.3s, avg = 54.9s, dev = 2.7s
```
and as of 1c18058f019229cd0af64669af0de31d0cec916d (the target of this PR, which I somehow can still run locally despite the Bintray disappearance):
```
//ledger/ledger-on-memory:conformance-test                               FAILED in 40 out of 40 in 58.8s
  Stats over 40 runs: max = 58.8s, min = 53.1s, avg = 55.6s, dev = 1.1s
```
In both cases, the error message is the same:
```
PackageManagement
- Concurrent uploads of the same package should be idempotent and result in the package being available for use ... Timeout
runner: callProcess: /private/var/tmp/_bazel_garyverhaegen/4b497307028b2b2afb5dc552b427a4b7/sandbox/processwrapper-sandbox/1341/execroot/com_github_digital_asset_daml/bazel-out/darwin-opt/bin/ledger/ledger-on-memory/conformance-test_wrapper.sh.runfiles/com_github_digital_asset_daml/ledger/ledger-api-test-tool/ledger-api-test-tool "--verbose" "--all-tests" "--exclude=ConfigManagementServiceIT" "localhost:6865" (exit 1): failed
21:10:47.060 INFO  c.d.p.a.s.ApiCommandService - Shutting down Command Service
21:10:47.060 INFO  c.d.p.a.s.t.TrackerMap - Shutting down 200 trackers
21:10:47.103 ERROR c.d.p.a.s.a.ApiPackageManagementService - Unhandled internal error
java.util.NoSuchElementException: head of empty stream
        at akka.stream.scaladsl.Sink$.$anonfun$head$3(Sink.scala:197)
```

**Comment by cocreature** [comment]
Did you observe the failure locally or on CI? I just tried `bazel test //ledger/ledger-on-memory:conformance-test --runs_per_test=20` on 189b7a719d2e8b4ed9d7d4c96b2f7aa533b935c4 (the current state of this PR) and I didn’t get a single failure. Maybe it is only this flaky on macos (we don’t run this test on macos on CI afaik)

**Review by cocreature — APPROVED** [review]
Reapproving with the disabled test. While I cannot reproduce it locally, ledger-on-memory on a branch I don’t expect us to touch again, doesn’t worry me that much (particularly, if I cannot reproduce it locally, if it had gotten super flaky everywhere without any change it would be somewhat worrying) so I wouldn’t spend more time on it.

**Comment by garyverhaegen-da** [comment]
> Did you observe the failure locally or on CI? I just tried `bazel test //ledger/ledger-on-memory:conformance-test --runs_per_test=20` on [189b7a7](https://github.com/digital-asset/daml/commit/189b7a719d2e8b4ed9d7d4c96b2f7aa533b935c4) (the current state of this PR) and I didn’t get a single failure. Maybe it is only this flaky on macos (we don’t run this test on macos on CI afaik)

I had ten failures in a row on CI before I gave up and started looking at disabling the tests. I tried bisecting on my machine and I found commit 6108c922c6ad506fc79f33c1765d6203116ad837 as the culprit: on my machine, on its parent (db8c09146) I get 10/10 successes; on 6108c92 I get 10/10 failures.

I don't have any explanation for why you wouldn't be able to reproduce, given it's fairly reliably broken for me (granted, on macOS) and for CI (on Linux).

**Comment by cocreature** [comment]
> I don't have any explanation for why you wouldn't be able to reproduce, given it's fairly reliably broken for me (granted, on macOS) and for CI (on Linux).

I don’t have one either :disappointed: While it somewhat pains me to say this, I’d suggest to merge and ignore it :see_no_evil:

**Comment by garyverhaegen-da** [comment]
> Did you observe the failure locally or on CI? I just tried `bazel test //ledger/ledger-on-memory:conformance-test --runs_per_test=20` on [189b7a7](https://github.com/digital-asset/daml/commit/189b7a719d2e8b4ed9d7d4c96b2f7aa533b935c4) (the current state of this PR) and I didn’t get a single failure. Maybe it is only this flaky on macos (we don’t run this test on macos on CI afaik)

🤦

189b7a719d2e8b4ed9d7d4c96b2f7aa533b935c4 is the one with the failing tests disabled, so I am definitely expecting that to succeed reliably. Perhaps try out 4ad3a39a01547f53e7b55e57ef4f71f94b60fa32 ?

**Comment by cocreature** [comment]
> [189b7a7](https://github.com/digital-asset/daml/commit/189b7a719d2e8b4ed9d7d4c96b2f7aa533b935c4) is the one with the failing tests disabled, so I am definitely expecting that to succeed reliably. Perhaps try out [4ad3a39](https://github.com/digital-asset/daml/commit/4ad3a39a01547f53e7b55e57ef4f71f94b60fa32) ?

Duh, I shouldn’t test things before I had coffee. It’s also failing for me now, sorry for the confusion. Still same advice, merge and let’s move on.

**Pull request merged**
