### PR TITLE
[KV] - Replace RESOURCE_EXHAUSTED KV error with RESOURCE_OVERLOADED [kvl-1290]

### PR DESCRIPTION
**Pull request by nicu-da**
As RESOURCE_EXHAUSTED also represents a gRPC status code, to avoid confusion (as the error is mapped to gRPC status code ABORTED), we replace it with RESOURCE_OVERLOADED

changelog_begin
changelog_end

### CODE REVIEW

**Review by fabiotudone-da — COMMENTED** [review]
I think a changelog entry is required here.

**Review by tudor-da — APPROVED** [review]

**Review by hubert-da — APPROVED** [review]

**Comment by fabiotudone-da** [comment]
An error being deprecated and a new one introduced and the [error docs](https://docs.daml.com/app-dev/grpc/error-codes.html#error-categories-inventory) will change as a consequence; true that we don't change the status codes though, not sure what the policy is about changelog entries in this case. FYI @bame-da

**Comment by bame-da** [comment]
Why is this better than using gRPC code RESOURCE_EXHAUSTED?

**Comment by bame-da** [comment]
Using RESOURCE_EXHAUSTED was the original plan laid out in https://docs.google.com/document/d/1wW-kWpYaTcmmPcJzwJVheB09qp6SNDWnptlY3MluQXA/edit.

**Comment by nicu-da** [comment]
@bame-da The RESOURCE_EXHAUSTED category was not added as an error category. 
The `ResourceExhausted` error is part of the `ContentionOnSharedResources` category which maps to `ABORTED` status code. 

This change comes as feedback from users if I remember correctly (you can correct me @fabiotudone-da), which were confused by the `RESOURCE_EXHAUSTED` error id which does not map to `RESOURCE_EXHAUSTED` gRPC status code.

**Pull request merged**
