### PR TITLE
ci: use windows-pool

### PR DESCRIPTION
**Pull request by majcherm-da**
- Switches to GCP hosted Windows CI agents pool
- Adds `scoop reset $app` call to windows dev-env's sync command, so that environment variables set in tools' manifest files are (re)set - missing `BAZEL_SH` and `JAVA_HOME` env. variables were causing problems on GCP hosted Windows Agents of Azure Pipelines

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/docs/source/support/release-notes.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by neil-da** [comment]
I'd like both @aherrmann-da and @garyverhaegen-da to review these changes before they go in.

**Comment by majcherm-da** [comment]
Sure, it was a draft PR to run build on CI and initial run successfully, so I removed 'draft', but it's unfortunatelly non-deterministic. I'll need to play with it - will let you know once it's working.

**Comment by majcherm-da** [comment]
@aherrmann-da , @garyverhaegen-da it's working now. Problems were caused by missing env. variables set by `scoop` for re-used agents. This is why it was non-deterministic - it was working ok for a clean run on a new agent, but was failing on agent which was previously used. I guess what was happening was agent started on clean box and env. variables set from the build, affecting both current PS session and stored as well, but because the process is not restarted it's not picking the stored ones and the new PS session didn't have env. variables set, since `scoop install $app` just verifies if the app is installed or not, but does not reset env. variables. I added a `scoop reset $app` to `dadew sync` call, to cover this case.

**Pull request merged**
