### PR TITLE
Fix the docstring for useStreamFetchByKeys

### PR DESCRIPTION
**Pull request by stefanobaghino-da**
changelog_begin
changelog_end

Originally reported at https://discuss.daml.com/t/usestreamfetchbykeys-is-missing-closehandler-argument/2552

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by cocreature — APPROVED** [review]
Thanks! We should still add the closeHandler separately and add it back to the docs then.

**Comment by garyverhaegen-da** [comment]
Looks like I screwed up in https://github.com/digital-asset/daml/pull/7567; it's not the docstring that needs fixing, but the code.

**Comment by stefanobaghino-da** [comment]
> Looks like I screwed up in #7567; it's not the docstring that needs fixing, but the code.

Would you mind if I take care of that? I can benefit from making small fixes to the JS bindings right now.

**Comment by garyverhaegen-da** [comment]
> @garyverhaegen-da Would you mind if I take care of that? I can benefit from making small fixes to the JS bindings right now.

Oh, sorry, saw this too late. Fixed in #9565, unless I screwed up again 🤷.

**Comment by stefanobaghino-da** [comment]
Sorry for the mess, unfortunately you'll have to rebase on this commit I merged. I was not expecting a fix to come in five minutes.

**Pull request merged**
