### PR TITLE
Add the DAML-on-X team as code owners of /ledger/participant-state.

### PR DESCRIPTION
**Pull request by SamirTalwar-DA**
Namely @dajmaki, @dasormeter, @fabiotudone-da, @miklos-da, and @mziolekda.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by SamirTalwar-DA** [comment]
If I missed anyone, holler.

**Comment by miklos-da** [comment]
> If I missed anyone, holler.

Can you add @dasormeter as well, please?

**Comment by SamirTalwar-DA** [comment]
@miklos-da: Done.

**Comment by miklos-da** [comment]
> @miklos-da: Done.

Thank you. Can you also make sure you alphabetically order the names, please? That helps scanning the list for humans ;)

**Pull request merged**
