### PR TITLE
README for vscode extension

### PR DESCRIPTION
**Pull request by alanz**
Need to `npm ci` before trying to create the package.

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/unreleased.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by alanz** [comment]
In my (limited) experience, `npm ci` honours the `package-lock.json` file exactly, where other commands may do an update to it.

So I generally use that as the go-to command for building something repeatedly from a repo.

It probably does not make much difference, for this.

**Comment by neil-da** [comment]
Unfortunately you need to sign the CLA before I can merge your patch. If that's not possible I'll make such a patch myself (I think it's fair to say the above patch doesn't contain copyright protections).

**Comment by alanz** [comment]
I think its easier to just update it yourself.

**Comment by neil-da** [comment]
Sure, updated in https://github.com/digital-asset/daml/pull/1827.

**Pull request closed without merging**
