### PR TITLE
timestamp-conversions: A set of libraries for converting timestamps and durations.

### PR DESCRIPTION
**Pull request by SamirTalwar-DA**
I got fed up of writing converters between various different timestamp and duration types (and not knowing if I was inadvertently introducing bugs in doing so), so I decided to make libraries for all of them.

These provide implicit converters between:

  - _java-scala_: Java durations and Scala durations
  - _java-lf_: Java instants and Daml-LF timestamps
  - _java-protobuf_:
    - Java instants and Java Protocol Buffers timestamps
    - Java durations and Java Protocol Buffers durations
  - _java-scalaprotobuf_:
    - Java instants and Scala Protocol Buffers timestamps
    - Java durations and Scala Protocol Buffers durations
  - _scala-protobuf_: Scala durations and Scala Protocol Buffers durations
  - _scala-javaprotobuf_: Scala durations and Java Protocol Buffers durations
  - _lf-javaprotobuf_: Daml-LF timestamps and Java Protocol Buffers timestamps
  - _lf-scalaprotobuf_: Daml-LF timestamps and Scala Protocol Buffers timestamps

There are many small libraries so you can depend on what you need without bringing in extra dependencies. For example, if you don't use ScalaPB, you don't want to include it inadvertently.

They are currently not used, but I have plans to replace existing conversion functions with these.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by S11001001** [comment]
There's something I didn't notice before that I think we should really avoid here: we generally are very explicit about our existing conversions being total or not, hence the `assert` names and their well-typed counterparts. By hiding that, this library would also be hiding that distinction.

Following the `TConv` design idea we can solve that problem by declaring it as `TConv[-From, To] {type OF[A]}` and returning `OF[To]` in the various methods. Regardless, the existing scheme of merely flattening this distinction makes these operations look _way_ more innocuous than they actually are.

**Comment by nicu-da** [comment]
@SamirTalwar-DA do we want to proceed with this PR?

**Comment by SamirTalwar-DA** [comment]
I lost interest. Let's close it and re-open it if anyone wants to pick it up.

**Pull request closed without merging**
