### PR TITLE
ci: use setvar to set variables

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
My goal here is to investigate the new warning Azure has been showing for the past few days:

> ##[warning]%25 detected in ##vso command. In March 2021, the agent command parser will be updated to unescape this to %. To opt out of this behavior, set a job level variable DECODE_PERCENTS to false. Setting to true will force this behavior immediately. More information can be found at https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/percentEncoding.md

As far as I'm aware we are not deliberately passing in any `%25` in any of our `vso` commands, so I was a bit surprised by this.

CHANGELOG_BEGIN
CHANGELOG_END

### CODE REVIEW

**Review by cocreature — APPROVED** [review]
lgtm, thanks!

**Comment by SamirTalwar-DA** [comment]
Is there a reason this isn't running on CI?

**Comment by garyverhaegen-da** [comment]
> Is there a reason this isn't running on CI?

That usually means I screwed up the YAML syntax somehow so Azure ails to parse it. In other words, this PR is off to a great start 🙂

**Comment by cocreature** [comment]
afaict, the warning here comes’s from azure’s builtin jobs not our own uses of `setvar`.

**Comment by cocreature** [comment]
upstream issue https://github.com/microsoft/azure-pipelines-tasks/issues/14302

**Comment by garyverhaegen-da** [comment]
> afaict, the warning here comes’s from azure’s builtin jobs not our own uses of `setvar`.

The goal of unifying all of our vso commands through one function was to make it easy to add debug statements to find out which of our commands actually passes a `%`. I couldn't find one, though.

**Pull request merged**
