### PR TITLE
Add additional rights and clarifications to user management API

### PR DESCRIPTION
**Pull request by meiersi-da**
Addresses: learning from design doc and review comments from https://github.com/digital-asset/daml/pull/11818/ that were added after merging; concretely
- add `CanActAsAnyParty` and `CanReadAsAnyParty` rights
- make `primary_party` optional for special users
- add `DeleteUserResponse`

FYI: @da-tanabe @bame-da @cocreature @gerolf-da @stefanobaghino-da @adriaanm-da @nmarton-da 

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [x] Normal production system change, include purpose of change in description
- [x] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by cocreature — APPROVED** [review]
Looks sensible, thank you!

**Review by cocreature — COMMENTED** [review]
@meiersi-da given that the extra rights are out of date now iiuc should this be updated? (and merged so we have the same base to work against)

**Comment by meiersi-da** [comment]
Agreed @moritzkiefer-da . I've just found that we already have `ClaimActAsAnyParty`, so I've only removed the `ReadAsAnyParty` right. Will merge as soon as the checks pass.

**Comment by cocreature** [comment]
> Agreed @moritzkiefer-da . I've just found that we already have `ClaimActAsAnyParty`, so I've only removed the `ReadAsAnyParty` right.

Note that while we have this internally, we currently do not expose this in any form to our users. So we may still want to be cautious in making this part of our public APi.

**Comment by meiersi-da** [comment]
> Note that while we have this internally, we currently do not expose this in any form to our users. So we may still want to be cautious in making this part of our public APi.

I'm inclined to expose it as it is
1. well-defined
2. solves use-cases like using Navigator in an authenticated setup

That said, I might be overlooking things. So what actions do you think we need to take before exposing this?

**Comment by meiersi-da** [comment]
Hmm... now having written that I get the rubber-duck effect: it seems that `CanActAsAnyParty` invites all kinds of hacks, instead of forcing us to solve the actual rights managements problems which would exist anyways in production. So yeah, I'm more inclined to remove it for now.

@bame-da what is your opinion?

**Comment by cocreature** [comment]
I’m not super strongly opposed to exposing it but it doesn’t seem necessary for 2.0 and I have concerns similar to the ones you mentioned above (encouraging various antipatterns). Adding it later seems fully backwards compatible so we can add it once we’re confident it’s a good idea.

**Comment by meiersi-da** [comment]
Thanks @cocreature for the valuable push-back. I've removed the xxxAnyRights

**Comment by cocreature** [comment]
> Thanks @cocreature for the valuable push-back. I've removed the xxxAnyRights

thanks! and just to be clear I’m happy to revisit this outside of the 2.0 scope

**Pull request merged**
