### PR TITLE
Re-release 0.13.35 as 0.13.36

### PR DESCRIPTION
**Pull request by gerolf-da**
### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/unreleased.rst), if appropriate
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by hurryabit** [comment]
When we do this next time, can please leave a comment in the release notes why there's a release without any new features. We're displaying the release notes in DAML Studio now. An empty page of release notes will look quite silly.

**Comment by hurryabit** [comment]
Oh wait, we're using the same release notes as for 0.13.35 and deleting those for 0.13.35. Let's hope that goes well. :crossed_fingers:

**Comment by gerolf-da** [comment]
All manual tests have passed

**Comment by gerolf-da** [comment]
> When we do this next time, can please leave a comment in the release notes why there's a release without any new features. We're displaying the release notes in DAML Studio now. An empty page of release notes will look quite silly.

@hurryabit: Hm, I didn't know that. Worth putting in how to treat failed releases in `RELEASE.md`.

**Pull request merged**
