### PR TITLE
cleanup: kill more stuff

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
changelog_begin
changelog_end

### CODE REVIEW

**Comment by garyverhaegen-da** [comment]
@cocreature This seems to have fixed that machine. Do you per chance remember why we switched from `lsof` to `pgrep`? I have no recollection and unfortunately I did not record it in #8748.

**Comment by cocreature** [comment]
> @cocreature This seems to have fixed that machine. Do you per chance remember why we switched from `lsof` to `pgrep`? I have no recollection and unfortunately I did not record it in #8748.

I’m not entirely sure, I remember either something about lsof not working properly or something about us not trusting the results and going for the “full” cleanup (which is apparently not full enough). I guess worts case, we’ll rediscover it.

**Comment by garyverhaegen-da** [comment]
This time we had Java and daml processes lingering, so killing Bazel ones is clearly not enough. 🤷

**Review by cocreature — APPROVED** [review]
Thans!

**Pull request merged**
