### PR TITLE
release 2.1.0-snapshot.20220308.9472.0.1f24348e

### PR DESCRIPTION
**Pull request by stewSquared**
@stewSquared is in charge of this release

### Pull Request Checklist

- [X] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [X] Include appropriate tests
- [X] Set a descriptive title and thorough description
- [X] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [X] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by stewSquared** [comment]
Manual test passed on Windows

**Comment by stewSquared** [comment]
Manual test passed on macOS

**Comment by stewSquared** [comment]
How do I restart `check_standard_change_label`?

**Comment by stewSquared** [comment]
How do I restart `check_standard_change_label`?

**Comment by cocreature** [comment]
I don’t think you actually need a new daml snapshot. You can use the last nightly one. @garyverhaegen-da can walk you through the details probably.

**Comment by garyverhaegen-da** [comment]
I'm a bit confused here. What did you test? This release is not created yet 🤔

As @cocreature mentioned, you shouldn't need to create a release in this repo. Could you point me to the instructions that lead you to do that?

**Comment by S11001001** [comment]
As a 2.x, will be a split release based on nightly snapshot instead.

**Pull request closed without merging**
