### PR TITLE
Support importing Script.Daml to determinism & memory test file

### LINKED ISSUE #16391: Support Daml.Script in determinism test
Our determinism test uses a subset of the daml-test-files to ensure determinism in compiling and building.
Given we intend to convert all of these files to script, the determinism test must support said scripts
Ensure we no longer see `Could not find module ‘Daml.Script’` when importing `Daml.Script` in `daml-test-files/Example.daml`

This ticket relates to #16332

### PR DESCRIPTION
**Pull request by samuel-williams-da**
Resolves #16391
Allows importing Daml.Script in determinism tests

Tested with `DAML_SDK_RELEASE_VERSION` of `0.0.0` and `2.6.0-snapshot.20230220.11461.0.5deb4ea7`

### CODE REVIEW

**Comment by samuel-williams-da** [comment]
Same changes are needed for the memory test, via `damlc_compile_test`.
Pushing both the changes here, but should consider refactoring the logic out if possible

**Comment by garyverhaegen-da** [comment]
I'm not really in a position to properly review this, but given the failure on CI I would have expected some change to [DamlDocsScriptImport.EXPECTED.json](https://github.com/digital-asset/daml/blob/0dbbcfe0f1e49f2cedc13bb8bfa951a0ea253213/compiler/damlc/tests/daml-test-files/DamlDocsScriptImport.EXPECTED.json), along the lines of replacing `0.0.0` with `$VERSION` or `__VERSION__` or something.

**Comment by samuel-williams-da** [comment]
@garyverhaegen-da See https://github.com/digital-asset/daml/pull/16389, sadly that file is generated, and changing it would result to issues in the future. I would like to add support for a VERSION keyword syntax in future though

**Comment by samuel-williams-da** [comment]
PR fails CI as, on windows only, there are absolute paths embedded in .daml
Might be an issue worth exploring

**Comment by samuel-williams-da** [comment]
@akrmn Any thoughts about how I might do this?

**Comment by akrmn** [comment]
not sure how we can refactor this specifically, I think eventually we'll want `damlc` to support packages itself but that's outside of the scope here

**Review by akrmn — APPROVED** [review]

**Pull request merged**
