### PR TITLE
fix notify_user

### PR DESCRIPTION
**Pull request by garyverhaegen-da**

### CODE REVIEW

**Comment by cocreature** [comment]
Could you provide some context for this? The changes look reasonable but I don’t quite understand what issue this fixes.

**Comment by garyverhaegen-da** [comment]
> Could you provide some context for this? The changes look reasonable but I don’t quite understand what issue this fixes.

There's no context because it's still a draft.

Context is: at the moment, some jobs can report success to Slack while they actually failed, because the `notify_user` job only depends on collect_build_data and thus doesn't "see" e.g. `check_changelog_entry` failures.

The PR as it stands doesn't properly fix it, though, because Azure makes it annoyingly hard for a job to know about the status of other jobs.

**Comment by cocreature** [comment]
> There's no context because it's still a draft.

Oh sorry, I got confused because you requested reviews. I’ll take a look once it’s no longer a draft then.

**Comment by garyverhaegen-da** [comment]
> > There's no context because it's still a draft.
> 
> Oh sorry, I got confused because you requested reviews. I’ll take a look once it’s no longer a draft then.

My bad. I expected the notification not to trigger until it's out of draft.

**Comment by garyverhaegen-da** [comment]
Proposed solution in this PR is actually not solving the issue as jobs don't run at all when they're dependencies are skipped. I don't actually know how to improve the current situation.

Fortunately, nobody has complained about the current situation for a few months, so I'm just going to close this and let the issue rest for now.

**Pull request closed without merging**
