### PR TITLE
compatibility-tests - Exclude CommandDeduplicationIT from running for 1.17 snapshots

### PR DESCRIPTION
**Pull request by nicu-da**
The current version of the ledger-api-tool is no longer compatible with existing 1.17 snapshots

Reason: in-between snapshots there was a proto change (field number change) which broke compatibility [the actual change](https://github.com/digital-asset/daml/pull/10822/files#diff-ed4ed30e4f593aaf9d013b39ed5272dfc0df08c548cc78f110fd4471eaa6f59cR75)

CHANGELOG_BEGIN

CHANGELOG_END

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [x] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by stefanobaghino-da — APPROVED** [review]

**Review by fabiotudone-da — APPROVED** [review]

**Comment by cocreature** [comment]
started a build of the compat pipeline to verify this works as expected

**Review by cocreature — APPROVED** [review]
Thanks!

**Comment by nicu-da** [comment]
@cocreature should we retry the job? it seems that it got stuck

**Comment by cocreature** [comment]
I’d just merge. macos & windows passed so the exclusions seem fine.

**Comment by nicu-da** [comment]
> I’d just merge. macos & windows passed so the exclusions seem fine.

sounds good to me

**Pull request merged**
