### PR TITLE
Kill stale sandbox processes on macos and linux

### PR DESCRIPTION
**Pull request by cocreature**
changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by SamirTalwar-DA** [comment]
This is a useful temporary stopgap until we start randomizing ports properly. I do think we still need to do that.

**Comment by cocreature** [comment]
> This is a useful temporary stopgap until we start randomizing ports properly.

While I’m all for randomizing ports I think that’s orthogonal to this problem here. Randomizing ports doesn’t solve the issue of stale processes, it just makes things take a bit longer before they end up overloading your machine.

**Comment by SamirTalwar-DA** [comment]
> Randomizing ports doesn’t solve the issue of stale processes, it just makes things take a bit longer before they end up overloading your machine.

True, but if we refresh the machines nightly, it should be enough.

**Comment by garyverhaegen-da** [comment]
Does anybody know why we suddenyl started having stale processes? I don't remember seeing that before last week.

**Comment by cocreature** [comment]
I don’t know it sadly.

**Pull request merged**
