### PR TITLE
Burn all the braces, prettify metrics project

### PR DESCRIPTION
**Pull request by realvictorprm**
Removed a bunch of braces which were not necessary and other small nits in the Metrics project.
I did this in the manner of "Leave the coder better than you found it"

changelog_begin
changelog_end

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by realvictorprm** [comment]
This one is ready as-is (if I don't oversaw any unnecessary braces).

**Review by cocreature — COMMENTED** [review]
I’ll leave it to the code owners to accept or reject this change but my general view on these types of changes is that either we enforce them via scalafmt or we don’t do them (meaning either is ok and we don’t bikeshed it on PRs). Otherwise, this just creates a lot of chore with no benefit.

**Comment by realvictorprm** [comment]
@cocreature I would prefer to not do that manually but let scalafmt do this.

**Comment by cocreature** [comment]
> @cocreature I would prefer to not do that manually but let scalafmt do this.

In that case, start a thread in #team-daml proposing such a rule change and if everyone agrees we can go down that route.

**Comment by realvictorprm** [comment]
Closing this till people have decided on whether they want braces or not

**Pull request closed without merging**
