### PR TITLE
Release SDK 1.17.0

### PR DESCRIPTION
**Pull request by cocreature**
changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by stefanobaghino-da — APPROVED** [review]

**Comment by stefanobaghino-da** [comment]
Not sure of what went wrong on CI.

```2021-09-29T07:13:56.1400920Z ERROR: /Users/vsts/agent/_work/1/s/daml-script/export/integration-tests/export-lf-1.6/BUILD.bazel:50:20: Action daml-script/export/integration-tests/export-lf-1.6/lf16-export.zip failed: (Exit 1): bash failed: error executing command 
2021-09-29T07:13:56.1406570Z   (cd /private/var/tmp/_bazel_vsts/38d36a619150b9300aa37bd0849c0ccc/sandbox/processwrapper-sandbox/4918/execroot/com_github_digital_asset_daml && \
2021-09-29T07:13:56.1410700Z   exec env - \
2021-09-29T07:13:56.1425120Z   /nix/store/pw267i20vmlzs4l4rqm95mx05xc12kyi-bash/bin/bash -c '
2021-09-29T07:13:56.1427930Z         export EXPORT_OUT="bazel-out/darwin-opt/bin/daml-script/export/integration-tests/export-lf-1.6/lf16-export.zip"
2021-09-29T07:13:56.1431930Z         bazel-out/darwin-opt/bin/bazel_tools/client_server/runner_with_port_file/runner_with_port_file "bazel-out/darwin-opt/bin/daml-script/export/integration-tests/export-lf-1.6/lf16-export-client" "--ledgerid=lf16-export-ledger --target-port=%PORT% bazel-out/darwin-opt/bin/daml-script/export/integration-tests/export-lf-1.6/lf16.dar" "bazel-out/darwin-opt/bin/ledger/sandbox/sandbox-binary" "--ledgerid=lf16-export-ledger --port=0 --port-file=%PORT_FILE% bazel-out/darwin-opt/bin/daml-script/export/integration-tests/export-lf-1.6/lf16.dar" "" &> runner.log
2021-09-29T07:13:56.1435690Z         if [ "$?" -ne 0 ]; then
2021-09-29T07:13:56.1438180Z           /nix/store/a3spmzmx03n3d7i5ah5dprwhrxgl35fs-posix-toolchain/bin/cat runner.log
2021-09-29T07:13:56.1439370Z           exit 1
2021-09-29T07:13:56.1439880Z         fi
2021-09-29T07:13:56.1440790Z       ')
2021-09-29T07:13:56.1442310Z Execution platform: @io_tweag_rules_nixpkgs//nixpkgs/platforms:host
```

**Comment by cocreature** [comment]
looks like a timeout in the reference ledger export step

**Comment by adriaanm-da** [comment]
LGTM

PS: Since this release has the same sha as a previous snapshot release, does this imply that [the commit](49a75801) will have multiple tags? I guess that's not a problem per se, but it can be confusing.

**Comment by cocreature** [comment]
> PS: Since this release has the same sha as a previous snapshot release, does this imply that [the commit](49a75801) will have multiple tags? I guess that's not a problem per se, but it can be confusing.

yes it does but that’s intentional. The snapshot is the same commit as the stable release so it should get the same tag.

**Pull request merged**
