### PR TITLE
Add location information to DAML-LF produced by damlc

### PR DESCRIPTION
**Pull request by martin-drhu-da**
This is required to get error locations in the scenario view. Rigth now,
the location information for `create`/`exercise` still points to the
template/choice. I'll fix that in a separate PR.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/docs/source/support/release-notes.rst), if appropriate

### CODE REVIEW

**Comment by martin-drhu-da** [comment]
@moritzkiefer-da I have not checked it on large files. I think, right now, we should trade usability for performance on big files anyway.

**Comment by moritzkiefer-da** [comment]
I completely agree that it is the right default but if it turns out to be too slow we should add an option to turn it off.

**Comment by martin-drhu-da** [comment]
I've compile the whole CDM two times with the old and the new compiler:
new:
```
22.11s user 0.38s system 99% cpu 22.494 total
21.97s user 0.42s system 100% cpu 22.391 total
```
old:
```
22.71s user 0.44s system 100% cpu 23.142 total
23.10s user 0.44s system 100% cpu 23.529 total
```
That's roughly a 5% degradation. I think we can live that for now.

**Comment by moritzkiefer-da** [comment]
:+1: Thanks for testing that!

**Comment by neil-da** [comment]
Thanks for taking the time to benchmark. I suspect if we need 5% perf improvement a quick profile would tell us (once we have profiling again).

**Comment by martin-drhu-da** [comment]
Actually, the location information in scenario failure looks good. The links don't work though. This is tracked in https://github.com/digital-asset/daml/issues/86.

**Pull request merged**
