### PR TITLE
Remove maximumLedgerTime DB query (pure refactoring)

### PR DESCRIPTION
**Pull request by nmarton-da**
changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by gerolf-da** [comment]
@nmarton-da: can this be removed, because we mutable-state-cache is always turned on, or rather, cannot be turned off?

**Review by skisel-da — APPROVED** [review]

**Comment by nmarton-da** [comment]
> @nmarton-da: can this be removed, because we mutable-state-cache is always turned on, or rather, cannot be turned off?

we have only mutable-state-cache now, the alternative was removed before, the flag is stale for backwards compatibility currently. see https://github.com/digital-asset/daml/pull/12528

**Review by rautenrieth-da — APPROVED** [review]
This removes tests at LedgerDao/StorageBackend level. Do we have any comparable tests on another level? I don't see any tests in the conformance test tool, and it is difficult to add tests there:
1. Tests that deal with time are non-deterministic in wallclock time mode
1. The clock of a participant is monotonically increasing in static time mode, but in distributed ledgers the ledger time of transactions does not need to be monotonically increasing.
1. You need a privacy-aware ledger to see divulged contracts for which you don't know the ledger time

**Comment by nmarton-da** [comment]
> This removes tests at LedgerDao/StorageBackend level. Do we have any comparable tests on another level? I don't see any tests in the conformance test tool, and it is difficult to add tests there:
> 
>     1. Tests that deal with time are non-deterministic in wallclock time mode
> 
>     2. The clock of a participant is monotonically increasing in static time mode, but in distributed ledgers the ledger time of transactions does not need to be monotonically increasing.
> 
>     3. You need a privacy-aware ledger to see divulged contracts for which you don't know the ledger time

we have some at MutableCacheBackedContractStoreSpec

**Pull request merged**
