### PR TITLE
[LF] make different kinds of speedy questions explicit

### PR DESCRIPTION
**Pull request by remyhaemmerle-da**
CHANGELOG_BEGIN
CHANGELOG_END

### CODE REVIEW

**Comment by carlpulley-da** [comment]
The splitting of questions based on usage makes sense (especially as we're now exploring the different use cases for Speedy machine and engine).

I'd suggest we also try and adopt 2 additional usage/implementation goals (and maybe we achieve these at a future date rather than now):
- usage specific questions should be mutually exclusive - e.g. scenario questions can not be asked by ledger engines/machines (in a similar manner, scenario builtins should not be usable by ledger engines)
- we allow (for example) script and trigger service to be able to define their questions and Speedy builtin extensions in their own modules (with speedy package structures/restrictions to access the relevant speedy APIs) - that way we keep script and trigger concerns within their respective modules without cluttering up the existing Speedy machine/engine package unnecessarily.

**Comment by nickchapman-da** [comment]
To make this work nicely, speedy machine must be polymorphic in question type. Can we do this?

**Comment by carlpulley-da** [comment]
> To make this work nicely, speedy machine must be polymorphic in question type. Can we do this?

My naive thinking here would be to define a generic question trait/abstract class. Then each target (e.g. ledger, scenario, trigger, etc.) defines sealed questions (extending our generic question trait/abstract class).

That said, I've currently no idea if that thinking would work at the builtin and engine levels of code.

**Comment by remyhaemmerle-da** [comment]
> o make this work nicely, speedy machine must be polymorphic in question type. Can we do this?

I believe we can make it. 

I think I would make `Machine` an extensible class parametrized by the Question type.  
Each type of question will have his own version of the Machine, and instead of checking the type of the parameter `onLedger` I would check the type of the full machine.

**Comment by remyhaemmerle-da** [comment]
subsumed by #15902

**Pull request closed without merging**
