### PR TITLE
Build DAML Script library for all LF versions

### PR DESCRIPTION
**Pull request by cocreature**
The hardcoded list is obviously garbage and didn’t include 1.11 so
this PR changes it to use the one we already have so they are always
in sync.

changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by cocreature** [comment]
Not sure how to write a useful test for this. Whatever I can come up just relies on the list of versions in the test being in sync with the one here which doesn’t seem super useful.

**Review by aherrmann-da — APPROVED** [review]

**Review by remyhaemmerle-da — COMMENTED** [review]
:+1:

**Comment by bame-da** [comment]
@cocreature Maybe a useful test as part of our compatibility suite would be to `daml start` the skeleton project with `--target=X` for all supported LF versions?

**Comment by cocreature** [comment]
> @cocreature Maybe a useful test as part of our compatibility suite would be to `daml start` the skeleton project with `--target=X` for all supported LF versions?

The problem is that "all suported LF versions" needs to come from somewhere and keeping the list in the test in sync with the list of available versions is basically the same problem as keeping the list of versions we build daml script against in sync with the list of available versions.

**Pull request merged**
