### PR TITLE
Added batch file for windows installation

### PR DESCRIPTION
**Pull request by ashfaq-shaik**
Added batch file to install SDK from archive on window

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/docs/source/support/release-notes.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by ashfaq-shaik** [comment]
@cocreature 

Thanks for the review.

**Comment by cocreature** [comment]
Don’t worry about the CI failures, they are unrelated to your PR and are being fixed in #1033

**Comment by ashfaq-shaik** [comment]
Makes sense. %~dp0 is much more efficient and descriptive. I will change the line to 

`%~dp0/daml/daml install %~dp0 --activate`

**Comment by neil-da** [comment]
Does it need a `..` after it? I always get confused by those ugly path dependent things (much less clear than `%cd%` but ensures it still works if someone is 2 levels up on the path or similar).

**Comment by ashfaq-shaik** [comment]
Actually it should be `%~dp0daml\daml install %~dp0 --activate` 

`%~dp0` comes with its own trailing \

Not sure if it needs `..` because a user would be executing the script by entering that directory.

**Comment by cocreature** [comment]
Thanks for the updates @ashfaq-shaik! It looks like CI is currently failing due to a missing copyright header. If you have python installed on your Windows machine (or a MacOS/Linux machine with our dev-env enabled) you can run `python3 dev-env/bin/dade-copyright-headers update`  to add it automatically. If you run into any issues or don’t have python installed just let me know and I can add it for you.

**Comment by ashfaq-shaik** [comment]
Thanks @cocreature . Sorry I dont have a dev-env available, could you please add the headers

**Comment by cocreature** [comment]
@ashfaq-shaik No problem, I’ve added it and pushed to your branch.

**Comment by associahedron** [comment]
Perfect, nice work @ashfaq-shaik @cocreature @neil-da 👍

**Comment by cocreature** [comment]
Thanks again for your contribution @ashfaq-shaik!

**Pull request merged**
