### PR TITLE
Backport version caching fixes

### PR DESCRIPTION
**Pull request by dylant-da**
Backporting https://github.com/digital-asset/daml/pull/17599 and https://github.com/digital-asset/daml/pull/17581

### CODE REVIEW

**Comment by dylant-da** [comment]
Made against wrong branch, restarting

**Comment by garyverhaegen-da** [comment]
You can actually change the target branch in an open PR.

**Comment by dylant-da** [comment]
TIL

**Review by garyverhaegen-da — APPROVED** [review]
I did not review the code but I approve the backporting of it, and the PRs have already been otherwise reviewed on main.

**Pull request merged**
