### PR TITLE
Support Script tests in integration suite

### PR DESCRIPTION
**Pull request by samuel-williams-da**
Adds support for running scripts in the integration test suite
Note, this does not currently use a flag to disable this behaviour, as the flag used for scenarios was only added as Scenarios have been disabled (and as such, threw a warning if not enabled). For ease of understanding, scripts will _always_ be run in accordance to the same predicates that the IDE allows scripts to be run (e.g., may not have arguments).

I've added a simple failing test that ensures the script is being run.

Resolves [#16331](https://github.com/digital-asset/daml/issues/16331)

### CODE REVIEW

**Review by akrmn — APPROVED** [review]
awesome work, thank you @samuel-williams-da!

**Comment by akrmn** [comment]
> Note, this does not currently use a flag to disable this behaviour, as the flag used for scenarios was only added as Scenarios have been disabled (and as such, threw a warning if not enabled). For ease of understanding, scripts will always be run in accordance to the same predicates that the IDE allows scripts to be run (e.g., may not have arguments).

agreed!

**Review by dylant-da — APPROVED** [review]
Looks good to me! Thanks for getting this through :)

**Comment by remyhaemmerle-da** [comment]
:partying_face:

**Pull request merged**
