### PR TITLE
Release 1.11.3 snapshot

### PR DESCRIPTION
**Pull request by gerolf-da**
### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by cocreature — APPROVED** [review]
:parrot:

**Comment by cocreature** [comment]
you’re missing a changelog entry

**Comment by gerolf-da** [comment]
> you’re missing a changelog entry

Thanks. That's what I get for not relying on my git commit template but passing the commit message with `-m` 😬

**Comment by stefanobaghino-da** [comment]
> > you’re missing a changelog entry
> 
> Thanks. That's what I get for not relying on my git commit template but passing the commit message with `-m` grimacing

I generally recommend to have this in your pre-push hook.

```
./ci/check-changelog.sh && ./fmt.sh --diff --test
```

**Pull request merged**
