### PR TITLE
Small fix in formatting to be consistent with other parts

### PR DESCRIPTION
**Pull request by zczapran**
Create and Exercise keywords are usually emboldened in the docs.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [x] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by bame-da** [comment]
HI @zczapran , thank you for this fix, much appreciated. Our build system requires that each Pull Request has a changelog entry in the commit message. The easiest way you can get that in is to amend your commit:

1. `git commit --amend`
2. Add two lines with `CHANGELOG_BEGIN` and `CHANGELOG_END` to the commit message
3. `git push -f`

**Comment by zczapran** [comment]
@bame-da Done. Thanks!

**Pull request merged**
