### PR TITLE
store sandbox perf test results as artifacts

### PR DESCRIPTION
**Pull request by bitonic**
### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/docs/source/support/release-notes.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by garyverhaegen-da** [comment]
My understanding of Azure Pipelines, for what it's worth, is that `$(Build.StagingDirectory)` is a folder that Azure creates for us prior to running a _job_ and deletes at the end of that _job_. A build is composed of multiple jobs which are themselves composed of multiple steps.

Based on that understanding, putting files in `$(Build.StagingDirectory)` is only useful to communicate them to the next steps in the same job. If you want these files to be downloadable from the Azure UI, you have to add a step to "publish" those artifacts, along the lines of:
```
steps:
  - ... [whatever executes the code changed in this PR]
  - task: PublishPipelineArtifact@0
    inputs:
      targetPath: $(Build.StagingDirectory)/logs
      artifactName: perf_logs
```

This would publish a file or folder identified by `targetPath` in the current job so that it can be downloaded by other jobs within the same pipeline, or by people looking at the pipeline build result in the web UI.

Note: there is not need to copy artifacts specifically to `$(Build.StagingDirectory)` for the above step to work, `targetPath` can target any path local to the build. It's probably easier if you aggregate all the log files in a single directory though, which you may choose to create under `$(Build.StagingDirectory)` if that is convenient (because `PublishPipelineArtifact` takes a single `targetPath`).

**Comment by garyverhaegen-da** [comment]
My understanding of Azure Pipelines, for what it's worth, is that `$(Build.StagingDirectory)` is a folder that Azure creates for us prior to running a _job_ and deletes at the end of that _job_. A build is composed of multiple jobs which are themselves composed of multiple steps.

Based on that understanding, putting files in `$(Build.StagingDirectory)` is only useful to communicate them to the next steps in the same job. If you want these files to be downloadable from the Azure UI, you have to add a step to "publish" those artifacts, along the lines of:
```
steps:
  - ... [whatever executes the code changed in this PR]
  - task: PublishPipelineArtifact@0
    inputs:
      targetPath: $(Build.StagingDirectory)/logs
      artifactName: perf_logs
```

This would publish a file or folder identified by `targetPath` in the current job so that it can be downloaded by other jobs within the same pipeline, or by people looking at the pipeline build result in the web UI.

Note: there is not need to copy artifacts specifically to `$(Build.StagingDirectory)` for the above step to work, `targetPath` can target any path local to the build. It's probably easier if you aggregate all the log files in a single directory though, which you may choose to create under `$(Build.StagingDirectory)` if that is convenient (because `PublishPipelineArtifact` takes a single `targetPath`).

**Comment by cocreature** [comment]
@gaverhae We already have a step for publishing the artifacts, see https://github.com/digital-asset/daml/blob/master/ci/build-unix.yml#L34 I guess we should rename that.

**Comment by garyverhaegen-da** [comment]
This broke master; see https://github.com/digital-asset/daml/pull/551 for fix.

**Pull request merged**
