### PR TITLE
[docs] Fix minor typo in doc of exerciseByKey in TS.

### PR DESCRIPTION
**Pull request by arturpoor-da**
changelog_begin
changelog_end

### CODE REVIEW

**Review by cocreature — APPROVED** [review]
Thanks!

**Review by garyverhaegen-da — APPROVED** [review]
Thanks!

**Review by stefanobaghino-da — APPROVED** [review]

**Review by robin-da — APPROVED** [review]
Thanks!

**Comment by arturpoor-da** [comment]
Thank you. Some of the CI tests failed for some reason. I don't think I caused the problem because I only changed 1 line in a comment. What do you suggest?

**Comment by garyverhaegen-da** [comment]
I've asked CI to retry.

**Pull request merged**
