### PR TITLE
Move the metrics API to the observability module [PLEN-35]

### PR DESCRIPTION
**Pull request by nicu-da**
Also split the telemetry code into its own package

### CODE REVIEW

**Comment by lucb-da** [comment]
I think the `telemetry` module should be named `tracing`.
`telemetry` is a really generic word, and the code is actually about tracing.

I might be the one who introduced the word `telemetry` in the code base, some time ago. So: sorry, maybe ?

**Comment by miklos-da** [comment]
> I think the `telemetry` module should be named `tracing`. `telemetry` is a really generic word, and the code is actually about tracing.
> 
> I might be the one who introduced the word `telemetry` in the code base, some time ago. So: sorry, maybe ?

I agree. However, the code is already under the `com.daml.telemetry` package, so it may be worth renaming the Bazel module to match the base package for consistency in a separate PR?

**Review by miklos-da — APPROVED** [review]
LGTM, assuming we don't need to adjust anything else for metrics doc generation in this repo.

**Comment by nicu-da** [comment]
> > I think the `telemetry` module should be named `tracing`. `telemetry` is a really generic word, and the code is actually about tracing.
> > I might be the one who introduced the word `telemetry` in the code base, some time ago. So: sorry, maybe ?
> 
> I agree. However, the code is already under the `com.daml.telemetry` package, so it may be worth renaming the Bazel module to match the base package for consistency in a separate PR?

That's the reasoning for the current naming, better to be consistent but wrong.
We should rename it fully in the future

**Comment by atriantafyllos-da** [comment]
> @atriantafyllos-da As we are moving some files around, do we need to make changes elsewhere in order to get the annotated metrics scraped for the docs from e.g. `InstrumentedExecutorServiceForDocs`?

No, there should not be any problem.

**Pull request merged**
