### PR TITLE
Release another 1.16.x snapshot

### PR DESCRIPTION
**Pull request by realvictorprm**
And here we go again :D

changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by garyverhaegen-da** [comment]
Target branch is wrong, releases are always done from the main branch.

**Review by garyverhaegen-da — CHANGES_REQUESTED** [review]
Needs to target main.

**Comment by realvictorprm** [comment]
Sincerely sorry for the noise, what a mess. I was not aware of that fact yet and after @garyverhaegen-da explanation I did rebase (well not exactly but more or less) and changed the target branch of this PR.

**Review by garyverhaegen-da — APPROVED** [review]

**Comment by realvictorprm** [comment]
OK looks good to go, going to merge in a couple min.

**Comment by oliverse-da** [comment]
Thank you @realvictorprm and @garyverhaegen-da

**Comment by realvictorprm** [comment]
Manual tests passed on Windows.

**Comment by realvictorprm** [comment]
Manual tests passed on Linux.

**Pull request merged**
